Repository mattermost/desktop, pull requests merged in 2018-04, with the labels that each got.

#746 Clear webFrame cache at a certain interval
  src/browser/webview/mattermost.js
Labels: All Platforms, Windows (looking for testers)

#750 Switch default GPU acceleration to false
  src/browser/components/SettingsPage.jsx
  src/common/config/defaultPreferences.js
Labels: All Platforms, Improvement

#745 MM-9922 Don't show hovered URL for internal links
  src/browser/components/MainPage.jsx
Labels: All Platforms, Improvement

#749 Upgrade electron-builder
  electron-builder.json
  package.json
  resources/linux/icon.png
  scripts/cp_artifacts.sh
  yarn.lock
Labels: All Platforms

#752 Make tabs undraggable
  src/browser/components/TabBar.jsx
Labels: All Platforms, Priority 1

#756 Use ES6 import/export for modules
  .eslintrc.json
  package.json
  scripts/.eslintrc.json
  src/browser/components/AutoSaveIndicator.jsx
  src/browser/components/DestructiveConfirmModal.jsx
  src/browser/components/ErrorView.jsx
  src/browser/components/HoveringURL.jsx
  src/browser/components/LoginModal.jsx
  src/browser/components/MainPage.jsx
  src/browser/components/MattermostView.jsx
  src/browser/components/NewTeamModal.jsx
  src/browser/components/PermissionRequestDialog.jsx
  src/browser/components/RemoveServerModal.jsx
  src/browser/components/SettingsPage.jsx
  src/browser/components/TabBar.jsx
  src/browser/components/TeamList.jsx
  src/browser/components/TeamListItem.jsx
  src/browser/config/AppConfig.js
  src/browser/index.jsx
  src/browser/js/badge.js
  src/browser/js/contextMenu.js
  src/browser/js/notification.js
  src/browser/settings.jsx
  src/browser/webview/mattermost.js
  src/common/JsonFileManager.js
  src/common/config/buildConfig.js
  src/common/config/defaultPreferences.js
  src/common/config/pastDefaultPreferences.js
  src/common/config/upgradePreferences.js
  src/common/deepmerge.js
  src/common/osVersion.js
  src/common/settings.js
  src/main.js
  src/main/AppStateManager.js
  src/main/CriticalErrorHandler.js
  src/main/PermissionManager.js
  src/main/SpellChecker.js
  src/main/allowProtocolDialog.js
  src/main/certificateStore.js
  src/main/downloadURL.js
  src/main/mainWindow.js
  src/main/menus/app.js
  src/main/menus/tray.js
  src/main/permissionRequestHandler.js
  src/main/squirrelStartup.js
  src/utils/util.js
  test/.eslintrc.json
  test/specs/app_test.js
  test/specs/permisson_test.js
  test/specs/settings_test.js
  test/specs/spellchecker_test.js
  webpack.config.base.js
  webpack.config.main.js
  webpack.config.renderer.js
Labels: All Platforms

#761 Fix package.json to use correct package name
  package.json
Labels: Windows

#762 Fix an issue where Windows installer crashed in some cases
  src/main.js
  src/main/squirrelStartup.js
Labels: Windows

#760 Truncate long server names in server tabs
  CHANGELOG.md
  src/browser/components/TabBar.jsx
  src/browser/css/components/TabBar.css
Labels: All Platforms, Priority 4

#782 Fix for being unable to type in the form fields on the add server dialog when launched from the tab bar
  CHANGELOG.md
  README.md
  src/browser/components/NewTeamModal.jsx
Labels: All Platforms
