Repository mattermost/desktop, pull requests merged in 2018-06, with the labels that each got.

#822 Upgrade build tools
  package.json
  test/specs/browser/settings_test.js
  webpack.config.base.js
  webpack.config.main.js
  yarn.lock
Labels: All Platforms, Windows (looking for testers)

#815 Update icon for Linux menus to use an SVG icon
  CHANGELOG.md
  electron-builder.json
  resources/linux/create_desktop_file.sh
  resources/linux/icon.png
  resources/linux/icon.svg
Labels: Improvement, Linux, Needs Design

#824 Upgrade dependencies
  package.json
  src/browser/components/NewTeamModal.jsx
  src/package.json
  src/yarn.lock
  yarn.lock
Labels: All Platforms, Windows (looking for testers)

#827 Apply new versioning scheme
  package.json
  src/package.json
Labels: All Platforms

#588 BASH-2 Bundle Mac Desktop App as DMG
  electron-builder.json
  resources/osx/DMG_BG.png
Labels: MacOS, Pending
