Repository mattermost/desktop, pull requests merged in 2018-05, with the labels that each got.

#777 Revert "Merge pull request #745 from mattermost/mm9922"
  src/browser/components/MainPage.jsx
Labels: All Platforms, Bug

#779 Improve error messages on add new server dialog
  CHANGELOG.md
  src/browser/components/NewTeamModal.jsx
Labels: Linux (looking for testers), Priority 3

#786 Update loading animation gif
  src/assets/loading.gif
  src/assets/loading@2x.gif
Labels: All Platforms

#785 Add workaround for permissionRequestHandler error on deep linking
  src/main/permissionRequestHandler.js
Labels: MacOS, Windows

#787 Fix an error where the main page gets blank when adding a server
  src/browser/components/MattermostView.jsx
Labels: All Platforms

#789 Make sure that cookies are saved to disk when closing the app
  src/main.js
  src/main/cookieManager.js
Labels: All Platforms

#791 Fix MattermostView.focusOnWebview() if statement
  src/browser/components/MattermostView.jsx
Labels: All Platforms

#799 Enable GPU hardware acceleration by default
  src/common/config/defaultPreferences.js
  test/specs/browser/settings_test.js
Labels: All Platforms

#812 Fix authentication dialog not working
  src/browser/components/LoginModal.jsx
Labels: All Platforms

#813 Backport #812 to release-4.1
  src/browser/components/LoginModal.jsx
Labels: All Platforms

#816 Update create_desktop_file.sh with categories
  resources/linux/create_desktop_file.sh
Labels: Linux

#818 Update categories of deb packages
  electron-builder.json
Labels: Improvement, Linux

#820 Upgrade Electron stack
  package.json
  test/specs/browser/settings_test.js
  test/specs/security_test.js
  yarn.lock
Labels: All Platforms, Electron
