Repository mattermost/desktop, pull requests merged in 2018-02, with the labels that each got.

#709 Upgrade devDependencies - babel
  .babelrc
  package.json
  webpack.config.renderer.js
  yarn.lock
Labels: All Platforms

#711 Upgrade Electron
  .babelrc
  package.json
  test/specs/app_test.js
  test/specs/browser/settings_test.js
  yarn.lock
Labels: All Platforms, Electron

#712 Fixed an issue where clicking on a file:// protocol path does not open windows explorer since version 3.5.0. #579
  src/browser/components/MattermostView.jsx
Labels: Windows

#719 Upgrade src dependencies
  NOTICE.txt
  package.json
  src/browser/components/MainPage.jsx
  src/browser/css/index.css
  src/package.json
  src/yarn.lock
  test/specs/browser/settings_test.js
  yarn.lock
Labels: All Platforms

#720 Fix app crached after toggling tray icon settings on Mac and Linux
  src/main.js
  test/modules/environment.js
  test/specs/browser/settings_test.js
Labels: Linux, MacOS
