Repository mattermost/desktop, pull requests merged in 2018-03, with the labels that each got.

#722 Whitelabel: Downloads link opens in Mattermost branded window.
  src/browser/components/MattermostView.jsx
Labels: All Platforms

#731 Fix correct spellchecker locale is not selected for non en-US locales
  src/common/config/defaultPreferences.js
  src/common/settings.js
  src/main.js
  test/specs/spellchecker_test.js
Labels: All Platforms

#734 Add "Enable GPU hardware acceleration" option
  src/browser/components/SettingsPage.jsx
  src/common/config/defaultPreferences.js
  src/main.js
  test/specs/browser/settings_test.js
Labels: All Platforms, Linux (looking for testers), Priority 1

#739 Upgrade Electron to 1.7.13
  package.json
  yarn.lock
Labels: All Platforms, Windows (looking for testers)

#741 Upgrade Electron to 1.8.4
  package.json
  yarn.lock
Labels: All Platforms

#733 Ignore did-fail-load event when trying to use U2F devices
  src/browser/components/MattermostView.jsx
Labels: All Platforms, Priority 4

#743 Disable Certificate Transparency verification
  src/main.js
Labels: All Platforms, Windows (looking for testers)

#704 Create configuration guides
  docs/configuration.md
  src/common/config/buildConfig.js
Labels: Priority 2
