Repository mattermost/desktop, pull requests merged in 2019-02, with the labels that each got.

#928 GPO: Configure server addresses and prevent adding new servers
  resources/windows/gpo/en-US/mattermost.adml
  resources/windows/gpo/mattermost.admx
Labels: 2: Dev Review, Hackfest

#929 Fix #538: makes the app not to restart in full-screen mode
  src/main/mainWindow.js
Labels: 2: Dev Review, Hackfest

#926 add a menu to open dev tools for current webview
  src/browser/components/MainPage.jsx
  src/main/menus/app.js
Labels: 3: Ready to Merge, Hackfest

#931 GH-848 Add flag to enable MacOS dark mode title bar
  electron-builder.json
Labels: 2: Dev Review, Hackfest, Improvement, MacOS, MacOS (looking for testers)

#935 add windows certificate to sign the releases
  resources/windows/certificate/mattermost-desktop-windows.pfx.enc
Labels: 3: Ready to Merge

#938 update simple-spellchecker for new dict files
  src/package-lock.json
  src/package.json
Labels: Hackfest
