Repository mattermost/desktop, pull requests merged in 2019-10, with the labels that each got.

#1047 [MM-18906] remove GPU acceleration option from GPO settings
  resources/windows/gpo/en-US/mattermost.adml
  resources/windows/gpo/mattermost.admx
Labels: 3: Reviews Complete

#1052 Merge back Release 4.3.0
  .circleci/config.yml
  electron-builder.json
  package.json
  resources/osx/entitlements.mac.inherit.plist
  resources/windows/certificate/mattermost-desktop-windows.pfx.enc
  resources/windows/gpo/en-US/mattermost.adml
  resources/windows/gpo/mattermost.admx
  resources/windows/license.rtf
  resources/windows/msi_create_folder.ico
  resources/windows/msi_dialog_banner.png
  resources/windows/msi_dialog_banner_small.png
  resources/windows/msi_i18n/en_US.wxl
  resources/windows/msi_modify.ico
  resources/windows/msi_question.ico
  resources/windows/msi_remove.ico
  resources/windows/msi_repair.ico
  resources/windows/msi_up.ico
  resources/windows/msi_warning.ico
  scripts/Makefile.ps1
  scripts/cp_artifacts.sh
  scripts/dependencies.ps1
  scripts/msi_installer.wxs
  scripts/msi_installer_files_replace_id.xslt
  scripts/msi_installer_files_set_win64.xslt
  scripts/tools.ps1
  scripts/wix311.sha
Labels: QA Review Done

#1049 [MM-18936] Guard against bad server url so app doesn't crash
  src/main.js
Labels: 3: Reviews Complete

#1054 MM-19095 – Stop cursor bug fix from running in inactive tabs
  src/browser/components/MattermostView.jsx
Labels: 3: Reviews Complete, QA Review Done

#1048 MM-16373: Change `help` menu shortcut on Windows
  src/main/menus/app.js
Labels: 3: Reviews Complete, QA Review Done

#1053 MM-19096 – simplify custom login process
  src/main.js
Labels: 2: Dev Review, 2: QA Review

#1057 [MM-19208] Allow hidden tabs to still receive unread/mention updates
  src/browser/css/components/MattermostView.css
Labels: 3: Reviews Complete

#1058 [MM-19187] Focus the webview on server selection
  src/browser/components/MainPage.jsx
Labels: 3: Reviews Complete

#1061 [MM-19266] User activity monitor updates
  src/main/UserActivityMonitor.js
  test/specs/main/user_activity_monitor_test.js
Labels: 2: Dev Review

#1066 [MM-19329] Change `Mattermost Desktop` to `Mattermost` in MSI
  scripts/msi_installer.wxs
Labels: 2: Dev Review, CherryPick/Approved

#1065 [MM 19369] Add controlled support for popup windows.
  src/main.js
Labels: 3: Reviews Complete, CherryPick/Approved

#1072 Disable AutoUpdate GPO
  resources/windows/gpo/en-US/mattermost.adml
  resources/windows/gpo/mattermost.admx
Labels: 2: Dev Review

#1073 Update GPO DefaultServerList Description
  resources/windows/gpo/en-US/mattermost.adml
Labels: 1: PM Review, 2: Dev Review

#1031 v4.3 Changelog draft
  CHANGELOG.md
Labels: 3: Reviews Complete, CherryPick/Approved

#1076 [MM-19515] Sign electron builder executable
  scripts/Makefile.ps1
Labels: 2: Dev Review, QA Review Done

#1079 Update CHANGELOG.md to clarify known issues
  CHANGELOG.md
Labels: 3: Reviews Complete

#1086 [MM-19569] add notarization to osx app
  .circleci/config.yml
  electron-builder.json
  package-lock.json
  package.json
  scripts/notarize.js
Labels: 3: Reviews Complete, CherryPick/Approved, MacOS, QA Review Done

#1083 Update add new server icon on the settings page
  src/browser/components/SettingsPage.jsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#1063 [MM-19051] [MM-14180] [MM-19330] Release helpers, push to github and aws, fix weird name on msi at UAC
  .circleci/config.yml
  scripts/Makefile.ps1
  scripts/cp_artifacts.sh
  scripts/generate_release_markdown.sh
  scripts/release.sh
Labels: 2: QA Review, CherryPick/Candidate

#1092 Manually handle misbehaving keyboard shortcuts
  package-lock.json
  package.json
  src/browser/components/MainPage.jsx
  src/main.js
  src/main/menus/app.js
  src/package-lock.json
  src/package.json
Labels: 3: Reviews Complete, CherryPick/Approved
