Repository mattermost/desktop, pull requests merged in 2019-11, with the labels that each got.

#1093 Fixed email links being rejected by will-navigate
  src/main.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1105 [MM-19963] set working directory on start
  scripts/Makefile.ps1
  scripts/notarize.js
  src/main.js
Labels: CherryPick/Approved, QA Review Done

#1106 [MM 19649] Fix blank window when auto-starting the app on login
  src/main.js
  src/main/Validator.js
  src/main/mainWindow.js
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#1097 [MM-19266] Manually exit html fullscreen on macOS when in fullscreen
  src/browser/components/MattermostView.jsx
  src/browser/webview/mattermost.js
  src/main.js
Labels: 1: PM Review, CherryPick/Approved, QA Review Done

#1111 [MM-20645] fix spellchecker
  src/browser/js/contextMenu.js
Labels: 3: Reviews Complete, CherryPick/Approved

#1114 [MM-20348] Fixed DMG background
  electron-builder.json
  resources/osx/DMG_BG.png
Labels: 3: Reviews Complete, QA Review Done
