Repository mattermost/desktop, pull requests merged in 2019-12, with the labels that each got.

#1120 update context
  .circleci/config.yml
Labels: 2: Dev Review

#1113 [MM-20156] Added '99+' message badge for Windows when over 99 mentions are on the badge
  src/browser/index.jsx
  src/browser/js/badge.js
Labels: 3: Reviews Complete, QA Review Done

#1130 [MM-21075] Prevent known teams to open in a new app window
  src/main.js
Labels: 2: Dev Review, QA Review Done

#1124 [MM-14135] allow negative window app positions
  src/main.js
  src/main/Validator.js
  src/utils/util.js
Labels: QA Review Done

#1115 [MM-20659] fixing upgrade
  scripts/msi_installer.wxs
Labels: 2: Dev Review, 2: QA Review, Windows

#1132 [MM-20794] change suggestion on spellchecker locale change
  src/browser/index.jsx
  src/main.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1126 [MM-19205] Allow the use of v2 configs by v1 config desktop apps
  src/common/config/index.js
Labels: 3: Reviews Complete, QA Review Done

#1136 [MM-19223] Created reduced size notification icon to fix pixelation
  src/assets/appicon_48.png
  src/browser/components/MattermostView.jsx
  src/browser/js/notification.js
Labels: 2: QA Review

#1129 [MM-20660] set white background for OSs which have turned off subpixel aliasing
  src/main.js
  src/main/autoUpdater.js
  src/main/mainWindow.js
Labels: QA Review Done

#1127 [MM-20796] Removed visibility: hidden from MM view when error page was showing
  src/browser/components/MattermostView.jsx
Labels: 3: Reviews Complete, QA Review Done

#1123 MM-18754: Desktop: Convert binding functions to arrow functions
  src/browser/components/LoginModal.jsx
  src/browser/components/MainPage.jsx
  src/browser/components/MattermostView.jsx
  src/browser/components/NewTeamModal.jsx
  src/browser/components/TeamList.jsx
  src/browser/components/TeamListItem.jsx
Labels: QA Review Done
