Repository mattermost/desktop, pull requests merged in 2020-01, with the labels that each got.

#1145 MM-20627: Create SECURITY.md
  SECURITY.md
Labels: 2: Dev Review

#1135 [MM-20795] Added auto focus on Server Display Name input field
  src/browser/components/NewTeamModal.jsx
Labels: 3: Reviews Complete, QA Review Done

#1125 [MM-20350] Block Basic auth for non trusted URLs
  src/main.js
Labels: 3: Reviews Complete, QA Review Done

#1133 [MM-20822] Added cut/paste/zoom events to other pages and added exceptions for dev tools and new server modal
  src/browser/components/MainPage.jsx
  src/browser/components/SettingsPage.jsx
  src/browser/updater.jsx
Labels: 2: QA Review

#1152 [MM-20270] Upgrade to Electron 6
  package-lock.json
  package.json
  src/main/UserActivityMonitor.js
Labels: QA Review Done

#1139 Add it-IT spell checker
  src/browser/js/contextMenu.js
  src/main/SpellChecker.js
  test/specs/spellchecker_test.js
Labels: 3: Reviews Complete

#1149 [MM-21195] add file extension on download
  src/main.js
Labels: 3: Reviews Complete, QA Review Done

#1137 [MM-20363] prevent using api to navigate within the app's window
  package.json
  src/browser/components/MattermostView.jsx
  src/main.js
  src/main/allowProtocolDialog.js
  src/utils/util.js
Labels: 2: Dev Review

#1116 CircleCI config tweaks
  .circleci/config.yml
  scripts/generate_release_markdown.sh
Labels: 3: Reviews Complete

#1155 Add pl-PL as spellchecker
  src/browser/js/contextMenu.js
  src/main/SpellChecker.js
  test/specs/spellchecker_test.js
Labels: 2: Dev Review

#1159 [MM-21869] handle downloading in a new way to adapt to electron v6
  src/main.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1110 [MM-18007] macOS app reopens closed window on Cmd+Tab
  src/main/mainWindow.js
  test/specs/app_test.js
Labels: QA Review Done

#1165 [MM-19919] Allow links to other servers to go directly to that server in the app
  src/browser/components/MainPage.jsx
  src/browser/components/MattermostView.jsx
  src/utils/util.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1151 [MM-21341] Changed keyboard shortcut logic to pull focused web contents if an explicitly focused tab is not found
  src/browser/components/MainPage.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1168 [MM-21934] don't do anything on cancel
  src/main.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1167 [MM-22007] Fix MSI download from S3, don't run when not an RC/release
  .circleci/config.yml
  scripts/generate_release_markdown.sh
Labels: 3: Reviews Complete

#1170 [MM-22006] fix name mapping
  src/browser/components/SelectCertificateModal.jsx
Labels: CherryPick/Approved, QA Review Done

#1171 [MM-22073] Added new titlebar to Settings page
  src/browser/components/SettingsPage.jsx
  src/browser/css/settings.css
  src/browser/settings.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1173 [MM-20796] Un-reverted the Ctrl+Tab fix and also made sure the tabs go in the right order
  src/browser/components/MainPage.jsx
  src/browser/components/MattermostView.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done
