Repository mattermost/desktop, pull requests merged in 2020-02, with the labels that each got.

#1164 [MM-21974] improve CSS for client certificate screens
  src/browser/components/SelectCertificateModal.jsx
  src/browser/components/showCertificateModal.jsx
  src/browser/css/components/CertificateModal.css
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1177 Update release-process.md
  docs/release-process.md
Labels: 3: Reviews Complete

#1180 [MM-22193] Workaround for app hang on Windows 10 dark mode
  src/main.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1169 [MM-20832] prevent dialog stacking, move to promises
  src/main.js
Labels: CherryPick/Approved, QA Review Done

#1156 [MM-21400] Enable setuid on linux packaging
  electron-builder.json
  scripts/afterpack.js
Labels: 2: Dev Review, 2: QA Review, CherryPick/Candidate

#1183 [MM-22150] Add default accelerators
  src/main/menus/app.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1186 [MM-19636] make file names consistent
  scripts/Makefile.ps1
  scripts/dependencies.ps1
  scripts/msi_installer.wxs
  scripts/tools.ps1
Labels: 2: Dev Review

#1190 Use ‘isTrustedURL’ function to validate url
  src/main.js
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#1193 [MM-22585] Ctrl/Cmd+<num> now switches to tabs based on order
  src/browser/components/MainPage.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1191 [MM-22494] Fixed misuse of config.set
  src/browser/components/MainPage.jsx
  src/browser/index.jsx
Labels: CherryPick/Approved, QA Review Done

#1192 [MM-22558] fix loginurls on subpath and server's with team in the url
  src/main.js
  src/utils/util.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1198 [MM-22618] Reorder tab menu items to match tab order
  src/main/menus/app.js
  src/main/menus/tray.js
Labels: 1: PM Review, CherryPick/Approved, QA Review Done

#1199 [MM-22558] Fix 3rd party login detection
  src/main.js
Labels: 1: PM Review, CherryPick/Approved, QA Review Done

#1196 [MM-22618] Clicking on setting team links to proper tab
  src/browser/components/SettingsPage.jsx
Labels: 1: PM Review, CherryPick/Approved, QA Review Done

#1197 [MM-22617] Force wrap long server urls in setting page
  src/browser/css/settings.css
Labels: 3: Reviews Complete, QA Review Done
