Repository mattermost/desktop, pull requests merged in 2020-07, with the labels that each got.

#1335 [MM-26665] fix security issues from dependabot
  package-lock.json
  package.json
  src/package-lock.json
  src/package.json
Labels: 2: Dev Review, CherryPick/Candidate

#1341 Bump electron to v7.3.2
  package.json
Labels: 2: Dev Review, CherryPick/Approved

#1343 [MM-26752] Commit package-lock.json for electron version bump
  package-lock.json
Labels: 2: Dev Review

#1345 [MM-26832] don't show the window until it is ready
  src/main/mainWindow.js
Labels: 3: QA Review, CherryPick/Approved

#1339 Fix typo in SettingsPage.jsx
  src/browser/components/SettingsPage.jsx
Labels: 2: Dev Review, Lifecycle/1:stale

#1354 [MM-27331] only show the picker if there is more than 1 cert
  src/main.js
Labels: 4: Reviews Complete

#1338 Fixes MM-22411 : Have the same default protocols as the server in the autolink plugin #1273
  electron-builder.json
Labels: 4: Reviews Complete
