Repository mattermost/desktop, pull requests merged in 2020-09, with the labels that each got.

#1351 [MM-467] Notification sounds
  src/assets/sounds/bing.mp3
  src/assets/sounds/crackle.mp3
  src/assets/sounds/ding.mp3
  src/assets/sounds/down.mp3
  src/assets/sounds/hello.mp3
  src/assets/sounds/ripple.mp3
  src/assets/sounds/upstairs.mp3
  src/browser/components/MattermostView.jsx
  src/browser/js/notification.js
  src/browser/webview/mattermost.js
  src/utils/util.js
Labels: 4: Reviews Complete

#1373 [MM-28595] Open team links within the app
  src/browser/components/MattermostView.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#1376 [MM-25789] - Update default settings for new installations
  src/common/config/defaultPreferences.js
  src/main.js
Labels: 2: Dev Review, QA Review Done
