Repository mattermost/desktop, pull requests merged in 2020-10, with the labels that each got.

#1375 add Russian language in the list available for spellchecking
  src/browser/components/SettingsPage.jsx
  src/browser/js/contextMenu.js
  src/main/SpellChecker.js
  src/package-lock.json
  src/package.json
  test/specs/spellchecker_test.js
Labels: 4: Reviews Complete

#1374 [MM-28620] allow navigating links to admin_console
  src/browser/components/MattermostView.jsx
  src/main.js
  src/utils/util.js
Labels: 4: Reviews Complete

#1379 [MM-27332] show window at autolaunch
  src/browser/components/SettingsPage.jsx
  src/main.js
  src/main/ParseArgs.js
  src/main/autoLaunch.js
  src/main/mainWindow.js
Labels: 3: QA Review

#1385 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved

#1388 [MM-29677] fix download complete notification not appearing
  src/browser/components/MainPage.jsx
Labels: 4: Reviews Complete

#1390 [MM-29702] fix soundname not existing
  src/browser/js/notification.js
Labels: CherryPick/Approved, QA Review Done

#1396 [MM-29921] fix custom sound not playing when receiving a notification
  src/browser/js/notification.js
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved

#1394 Update release-process.md
  docs/release-process.md
Labels: 4: Reviews Complete

#1362 Browserview settings window
  src/main/MattermostServer.js
  src/main/MattermostView.js
  src/main/allowProtocolDialog.js
  src/main/downloadURL.js
  src/main/main.js
  src/main/menus/app.js
  src/main/menus/tray.js
  src/main/viewManager.js
  src/main/windows/mainWindow.js
  src/main/windows/settingsWindow.js
  src/main/windows/windowManager.js
  src/renderer/components/AutoSaveIndicator.jsx
  src/renderer/components/Button/Button.stories.jsx
  src/renderer/components/DestructiveConfirmModal.jsx
  src/renderer/components/ErrorView.jsx
  src/renderer/components/Finder.jsx
  src/renderer/components/HoveringURL.jsx
  src/renderer/components/MainPage.jsx
  src/renderer/components/RemoveServerModal.jsx
  src/renderer/components/SettingsPage.jsx
  src/renderer/components/TabBar.jsx
  src/renderer/components/TeamList.jsx
  src/renderer/components/UpdaterPage.jsx
  src/renderer/components/UpdaterPage/UpdaterPage.stories.jsx
  src/renderer/css/settings.css
  src/renderer/settings.html
  src/renderer/settings.jsx
  src/renderer/updater.jsx
  test/modules/environment.js
  test/specs/browser/index_test.js
  test/specs/security_test.js
  test/specs/spellchecker_test.js
  test/specs/utils/util_test.js
Labels: 4: Reviews Complete
