Repository mattermost/desktop, pull requests merged in 2020-04, with the labels that each got.

#1213 [MM-22363] - Add desktop notification on download complete
  src/browser/components/MainPage.jsx
  src/browser/components/MattermostView.jsx
  src/browser/webview/mattermost.js
  src/main.js
  src/utils/util.js
Labels: 2: Dev Review, QA Review Done

#1248 [MM-23153] Fixed the issue where back/forward navigation not in the main window causes the app to crash
  src/main/menus/app.js
Labels: 3: Reviews Complete, QA Review Done

#1242 [MM022677] fix focus on new server modal
  src/browser/components/MainPage.jsx
  src/browser/components/NewTeamModal.jsx
Labels: QA Review Done

#1216 [MM-22004] Add dragability to the title bar buttons area for macOS
  src/browser/css/index.css
Labels: 3: Reviews Complete, QA Review Done

#1226 [MM-22552] Remove permission request everytime a notification needs to be shown
  src/utils/util.js
Labels: 3: Reviews Complete, QA Review Done

#1256 [MM-23332] fix eslint (#1238)
  .eslintrc-webapp.json
  package-lock.json
  package.json
  scripts/afterpack.js
  src/browser/components/Finder.jsx
  src/browser/components/MattermostView.jsx
Labels: AutoMerge

#1240 [MM-22434] update joi, convert to json before validating
  src/main/Validator.js
  src/main/certificateStore.js
  src/package-lock.json
  src/package.json
Labels: 3: Reviews Complete, QA Review Done

#1247 [MM-23057] add different useragent for popup windows
  src/main.js
Labels: 3: Reviews Complete, QA Review Done

#1257 [MM-23057] add different useragent for popup windows (#1247)
  src/main.js
Labels: AutoMerge

#1258 [MM-23784] Removed unnecessary code for focusing the mattermost view
  src/browser/components/MattermostView.jsx
Labels: 3: Reviews Complete, QA Tests/Done

#1246 [MM-23082] Fixes whitescreen issue on app upgrade / GPO / whitelabeled app deployments
  src/common/config/buildConfig.js
  src/common/config/index.js
Labels: CherryPick/Approved, QA Review Done

#1255 [MM-23793] only ask for permission if we never asked before
  src/browser/components/MattermostView.jsx
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#1261 [MM-23082] cherry pick of #1246
  src/common/config/buildConfig.js
  src/common/config/index.js
Labels: 2: Dev Review, AutoMerge

#1214 [MM-22720] Assume maximize setting when AppleActionOnDoubleClick isn't explicitly set
  src/browser/components/MainPage.jsx
  src/browser/components/SettingsPage.jsx
Labels: 3: Reviews Complete, QA Review Done

#1223 [MM-22229] migrate some operations to promises
  src/browser/components/MattermostView.jsx
  src/main.js
  src/main/cookieManager.js
  src/main/downloadURL.js
  src/main/menus/app.js
Labels: 3: Reviews Complete, QA Review Done

#1249 [MM-23195] fix logic to detect if windows is outside of display boundaries
  src/main.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#1267 [MM-23195] fix logic to detect if windows is outside of display bound…
  src/main.js
Labels: AutoMerge

#1269 [MM-23215] prevent mouse event to go through and click on window
  src/browser/components/MainPage.jsx
Labels: 2: QA Review

#1252 [MM-23663] Fixed z-index ordering of webview vs. error page
  src/browser/components/MattermostView.jsx
  src/browser/css/components/MattermostView.css
Labels: 3: Reviews Complete, QA Review Done
