Repository mattermost/desktop, pull requests merged in 2020-03, with the labels that each got.

#1218 [MM-22361] - Set default preferences to flash app window
  src/common/config/defaultPreferences.js
Labels: 2: QA Review

#1208 [MM-22082] - Add focus to server name field in new server modal
  src/browser/components/NewTeamModal.jsx
Labels: QA Review Done

#1238 [MM-23332] fix eslint
  .eslintrc-webapp.json
  package-lock.json
  package.json
  scripts/afterpack.js
  src/browser/components/Finder.jsx
  src/browser/components/MattermostView.jsx
Labels: 3: Reviews Complete, QA Review Done

#1179 [MM-19856] Add back button when navigating outside of the mattermost team within the app
  .gitignore
  electron-builder.json
  src/assets/fonts/OpenSans-Light.woff2
  src/assets/fonts/open-sans-v13-latin-ext_latin_cyrillic-ext_greek-ext_greek_cyrillic_vietnamese-300.woff2
  src/assets/fonts/open-sans-v13-latin-ext_latin_cyrillic-ext_greek-ext_greek_cyrillic_vietnamese-300italic.woff2
  src/assets/fonts/open-sans-v13-latin-ext_latin_cyrillic-ext_greek-ext_greek_cyrillic_vietnamese-600italic.woff2
  src/assets/fonts/open-sans-v13-latin-ext_latin_cyrillic-ext_greek-ext_greek_cyrillic_vietnamese-italic.woff2
  src/assets/fonts/open-sans-v13-latin-ext_latin_cyrillic-ext_greek-ext_greek_cyrillic_vietnamese-regular.woff2
  src/browser/components/ExtraBar.jsx
  src/browser/components/MainPage.jsx
  src/browser/components/MattermostView.jsx
  src/browser/css/components/ExtraBar.css
  src/browser/css/components/MattermostView.css
  src/browser/css/components/index.css
  src/browser/css/index.css
  src/package-lock.json
  src/package.json
  webpack.config.renderer.js
Labels: 3: Reviews Complete, QA Review Done

#1243 [MM-20742] Null checking on URL pathname when deep linking
  src/browser/components/MainPage.jsx
Labels: 3: Reviews Complete, QA Review Done

#1237 [MM-22653] make upload to github to not run in paralel with s3 upload
  .circleci/config.yml
Labels: 2: Dev Review

#1244 [MM-22479] Added aria-label to 3-dot menu on Windows
  src/browser/components/MainPage.jsx
Labels: 3: Reviews Complete, QA Review Done
