Repository mattermost/desktop, pull requests merged in 2020-06, with the labels that each got.

#1307 Fix typo in release message
  .circleci/config.yml
Labels: 2: Dev Review

#1308 [MM-25681] fix reload
  src/browser/components/MattermostView.jsx
Labels: 2: Dev Review

#1301 [MM-25429]/[MM-25433] fix finder focus, align buttons, keep state consistent
  src/browser/components/Finder.jsx
  src/browser/components/MainPage.jsx
  src/browser/css/components/Finder.css
  src/browser/css/components/MainPage.css
Labels: 4: Reviews Complete

#1309 [MM-25671] fix invalid urls
  src/utils/util.js
Labels: 4: Reviews Complete, CherryPick/Approved

#1313 [MM-24154] - Fix copy/paste mismatch by upgrading electron context menu
  src/package-lock.json
  src/package.json
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done

#1317 [MM-24154] - Fix copy/paste mismatch by upgrading electron context me…
  src/package-lock.json
  src/package.json
Labels: AutoMerge, CherryPick/Done

#1312 [MM-24587] Added margin at top of draggable tab bar to facilitate resizing
  src/browser/css/components/TabBar.css
  src/browser/css/index.css
Labels: 4: Reviews Complete

#1315 [MM-22230] fix promises, reenable trust protocols, reenable capturing unhandled exceptions
  src/main/CriticalErrorHandler.js
  src/main/allowProtocolDialog.js
  src/main/autoUpdater.js
Labels: 4: Reviews Complete, CherryPick/Approved

#1319 [MM-22230] cherry pick #1315
  src/main/CriticalErrorHandler.js
  src/main/allowProtocolDialog.js
  src/main/autoUpdater.js
Labels: AutoMerge

#1323 [MM-25980] no menu for popups
  src/browser/components/MainPage.jsx
Labels: 4: Reviews Complete

#1322 [MM-22751] Removed Windows 10 style border for non-Windows 10 clients
  src/browser/components/MainPage.jsx
  src/browser/components/SettingsPage.jsx
  src/main/mainWindow.js
Labels: 4: Reviews Complete, QA Review Done

#1311 [MM-25748]Allow access to managed resources
  src/browser/components/MattermostView.jsx
  src/common/config/buildConfig.js
  src/main.js
  src/utils/util.js
Labels: 4: Reviews Complete

#1327 [MM-26017] add menu to all windows
  src/browser/components/MainPage.jsx
  src/browser/components/MattermostView.jsx
  src/browser/js/contextMenu.js
  src/browser/settings.jsx
Labels: 4: Reviews Complete
