Repository mattermost/desktop, pull requests merged in 2020-11, with the labels that each got.

#1383 [MM-22013] - Allow users to specify default download locations
  src/browser/components/SettingsPage.jsx
  src/common/config/defaultPreferences.js
  src/main.js
  src/main/Validator.js
Labels: 4: Reviews Complete

#1384 [MM-21835] Use URL instead of the url library
  src/browser/components/MainPage.jsx
  src/browser/components/MattermostView.jsx
  src/browser/components/NewTeamModal.jsx
  src/browser/components/externalLink.jsx
  src/browser/index.jsx
  src/browser/js/contextMenu.js
  src/browser/updater.jsx
  src/common/permissions.js
  src/main.js
  src/main/Validator.js
  src/main/certificateStore.js
  src/main/trustedOrigins.js
  src/utils/url.js
  src/utils/util.js
  test/modules/utils.js
  test/specs/utils/url_test.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#1378 [BrowserView] renderer
  .eslintrc.json
  package-lock.json
  package.json
  src/common/communication.js
  src/common/config/RegistryConfig.js
  src/common/config/index.js
  src/common/utils/constants.js
  src/main/MattermostView.js
  src/main/Validator.js
  src/main/badge.js
  src/main/main.js
  src/main/menus/app.js
  src/main/menus/tray.js
  src/main/preload/mattermost.js
  src/main/utils.js
  src/main/viewManager.js
  src/main/windows/mainWindow.js
  src/main/windows/windowManager.js
  src/renderer/components/ErrorView.jsx
  src/renderer/components/ExtraBar.jsx
  src/renderer/components/MainPage.jsx
  src/renderer/components/MattermostView.jsx
  src/renderer/components/NewTeamModal.jsx
  src/renderer/components/PermissionModal.jsx
  src/renderer/components/SettingsPage.jsx
  src/renderer/css/components/MattermostView.css
  webpack.config.renderer.js
Labels: 2: Dev Review

#1387 Bv menus
  package-lock.json
  package.json
  src/main/MattermostView.js
  src/main/contextMenu.js
  src/main/main.js
  src/main/menus/app.js
  src/main/viewManager.js
  src/main/windows/mainWindow.js
  src/main/windows/settingsWindow.js
  src/renderer/components/MainPage.jsx
  src/renderer/index.jsx
  src/renderer/js/badge.js
  src/renderer/js/notification.js
  src/renderer/settings.jsx
Labels: 2: Dev Review

#1409 [MM-22810] Update loading screen with new design & animation
  .eslintrc.json
  src/assets/window-background-dots.svg
  src/assets/window-background-dots_dark.svg
  src/assets/window-background.svg
  src/assets/window-background_dark.svg
  src/browser/components/LoadingAnimation/LoadingAnimation.jsx
  src/browser/components/LoadingAnimation/LoadingIcon.jsx
  src/browser/components/LoadingAnimation/index.js
  src/browser/components/LoadingScreen.jsx
  src/browser/components/MainPage.jsx
  src/browser/components/MattermostView.jsx
  src/browser/css/components/LoadingAnimation.css
  src/browser/css/components/LoadingScreen.css
  src/browser/css/components/MattermostView.css
  src/browser/css/components/index.css
  src/browser/hooks/useAnimationEnd.js
  src/browser/hooks/useTransitionEnd.js
  src/package.json
Labels: 1: PM Review, QA Review Done

#1403 [MM-22691][Browserview] fix tray icon
  .gitignore
  package-lock.json
  package.json
  src/main/main.js
  src/main/menus/tray.js
  src/main/tray/tray.js
  webpack.config.renderer.js
Labels: 2: Dev Review

#1393 Browserview URLHover
  src/common/communication.js
  src/main/MattermostView.js
  src/main/utils.js
  src/main/viewManager.js
  src/main/windows/mainWindow.js
  src/main/windows/settingsWindow.js
  src/renderer/components/HoveringURL.jsx
  src/renderer/components/MainPage.jsx
  src/renderer/components/urlDescription.jsx
  src/renderer/css/components/HoveringURL.css
  src/renderer/modals/urlView/index.html
  src/renderer/modals/urlView/urlView.jsx
  test/modules/environment.js
  webpack.config.renderer.js
Labels: 2: Dev Review

#1418 [BrowserView] remove remote usage, fix menus and window buttons in Win
  src/common/communication.js
  src/main/main.js
  src/main/windows/windowManager.js
  src/renderer/components/MainPage.jsx
Labels: 4: Reviews Complete

#1397 [MM-22960] - Keep desktop app pinned to task bar when the app upgrades
  scripts/msi_installer.wxs
Labels: 4: Reviews Complete

#1420 [BrowserView] fix different errors when loading config
  package-lock.json
  package.json
  src/common/config/index.js
  src/main/main.js
Labels: 2: Dev Review

#1417 [BrowserView] Native modules & registry access
  package-lock.json
  package.json
  scripts/setup_env_vars.js
  scripts/setup_env_vars.ps1
  src/common/config/RegistryConfig.js
  src/main/main.js
  webpack.config.main.js
Labels: 2: Dev Review
