Repository mattermost/desktop, pull requests merged in 2021-12, with the labels that each got.

#1884 Code cleanup, update eslint from webapp, add ts-prune
  .eslintrc-webapp.json
  package-lock.json
  package.json
  src/common/communication.ts
  src/common/permissions.ts
  src/common/tabs/TabView.ts
  src/main/CriticalErrorHandler.ts
  src/main/UserActivityMonitor.ts
  src/main/appState.ts
  src/main/autoUpdater.ts
  src/main/menus/app.ts
  src/main/menus/tray.ts
  src/main/notifications/Mention.ts
  src/main/utils.ts
  src/main/views/MattermostView.ts
  src/main/views/viewManager.ts
  src/main/views/webContentEvents.ts
  src/main/windows/windowManager.ts
  src/renderer/notificationSounds.ts
Labels: 4: Reviews Complete, release-note-none

#1883 [MM-40329] Unit tests for main/views
  src/main/authManager.ts
  src/main/certificateManager.ts
  src/main/main.ts
  src/main/views/MattermostView.test.js
  src/main/views/MattermostView.ts
  src/main/views/modalManager.test.js
  src/main/views/modalManager.ts
  src/main/views/modalView.test.js
  src/main/views/teamDropdownView.test.js
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEvents.ts
Labels: 4: Reviews Complete, release-note-none

#1885 [MM-40330] Unit tests for main/windows
  src/main/allowProtocolDialog.test.js
  src/main/allowProtocolDialog.ts
  src/main/appState.ts
  src/main/authManager.ts
  src/main/badge.test.js
  src/main/badge.ts
  src/main/certificateManager.ts
  src/main/main.ts
  src/main/menus/app.test.js
  src/main/menus/app.ts
  src/main/menus/tray.ts
  src/main/notifications/index.test.js
  src/main/notifications/index.ts
  src/main/tray/tray.ts
  src/main/views/MattermostView.ts
  src/main/views/modalManager.ts
  src/main/views/teamDropdownView.ts
  src/main/views/webContentEvents.ts
  src/main/windows/mainWindow.test.js
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, release-note-none

#1886 [MM-40192] Don't send message until server is finished reloading
  src/main/views/MattermostView.ts
Labels: 2: Dev Review, release-note

#1890 [MM-40406] Add more singletons, refactor main.ts into pieces, add tests and some cleanup + tests for additional coverage
  .eslintrc.json
  e2e/specs/startup/config.test.js
  package.json
  src/common/communication.ts
  src/common/config/RegistryConfig.test.js
  src/common/config/index.test.js
  src/common/config/index.ts
  src/common/utils/util.ts
  src/jestSetup.js
  src/main/AppVersionManager.test.js
  src/main/AppVersionManager.ts
  src/main/AutoLauncher.test.js
  src/main/AutoLauncher.ts
  src/main/CriticalErrorHandler.test.js
  src/main/CriticalErrorHandler.ts
  src/main/ParseArgs.test.js
  src/main/UserActivityMonitor.test.js
  src/main/UserActivityMonitor.ts
  src/main/allowProtocolDialog.ts
  src/main/app/app.test.js
  src/main/app/app.ts
  src/main/app/config.test.js
  src/main/app/config.ts
  src/main/app/index.ts
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/app/intercom.test.js
  src/main/app/intercom.ts
  src/main/app/utils.test.js
  src/main/app/utils.ts
  src/main/authManager.test.js
  src/main/authManager.ts
  src/main/certificateManager.ts
  src/main/certificateStore.test.js
  src/main/certificateStore.ts
  src/main/constants.ts
  src/main/cookieManager.ts
  src/main/main.ts
  src/main/menus/app.ts
  src/main/menus/tray.ts
  src/main/tray/tray.ts
  src/main/trustedOrigins.test.js
  src/main/trustedOrigins.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
  src/main/windows/settingsWindow.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
  webpack.config.main.js
Labels: 4: Reviews Complete, release-note-none

#1889 [GH-1635] don't validate custom protocol URLs
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEvents.ts
Labels: release-note-none, Contributor

#1919 add hide on start option
  src/common/config/defaultPreferences.ts
  src/common/config/index.ts
  src/common/config/upgradePreferences.test.js
  src/main/Validator.test.js
  src/main/Validator.ts
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
  src/renderer/components/SettingsPage.tsx
  src/types/config.ts
Labels: 2: Dev Review, 3: QA Review, release-note, Contributor

#1928 Disable flaky test
  e2e/specs/server_management/edit_server_modal.test.js
Labels: do-not-merge/release-note-label-needed

#1925 [MM-32946][MM-40602] Ensure URL is valid before showing tooltip link, allow parsed URLs that aren't valid to open in browser
  src/common/utils/url.ts
  src/main/views/MattermostView.test.js
  src/main/views/MattermostView.ts
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEvents.ts
Labels: release-note

#1865 [MM-40574] Fix for race condition where new server modal didn't show initially on Linux, resizing issues
  src/common/communication.ts
  src/main/app/config.test.js
  src/main/app/config.ts
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/app/intercom.ts
  src/main/views/modalManager.ts
  src/main/views/modalView.ts
  src/main/windows/windowManager.ts
Labels: 2: Dev Review, release-note

#1932 [MM-40603] Add timeout for alt press to make sure it doesn't interfere with OS shortcuts
  src/main/views/MattermostView.ts
Labels: 4: Reviews Complete, release-note

#1922 [MM-40632] Updates to the Developer Documentation and README, remove unnecessary files and code
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
  README.md
  TESTING.md
  docs/20160922_mattermost_desktop.png
  docs/configuration.md
  docs/development.md
  docs/release-process.md
  docs/setup.md
  package.json
Labels: 4: Reviews Complete, release-note-none

#1934 [MM-40635] Fix notifications and badges broken during test changes
  src/main/appState.ts
  src/main/views/MattermostView.ts
Labels: 4: Reviews Complete, release-note-none

#1931 [MM-40573] Stop asterisk detection on versions newer than 5.28, force space for the others
  src/main/views/MattermostView.test.js
  src/main/views/MattermostView.ts
Labels: 4: Reviews Complete, release-note

#1927 [MM-26018] Added disclaimer for window flashing on Linux
  src/renderer/components/SettingsPage.tsx
Labels: 2: Dev Review, release-note
