Repository mattermost/desktop, pull requests merged in 2021-03, with the labels that each got.

#1495 [MM-33238] Check for admin URL when toggling back bar
  src/main/views/MattermostView.js
Labels: 4: Reviews Complete

#1490 [MM-31342] fix "save image as" context menu crash
  package-lock.json
  package.json
Labels: 2: Dev Review

#1493 [MM-33231] update jewel on new mentions/when read
  src/main/appState.js
  src/main/main.js
  src/renderer/components/MainPage.jsx
Labels: 2: Dev Review

#1496 [MM-33032] Use `hidden` titleBarStyle value to fix macOS Catalina click issue
  src/main/windows/mainWindow.js
Labels: 4: Reviews Complete

#1494 [MM-32809] Remove Toggle Dark Mode menu item for Windows, enable toggling on Linux
  src/common/config/index.js
  src/main/main.js
  src/main/menus/app.js
Labels: 4: Reviews Complete

#1499 [MM-33334] Restore keyboard shortcuts for menu items moved to roles
  src/main/menus/app.js
Labels: 4: Reviews Complete

#1501 [MM-33434] Upgrade to Electron v11, some other dependency upgrades
  package-lock.json
  package.json
  src/main/contextMenu.js
  src/main/views/MattermostView.js
  src/main/views/modalView.js
  src/main/views/viewManager.js
  src/main/windows/settingsWindow.js
Labels: 4: Reviews Complete

#1502 [MM-33542] Trigger finder cleanup on pressing close or Escape
  src/renderer/modals/finder/finder.jsx
Labels: 2: Dev Review

#1503 [MM-33607] Remove old badge code, update unreads code
  src/main/main.js
  src/main/menus/app.js
  src/renderer/components/MainPage.jsx
  src/renderer/components/TabBar.jsx
  src/renderer/index.jsx
Labels: 4: Reviews Complete

#1498 [MM-33247] Have the app handle links to other teams as a deep link
  src/main/views/webContentEvents.js
Labels: 4: Reviews Complete

#1507 [MM-33373] Trigger the smaller font for 99+ mentions
  src/main/badge.js
  src/main/windows/windowManager.js
Labels: 2: Dev Review

#1504 [MM-32805] Merge master, migrate LoadingScreen to BrowserView
  .circleci/config.yml
  .github/workflows/codeql-analysis.yml
  docs/release-process.md
  package.json
  scripts/Makefile.ps1
  scripts/dependencies.ps1
  scripts/msi_installer.wxs
  scripts/tools.ps1
  src/assets/ding.mp3
  src/assets/window-background-dots.svg
  src/assets/window-background-dots_dark.svg
  src/assets/window-background.svg
  src/assets/window-background_dark.svg
  src/common/communication.js
  src/main/main.js
  src/main/menus/app.js
  src/main/preload/loadingScreenPreload.js
  src/main/preload/mattermost.js
  src/main/views/MattermostView.js
  src/main/views/viewManager.js
  src/main/windows/windowManager.js
  src/renderer/components/LoadingAnimation/LoadingAnimation.jsx
  src/renderer/components/LoadingAnimation/LoadingIcon.jsx
  src/renderer/components/LoadingAnimation/index.js
  src/renderer/components/LoadingScreen.jsx
  src/renderer/components/MainPage.jsx
  src/renderer/css/components/LoadingAnimation.css
  src/renderer/css/components/LoadingScreen.css
  src/renderer/css/components/MattermostView.css
  src/renderer/css/components/index.css
  src/renderer/hooks/useAnimationEnd.js
  src/renderer/hooks/useTransitionEnd.js
  src/renderer/modals/loadingScreen/index.jsx
  webpack.config.main.js
  webpack.config.renderer.js
Labels: 4: Reviews Complete

#1506 [MM-33668] Restore tests to browser-view branch
  .circleci/config.yml
  package-lock.json
  package.json
  src/common/communication.js
  src/main/main.js
  src/main/views/MattermostView.js
  src/main/views/modalView.js
  src/main/views/viewManager.js
  src/main/views/webContentEvents.js
  src/main/windows/mainWindow.js
  src/main/windows/settingsWindow.js
  src/main/windows/windowManager.js
  test/modules/environment.js
  test/specs/app_test.js
  test/specs/browser/index_test.js
  test/specs/browser/settings_test.js
  test/specs/spellchecker_test.js
  test/unit/index.js
  test/unit/trusted_origins_test.js
  webpack.config.base.js
  webpack.config.test.js
Labels: 4: Reviews Complete, AutoMerge

#1509 Cleanup of BrowserView migration, some bug fixes
  src/common/communication.js
  src/common/config/index.js
  src/main/appState.js
  src/main/contextMenu.js
  src/main/main.js
  src/main/menus/app.js
  src/main/notifications/Download.js
  src/main/notifications/Mention.js
  src/main/preload/mattermost.js
  src/main/views/MattermostView.js
  src/main/views/modalManager.js
  src/main/views/modalView.js
  src/main/views/viewManager.js
  src/main/windows/mainWindow.js
  src/main/windows/windowManager.js
  src/renderer/components/ErrorView.jsx
  src/renderer/components/Finder.jsx
  src/renderer/components/LoginModal.jsx
  src/renderer/components/MainPage.jsx
  src/renderer/components/PermissionModal.jsx
  src/renderer/components/SelectCertificateModal.jsx
  src/renderer/components/SettingsPage.jsx
  src/renderer/components/TabBar.jsx
  src/renderer/components/externalLink.jsx
  src/renderer/index.jsx
  src/renderer/settings.jsx
Labels: 4: Reviews Complete

#1508 store daily build to S3
  .circleci/config.yml
Labels: 4: Reviews Complete

#1511 [MM-33551] Keep tray state
  src/main/tray/tray.js
Labels: 2: Dev Review

#1516 [MM-34088] remove listeners before destroy
  src/main/views/MattermostView.js
Labels: 2: Dev Review

#1517 [MM-33828] Define CSP for all BrowserWindows, enable contextIsolation for main/settings window, other fixes
  src/main/preload/mainWindow.js
  src/main/views/MattermostView.js
  src/main/views/webContentEvents.js
  src/main/windows/mainWindow.js
  src/main/windows/settingsWindow.js
  src/renderer/components/MainPage.jsx
  src/renderer/components/SettingsPage.jsx
  src/renderer/components/TabBar.jsx
  src/renderer/index.html
  src/renderer/index.jsx
  src/renderer/settings.jsx
  src/renderer/updater.jsx
  webpack.config.main.js
Labels: 4: Reviews Complete

#1515 [MM-19327] Remove Finder from desktop app
  src/common/communication.js
  src/main/menus/app.js
  src/main/preload/finderPreload.js
  src/main/views/MattermostView.js
  src/main/views/viewManager.js
  src/main/windows/windowManager.js
  src/renderer/css/components/Finder.css
  src/renderer/css/components/index.css
  src/renderer/modals/finder/finder.jsx
  src/renderer/modals/finder/index.jsx
  src/renderer/updater.jsx
  test/specs/app_test.js
  webpack.config.main.js
  webpack.config.renderer.js
Labels: 4: Reviews Complete

#1519 [MM-34067] Explicitly destroy web contents in non-permanent BrowserViews
  src/main/views/MattermostView.js
  src/main/views/modalView.js
  src/main/views/viewManager.js
Labels: 4: Reviews Complete

#1520 Improve daily build ci
  .circleci/config.yml
Labels: 2: Dev Review

#1522 [MM-34201] fix non-links crashing the app
  src/main/views/webContentEvents.js
Labels: 3: QA Review
