Repository mattermost/desktop, pull requests merged in 2021-06, with the labels that each got.

#1595 [GH-317] Correct size for Linux tray icons
  src/assets/linux/ICONS.md
  src/assets/linux/dark/MenuIcon.png
  src/assets/linux/dark/MenuIcon@2x.png
  src/assets/linux/dark/MenuIconMention.png
  src/assets/linux/dark/MenuIconMention@2x.png
  src/assets/linux/dark/MenuIconUnread.png
  src/assets/linux/dark/MenuIconUnread@2x.png
  src/assets/linux/light/MenuIcon.png
  src/assets/linux/light/MenuIcon@2x.png
  src/assets/linux/light/MenuIconMention.png
  src/assets/linux/light/MenuIconMention@2x.png
  src/assets/linux/light/MenuIconUnread.png
  src/assets/linux/light/MenuIconUnread@2x.png
  src/assets/linux/top_bar_dark_16.png
  src/assets/linux/top_bar_dark_16@2x.png
  src/assets/linux/top_bar_dark_mention_16.png
  src/assets/linux/top_bar_dark_mention_16@2x.png
  src/assets/linux/top_bar_dark_unread_16.png
  src/assets/linux/top_bar_dark_unread_16@2x.png
  src/assets/linux/top_bar_light_16.png
  src/assets/linux/top_bar_light_16@2x.png
  src/assets/linux/top_bar_light_mention_16.png
  src/assets/linux/top_bar_light_mention_16@2x.png
  src/assets/linux/top_bar_light_unread_16.png
  src/assets/linux/top_bar_light_unread_16@2x.png
  src/main/tray/tray.js
Labels: 2: Dev Review, Lifecycle/1:stale, release-note

#1619 [MM-19601] Update to v12.0.10, fix alt issue in linux
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note

#1621 Cherry-pick update to v12.0.10 (#1619)
  package-lock.json
  package.json
Labels: release-note

#1620 [MM-35581] Rename arm64 to m1
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note

#1623 [MM-35581] Rename arm64 to m1 (Cherry-pic #1620)
  .circleci/config.yml
Labels: release-note

#1627 [MM-36340] fix linux theme comparison
  src/main/tray/tray.js
Labels: 2: Dev Review, release-note-none

#1628 [MM-36030] Allow for duplicate servers with different names to behave normally
  src/common/config/index.js
  src/main/views/viewManager.js
Labels: 4: Reviews Complete, release-note-none

#1626 [MM-35581] fix m1 rename not being persisted, add rpm to release
  .circleci/config.yml
  scripts/generate_release_markdown.sh
Labels: release-note-none

#1630 [MM-30147] [MM-30146] fix loading path for cert modal
  src/main/certificateManager.js
Labels: 4: Reviews Complete, CherryPick/Candidate, release-note-none

#1631 [MM-30147] [MM-30146] fix loading path for cert modal (#1630)
  src/main/certificateManager.js
Labels: release-note-none

#1633 [MM-36543] Check for webcontents before trying to load url in case tab was removed
  src/main/views/MattermostView.js
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#1641 Update README.md
  README.md
Labels: 4: Reviews Complete, release-note
