Repository mattermost/desktop, pull requests merged in 2021-08, with the labels that each got.

#1678 make electron builder compatible with node v16
  package-lock.json
  package.json
  scripts/cp_artifacts.sh
Labels: 4: Reviews Complete, release-note

#1681 Fix mac installer
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note-none

#1683 [MM-37646] Fixed long server name style issue
  src/renderer/css/dropdown.scss
Labels: 4: Reviews Complete, release-note-none

#1682 [MM-36423][MM-36427] Edit/Delete modals for dropdown
  .circleci/config.yml
  scripts/cp_artifacts.sh
  src/common/communication.ts
  src/main/main.ts
  src/main/preload/dropdown.js
  src/renderer/components/SettingsPage.tsx
  src/renderer/components/TeamList.tsx
  src/renderer/components/TeamListItem.tsx
  src/renderer/css/components/TeamListItem.css
  src/renderer/css/components/index.css
  src/renderer/css/dropdown.scss
  src/renderer/dropdown.tsx
  src/renderer/modals/editServer/editServer.tsx
  src/renderer/modals/removeServer/removeServer.tsx
  webpack.config.renderer.js
Labels: 4: Reviews Complete, release-note

#1689 enable handlers earlier (#1676) - cherry-pick
  src/common/config/index.ts
Labels: do-not-merge/release-note-label-needed

#1693 Remove old `src/node_modules` on `clean` if it exists
  package.json
Labels: 4: Reviews Complete, release-note-none

#1692 fix package lock
  package-lock.json
Labels: 4: Reviews Complete, release-note-none

#1691 [MM-37661][MM-29878] Brand Updates for Desktop v5.0/MM v6.0
  .circleci/config.yml
  electron-builder.json
  src/assets/appicon_48.png
  src/assets/icon.icns
  src/assets/icon.ico
  src/assets/linux/app_icon.png
  src/assets/osx/DMG_BG.png
Labels: 1: UX Review, release-note

#1688 [MM-37743] Fix URL validation when editing/adding a server
  src/common/utils/url.ts
Labels: 4: Reviews Complete, release-note-none

#1696 [MM-37797] Re-added the check for flashing the window
  src/main/windows/windowManager.ts
  src/renderer/components/SettingsPage.tsx
Labels: 4: Reviews Complete, release-note

#1695 [MM-36428][MM-36434][MM-36435] Keyboard navigation and menu updates for new tab/dropdown layout
  .circleci/config.yml
  src/common/communication.ts
  src/main/main.ts
  src/main/menus/app.ts
  src/main/windows/windowManager.ts
  src/renderer/components/MainPage.tsx
  src/renderer/components/TeamDropdownButton.tsx
  src/renderer/css/components/TeamDropdownButton.scss
  src/renderer/dropdown.tsx
Labels: 2: Dev Review, release-note

#1697 [MM-36923] Wait to return to the application before turning off the custom login setting
  src/main/views/webContentEvents.ts
Labels: 4: Reviews Complete, release-note-none

#1702 MM-36234: CRT, handle click on notification
  src/main/main.js
  src/main/notifications/index.js
  src/main/preload/mattermost.js
Labels: release-note-none

#1708 [MM-37954] Fix dragging scrollbar issue
  package-lock.json
  package.json
Labels: 2: Dev Review, release-note

#1699 MM-36234: CRT, handle click on notification
  src/main/main.ts
  src/main/notifications/index.ts
  src/main/preload/mattermost.js
Labels: 4: Reviews Complete, CherryPick/Done, release-note-none

#1700 [MM-36577] Fix electron-builder path for linux files
  electron-builder.json
Labels: 4: Reviews Complete, release-note-none

#1707 [MM-36793][MM-37954] Upgrade to Electron v13.2.0
  .circleci/config.yml
  package-lock.json
  package.json
  src/main/views/webContentEvents.ts
  src/main/windows/mainWindow.ts
Labels: 4: Reviews Complete, release-note

#1706 [MM-37090] Update loading screen branding
  .circleci/config.yml
  src/assets/loader/StippleMask.jpg
  src/assets/window-background-dots.svg
  src/assets/window-background-dots_dark.svg
  src/assets/window-background.svg
  src/assets/window-background_dark.svg
  src/renderer/components/LoadingScreen/LoadingBackground.tsx
  src/renderer/components/LoadingScreen/LoadingScreen.tsx
  src/renderer/components/LoadingScreen/index.ts
  src/renderer/css/components/LoadingAnimation.css
  src/renderer/css/components/LoadingScreen.css
Labels: 4: Reviews Complete, release-note

#1713 Add jobs for automatically building test builds for PRs
  .circleci/config.yml
Labels: 2: Dev Review, release-note-none

#1710 [MM-37797] Invert check logic
  src/renderer/components/SettingsPage.jsx
Labels: 4: Reviews Complete, release-note-none
