Repository mattermost/desktop, pull requests merged in 2021-04, with the labels that each got.

#1526 [MM-34461] Restore Find menu item
  src/main/menus/app.js
  src/main/windows/windowManager.js
Labels: 2: Dev Review

#1527 [MM-33577] Workaround for Linux minimizing/maximizing issue
  src/main/windows/windowManager.js
Labels: 4: Reviews Complete

#1524 [MM-34527] fix reload and long names
  src/common/utils/util.js
  src/main/views/MattermostView.js
  src/main/views/webContentEvents.js
  src/renderer/css/components/TabBar.css
  src/renderer/css/settings.css
Labels: 1: UX Review, 2: Dev Review, 3: QA Review

#1531 [MM-34459] Fix config key to show 'learn more'
  src/main/menus/app.js
Labels: 4: Reviews Complete

#1530 [MM-34528] hide menu bar
  src/main/windows/settingsWindow.js
Labels: 4: Reviews Complete

#1532 prevent eager filtering
  .circleci/config.yml
Labels: 4: Reviews Complete

#1537 [MM-34645] Align App Options header and save indicator using display: inline-block instead of float: left
  src/renderer/components/SettingsPage.jsx
  src/renderer/css/settings.css
Labels: 4: Reviews Complete

#1540 [MM-33903] fix loading screen
  src/common/communication.js
  src/common/utils/constants.js
  src/main/views/MattermostView.js
  src/main/views/viewManager.js
  src/renderer/components/MainPage.jsx
Labels: 4: Reviews Complete

#1543 [MM-34820] Improve spell check's option help text
  src/renderer/components/SettingsPage.jsx
Labels: 4: Reviews Complete, Docs/Needed

#1544 [MM-34494] Encapsulate context menu in a class object and add it to each view as necessary
  src/main/contextMenu.js
  src/main/views/MattermostView.js
  src/main/views/modalView.js
  src/main/views/viewManager.js
  src/main/windows/mainWindow.js
  src/main/windows/settingsWindow.js
Labels: 4: Reviews Complete

#1546 [MM-34890][MM-34897] Fix some fullscreen issues
  src/common/communication.js
  src/main/windows/mainWindow.js
  src/main/windows/settingsWindow.js
  src/renderer/components/MainPage.jsx
Labels: 2: Dev Review, 4: Reviews Complete

#1538 [MM-34594] Only show dock badge when the setting is enabled
  src/main/appState.js
  src/main/badge.js
  src/main/main.js
Labels: 4: Reviews Complete, CherryPick/Candidate

#1549 [MM-35007] don't try to use pressed images with templates
  src/main/tray/tray.js
Labels: 2: Dev Review, CherryPick/Candidate

#1548 Fix msi
  .circleci/config.yml
  scripts/Makefile.ps1
  scripts/msi_installer.wxs
Labels: 4: Reviews Complete, CherryPick/Candidate

#1550 [MM-35010] add m1 architecture support
  package.json
  scripts/generate_release_markdown.sh
Labels: 2: Dev Review, CherryPick/Candidate

#1552 [MM-34884] Only call `show()` on an existing mainWindow if the window is actually closed or hidden
  src/main/windows/windowManager.js
Labels: 4: Reviews Complete, CherryPick/Approved

#1558 [MM-20677] Quarantine files downloaded from electron
  electron-builder.json
Labels: 2: Dev Review

#1536 add PR/Issue template and release notes section in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 4: Reviews Complete, release-note-none

#1559 [MM-35010] Fix m1 release pipeline
  scripts/cp_artifacts.sh
Labels: 2: Dev Review

#1562 [MM-35010] Fix m1 release pipeline (cherry-pick v4.7)
  scripts/cp_artifacts.sh
Labels: release-note-none

#1561 add beta template
  .github/ISSUE_TEMPLATE/beta_report.md
Labels: 2: Dev Review, release-note

#1560 [MM-34836] Cleanse URLs of extra slashes on parsing, and add the image proxy case
  src/common/utils/url.js
  src/main/views/webContentEvents.js
  test/unit/index.js
  test/unit/url_test.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#1565 [MM-34836] Cleanse URLs of extra slashes on parsing, and add the image proxy case (#1560)
  src/common/utils/url.js
  src/main/views/webContentEvents.js
  test/unit/index.js
  test/unit/url_test.js
Labels: do-not-merge/release-note-label-needed

#1564 fix help message spacing
  src/renderer/components/SettingsPage.jsx
Labels: 2: Dev Review, release-note-none

#1568 Make daily links in s3 look always the same to help with rainforest
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note-none

#1569 Fix help message spacing (cherry-pick v4.7)
  src/renderer/components/SettingsPage.jsx
Labels: release-note-none

#1571 [MM-35171] Use modified default user agent string instead of hardcoded
  src/main/utils.js
  src/main/views/MattermostView.js
  src/main/views/webContentEvents.js
Labels: 4: Reviews Complete, release-note-none

#1572 [MM-35278] Remove dependency libappindicator1
  electron-builder.json
Labels: 4: Reviews Complete, release-note

#1576 [MM-35278] Remove dependency libappindicator1 (cherry-pick v4.7)
  electron-builder.json
Labels: release-note

#1577 [MM-35171] Use modified default user agent string instead of hardcoded (#1571) - cherry-pick
  src/main/utils.js
  src/main/views/MattermostView.js
  src/main/views/webContentEvents.js
Labels: do-not-merge/release-note-label-needed

#1573 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#1578 Update NOTICE.txt (#1573) (cherry-pick v4.7
  NOTICE.txt
Labels: do-not-merge/release-note-label-needed

#1574 [MM-35131] Set default app downloads path to specified path in config
  src/main/main.js
Labels: 4: Reviews Complete, release-note-none
