Repository mattermost/desktop, pull requests merged in 2021-09, with the labels that each got.

#1716 add no_output_timeout to 30m (default 10m)
  .circleci/config.yml
Labels: release-note-none

#1680 [MM-36432][MM-37072][MM-37073] Logic to support Focalboard and Playbooks tabs
  .circleci/config.yml
  package-lock.json
  package.json
  src/common/communication.ts
  src/common/tabs/FocalboardTabView.ts
  src/common/tabs/PlaybooksTabView.ts
  src/common/tabs/TabView.ts
  src/common/utils/url.ts
  src/common/utils/util.ts
  src/main/Validator.ts
  src/main/main.ts
  src/main/menus/app.ts
  src/main/preload/mattermost.js
  src/main/server/serverAPI.ts
  src/main/server/serverInfo.ts
  src/main/views/MattermostView.ts
  src/main/views/viewManager.ts
  src/main/views/webContentEvents.ts
  src/main/windows/windowManager.ts
  src/renderer/components/MainPage.tsx
  src/renderer/components/TabBar.tsx
  src/renderer/components/TeamDropdownButton.tsx
  src/renderer/css/components/TabBar.css
  src/renderer/css/components/TeamDropdownButton.scss
  src/types/config.ts
  src/types/server.ts
  src/types/utils.ts
Labels: 1: UX Review, release-note-none

#1720 [MM-36347] Force min window width of 700px
  src/common/utils/constants.ts
  src/main/preload/dropdown.js
  src/main/views/teamDropdownView.ts
  src/main/windows/mainWindow.ts
  src/main/windows/windowManager.ts
  src/renderer/css/components/TeamDropdownButton.scss
  src/renderer/css/dropdown.scss
  src/renderer/dropdown.tsx
Labels: 3: QA Review, release-note-none

#1719 [MM-38301] Check for admin URL when adding space for back bar
  src/main/windows/windowManager.ts
Labels: 3: QA Review, release-note

#1718 [MM-36309] Completely remove menu bar from Linux/Windows
  src/main/main.ts
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, release-note

#1722 [MM-38310][MM-38313][MM-38315] Fixed some issues caused by having multiple tabs
  src/common/communication.ts
  src/common/tabs/BaseTabView.ts
  src/common/tabs/MessagingTabView.ts
  src/common/tabs/TabView.ts
  src/main/main.ts
  src/main/notifications/index.ts
  src/main/preload/mattermost.js
  src/main/views/MattermostView.ts
  src/main/views/viewManager.ts
  src/main/windows/windowManager.ts
  src/renderer/components/MainPage.tsx
  src/renderer/components/TabBar.tsx
Labels: release-note-none

#1724 Make the Window menu on macOS more standard
  src/main/menus/app.ts
Labels: release-note

#1723 Show topbar regardless of whether there are servers or not
  src/renderer/components/MainPage.tsx
  src/renderer/components/TabBar.tsx
  src/renderer/components/TeamDropdownButton.tsx
Labels: 4: Reviews Complete, release-note-none

#1717 [MM-35483] Flip fuses on ELECTRON_RUN_AS_NODE
  package-lock.json
  package.json
  scripts/afterpack.js
Labels: 4: Reviews Complete, release-note-none

#1725 [MM-23452][MM-36861] Fixed some configuration issues
  src/common/communication.ts
  src/common/config/upgradePreferences.ts
  src/main/Validator.ts
  src/main/main.ts
  src/main/views/viewManager.ts
  src/main/windows/windowManager.ts
  src/renderer/components/MainPage.tsx
  src/renderer/index.tsx
  src/types/config.ts
Labels: 4: Reviews Complete, release-note-none

#1728 [MM-38433] Error checking when a bad server URL is entered
  src/main/server/serverAPI.ts
Labels: 4: Reviews Complete, release-note-none

#1726 [MM-38275] Use browser history push for deeplinking and other inter-tab navigation when using a v6.0 server
  src/main/views/MattermostView.ts
  src/main/views/viewManager.ts
Labels: 4: Reviews Complete, release-note-none

#1729 [MM-38316] Remove mention and unread counts for current server from the dropdown button
  src/renderer/components/MainPage.tsx
Labels: 4: Reviews Complete, release-note-none

#1727 [MM-38325] Polished up some of the UI elements
  src/renderer/css/components/TabBar.css
  src/renderer/css/components/TeamDropdownButton.scss
  src/renderer/css/dropdown.scss
Labels: release-note-none

#1730 [MM-38459] Resize the menu instead of removing the browser view altogether
  src/main/views/teamDropdownView.ts
Labels: 4: Reviews Complete, release-note-none

#1733 [MM-16516] Add a "don't trust" option for certificates
  src/main/certificateStore.ts
  src/main/main.ts
  src/types/certificate.ts
Labels: 4: Reviews Complete, release-note

#1734 [MM-38503] Upgrade to Electron v14
  package-lock.json
  package.json
  src/main/views/MattermostView.ts
  src/main/views/modalView.ts
  src/main/views/teamDropdownView.ts
  src/main/views/viewManager.ts
  src/main/views/webContentEvents.ts
  src/main/windows/mainWindow.ts
  src/main/windows/settingsWindow.ts
  src/renderer/updater.tsx
  test/specs/app_test.js
  test/specs/browser/index_test.js
Labels: 4: Reviews Complete, release-note

#1732 [MM-36309] Restore window menu, override shortcuts for window menu so they don't interfere
  src/main/main.ts
  src/main/windows/windowManager.ts
Labels: 2: Dev Review, release-note-none

#1735 [MM-38524] Rework the closing and opening tab logic, fixed login issue
  src/common/communication.ts
  src/common/tabs/TabView.ts
  src/common/utils/util.ts
  src/main/Validator.ts
  src/main/main.ts
  src/main/preload/mattermost.js
  src/main/views/viewManager.ts
  src/main/windows/windowManager.ts
  src/renderer/components/MainPage.tsx
  src/renderer/components/SettingsPage.tsx
  src/renderer/components/TabBar.tsx
  src/types/config.ts
Labels: 4: Reviews Complete, release-note-none

#1738 [MM-38535] Overlay drag region with clickable area when menu is open
  src/renderer/components/MainPage.tsx
  src/renderer/components/TabBar.tsx
  src/renderer/css/components/TabBar.css
Labels: 2: Dev Review, release-note-none

#1739 [MM-38570] Fixed the keyboard shortcuts for switching tabs when some tabs are closed
  src/main/menus/app.ts
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, release-note-none

#1742 Fix typo in mattermost.adml
  resources/windows/gpo/en-US/mattermost.adml
Labels: 4: Reviews Complete, release-note-none

#1737 [MM-38532] Force new server to display when added
  src/main/main.ts
  src/main/views/viewManager.ts
  src/main/windows/windowManager.ts
  src/renderer/components/MainPage.tsx
Labels: 4: Reviews Complete, release-note-none

#1743 [MM-33112] Add support for multiple custom spellchecking languages
  package-lock.json
  package.json
  src/common/communication.ts
  src/common/config/defaultPreferences.ts
  src/common/config/index.ts
  src/common/config/upgradePreferences.ts
  src/common/utils/constants.ts
  src/main/Validator.ts
  src/main/main.ts
  src/renderer/components/SettingsPage.tsx
  src/renderer/css/lazy/settings-dark.lazy.css
  src/renderer/css/settings.css
  src/types/config.ts
Labels: 4: Reviews Complete, release-note

#1746 [MM-36032] Add electron-context-menu to popup windows
  src/main/views/webContentEvents.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#1753 [MM-36032] Add electron-context-menu to popup windows (#1746) - cherrypick
  src/main/views/webContentEvents.ts
Labels: release-note-none

#1750 [MM-37055] Remove commit hash from release builds generated by CircleCI
  src/main/CriticalErrorHandler.ts
  src/main/menus/app.ts
  src/renderer/index.tsx
  webpack.config.base.js
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#1747 [MM-38530] Update build to generate universal binaries
  .circleci/config.yml
  package.json
  scripts/cp_artifacts.sh
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#1751 [MM-38642] Set a max-width for the dropdown button and menu
  src/renderer/css/components/TeamDropdownButton.scss
  src/renderer/css/dropdown.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#1744 [MM-38577] Allow exit of full screen mode using the restore button on Windows
  src/main/windows/windowManager.ts
  src/renderer/components/MainPage.tsx
Labels: 2: Dev Review, CherryPick/Approved, release-note

#1755 [MM-38530] Update build to generate universal binaries (#1747) - cherry-pick
  .circleci/config.yml
  package.json
  scripts/cp_artifacts.sh
Labels: release-note-none

#1756 [MM-38642] Set a max-width for the dropdown button and menu (#1751)
  src/renderer/css/components/TeamDropdownButton.scss
  src/renderer/css/dropdown.scss
Labels: release-note-none

#1757 [MM-38577] Allow exit of full screen mode using the restore button on Windows (#1744) - cherrypick
  src/main/windows/windowManager.ts
  src/renderer/components/MainPage.tsx
Labels: release-note-none

#1749 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#1752 [MM-38679] Fix download notification title on Windows
  src/main/main.ts
  src/main/notifications/Download.ts
  src/main/notifications/index.ts
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#1759 Automated cherry pick of #1752
  src/main/main.ts
  src/main/notifications/Download.ts
  src/main/notifications/index.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#1760 Automated cherry pick of #1750
  src/main/CriticalErrorHandler.ts
  src/main/menus/app.ts
  src/renderer/index.tsx
  webpack.config.base.js
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#1740 remove global shortcuts
  src/main/main.ts
  src/main/windows/mainWindow.ts
Labels: 2: Dev Review, release-note

#1762 Automated cherry pick of #1740
  src/main/main.ts
  src/main/windows/mainWindow.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#1763 Fix tab opening behaviour for playbooks
  src/main/server/serverInfo.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#1765 Automated cherry pick of #1763
  src/main/server/serverInfo.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#1758 [MM-38649] Put top bar in a BrowserView
  src/main/menus/app.ts
  src/main/utils.ts
  src/main/views/teamDropdownView.ts
  src/main/views/viewManager.ts
  src/main/windows/mainWindow.ts
  src/main/windows/windowManager.ts
Labels: CherryPick/Approved, release-note

#1766 Automated cherry pick of #1758
  src/main/menus/app.ts
  src/main/utils.ts
  src/main/views/teamDropdownView.ts
  src/main/views/viewManager.ts
  src/main/windows/mainWindow.ts
  src/main/windows/windowManager.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#1761 Fixed multiple reloads happening on launch
  src/main/views/viewManager.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#1768 Automated cherry pick of #1761
  src/main/views/viewManager.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#1767 [MM-38695] Fixed minimize to tray setting on Linux
  src/renderer/components/SettingsPage.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#1770 Automated cherry pick of #1767
  src/renderer/components/SettingsPage.tsx
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#1764 [MM-38857] Fix spellcheck locales regex
  src/main/Validator.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#1769 [MM-38607] Ensure window is inside one of the screen bounds before rendering
  src/main/windows/mainWindow.ts
Labels: 2: Dev Review, CherryPick/Approved, release-note

#1771 Automated cherry pick of #1764
  src/main/Validator.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#1772 Automated cherry pick of #1769
  src/main/windows/mainWindow.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#1773 Fix for user selection on the dropdown menu button
  src/renderer/css/components/TeamDropdownButton.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#1774 Automated cherry pick of #1773
  src/renderer/css/components/TeamDropdownButton.scss
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed
