Repository mattermost/desktop, pull requests merged in 2021-05, with the labels that each got.

#1579 [MM-35131] Set default app downloads path to specified path in config (#1574)
  src/main/main.js
Labels: do-not-merge/release-note-label-needed

#1580 [MM-35386] Upgrade electron
  package-lock.json
  package.json
Labels: 2: Dev Review, release-note

#1581 [MM-35386] Upgrade electron (cherry-pick v4.7)
  package-lock.json
  package.json
Labels: release-note

#1584 fix wrong folder name for s3_daily
  .circleci/config.yml
Labels: release-note-none

#1583 [MM-35454] Fix default downloads path for Windows and Linux, only set for the app if the path is not blank
  src/common/config/defaultPreferences.js
  src/main/main.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#1582 [MM-35245] Null check to prevent console error in preload script on unloaded server
  src/main/preload/mattermost.js
Labels: 4: Reviews Complete, release-note-none

#1587 [MM-35249] Set window bounds on initial load success
  src/main/views/MattermostView.js
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#1590 [MM-19510][MM-19511] Remove ToastActivatorCLSID from Start Menu shortcut on Windows
  scripts/msi_installer.wxs
Labels: 4: Reviews Complete, release-note

#1600 [MM-35131] Don't set the download location in config if we hit Cancel
  src/renderer/components/SettingsPage.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#1604 [MM-35811][MM-35386] Upgrade to Electron 12
  package-lock.json
  package.json
  src/main/preload/mainWindow.js
  src/main/windows/windowManager.js
Labels: 4: Reviews Complete, CherryPick/Candidate, release-note-none

#1607 [MM-35811][MM-35386] Upgrade to Electron 12 (#1604) (cherry-pick v4.7)
  package-lock.json
  package.json
  src/main/preload/mainWindow.js
  src/main/windows/windowManager.js
Labels: release-note

#1608 [MM-35781] Another workaround for Linux resizing
  src/main/windows/windowManager.js
Labels: 2: Dev Review, release-note-none

#1609 [MM-35781] Another workaround for Linux resizing (#1608)
  src/main/windows/windowManager.js
Labels: do-not-merge/release-note-label-needed

#1611 add rpm build option to electron builder
  electron-builder.json
Labels: 2: Dev Review, 3: QA Review, do-not-merge/release-note-label-needed

#1612 [MM-35662] Added media-src tag to CSP to allow data blobs to play for notification sounds
  src/renderer/index.html
Labels: release-note-none
