Repository mattermost/desktop, pull requests merged in 2021-07, with the labels that each got.

#1639 React bootstrap upgrade to v1, migrate to react-beautiful-dnd
  .circleci/config.yml
  package-lock.json
  package.json
  src/renderer/components/AutoSaveIndicator.tsx
  src/renderer/components/Button/Button.stories.tsx
  src/renderer/components/DestructiveConfirmModal.tsx
  src/renderer/components/ErrorView.tsx
  src/renderer/components/ExtraBar.tsx
  src/renderer/components/MainPage.tsx
  src/renderer/components/NewTeamModal.tsx
  src/renderer/components/RemoveServerModal.tsx
  src/renderer/components/SettingsPage.tsx
  src/renderer/components/TabBar.tsx
  src/renderer/components/TeamListItem.tsx
  src/renderer/components/UpdaterPage.tsx
  src/renderer/components/showCertificateModal.tsx
  src/renderer/css/components/AddServerModal.css
  src/renderer/css/components/ExtraBar.css
  src/renderer/css/components/TabBar.css
  src/renderer/css/components/TeamListItem.css
  src/renderer/css/index.css
  src/renderer/css/modals.css
  src/renderer/css/settings.css
  src/renderer/index.tsx
  src/renderer/modals/certificate/certificateModal.tsx
  src/renderer/modals/login/loginModal.tsx
  src/renderer/modals/permission/permissionModal.tsx
Labels: 4: Reviews Complete, release-note

#1647 [MM-36421] Replace server tabs with dropdown menu
  .circleci/config.yml
  package-lock.json
  package.json
  src/common/communication.ts
  src/common/utils/constants.ts
  src/main/appState.ts
  src/main/main.ts
  src/main/preload/dropdown.js
  src/main/preload/loadingScreenPreload.js
  src/main/preload/mattermost.js
  src/main/utils.ts
  src/main/views/MattermostView.ts
  src/main/views/teamDropdownView.ts
  src/main/views/viewManager.ts
  src/main/windows/windowManager.ts
  src/renderer/assets/fonts/compass-icons/compass-icons.eot
  src/renderer/assets/fonts/compass-icons/compass-icons.svg
  src/renderer/assets/fonts/compass-icons/compass-icons.ttf
  src/renderer/assets/fonts/compass-icons/compass-icons.woff
  src/renderer/assets/fonts/compass-icons/compass-icons.woff2
  src/renderer/components/MainPage.tsx
  src/renderer/components/TabBar.tsx
  src/renderer/components/TeamDropdownButton.tsx
  src/renderer/css/compass-icons.css
  src/renderer/css/components/TabBar.css
  src/renderer/css/components/TeamDropdownButton.scss
  src/renderer/css/dropdown.scss
  src/renderer/css/fonts.css
  src/renderer/css/index.css
  src/renderer/dropdown.tsx
  webpack.config.main.js
  webpack.config.renderer.js
Labels: 4: Reviews Complete, release-note

#1650 Bootstrap v4 dark mode for modals and settings window
  package-lock.json
  package.json
  src/common/communication.ts
  src/main/preload/modalPreload.js
  src/main/views/modalManager.ts
  src/main/windows/windowManager.ts
  src/renderer/css/lazy/modals-dark.lazy.css
  src/renderer/css/lazy/settings-dark.lazy.css
  src/renderer/modals/certificate/certificate.tsx
  src/renderer/modals/darkMode.ts
  src/renderer/modals/login/login.tsx
  src/renderer/modals/newServer/newServer.tsx
  src/renderer/modals/permission/permission.tsx
  src/renderer/settings.tsx
  src/types/external/file-types.d.ts
  webpack.config.renderer.js
Labels: 4: Reviews Complete, release-note

#1653 [MM-36938] Disable gpu before reading the registry
  src/common/config/index.js
  src/main/main.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#1654 [MM-36938] disable gpu before app inits (cherry pick to master)
  src/common/config/index.ts
  src/main/main.ts
Labels: release-note

#1651 [MM-36459] Drag and drop for dropdown
  .circleci/config.yml
  src/main/appState.ts
  src/main/badge.ts
  src/main/preload/dropdown.js
  src/main/views/teamDropdownView.ts
  src/renderer/assets/fonts/compass-icons/compass-icons.eot
  src/renderer/assets/fonts/compass-icons/compass-icons.svg
  src/renderer/assets/fonts/compass-icons/compass-icons.ttf
  src/renderer/assets/fonts/compass-icons/compass-icons.woff
  src/renderer/assets/fonts/compass-icons/compass-icons.woff2
  src/renderer/css/compass-icons.css
  src/renderer/css/dropdown.scss
  src/renderer/dropdown.tsx
Labels: 4: Reviews Complete, release-note-none

#1659 [MM-37117] Prevent crashing if the download path is not set correctly
  src/common/config/defaultPreferences.js
  src/main/main.js
Labels: 2: Dev Review, release-note

#1662 fix crash on invalid download paths
  src/common/config/defaultPreferences.ts
  src/main/main.ts
Labels: 2: Dev Review, release-note

#1660 [MM-36998] Ensure server key must be at least 0
  src/renderer/components/MainPage.tsx
Labels: 4: Reviews Complete, do-not-merge/release-note-label-needed

#1655 [MM-36431] Logic to support multiple configurable tabs per server
  src/common/communication.ts
  src/common/config/defaultPreferences.ts
  src/common/config/index.ts
  src/common/config/pastDefaultPreferences.ts
  src/common/config/upgradePreferences.ts
  src/common/servers/MattermostServer.ts
  src/common/tabs/BaseTabView.ts
  src/common/tabs/FocalboardTabView.ts
  src/common/tabs/MessagingTabView.ts
  src/common/tabs/PlaybooksTabView.ts
  src/common/tabs/TabView.ts
  src/common/utils/url.ts
  src/main/Validator.ts
  src/main/authManager.ts
  src/main/main.ts
  src/main/menus/app.ts
  src/main/preload/dropdown.js
  src/main/preload/mattermost.js
  src/main/views/MattermostView.ts
  src/main/views/teamDropdownView.ts
  src/main/views/viewManager.ts
  src/main/views/webContentEvents.ts
  src/main/windows/windowManager.ts
  src/renderer/components/MainPage.tsx
  src/renderer/components/SettingsPage.tsx
  src/renderer/components/TabBar.tsx
  src/renderer/dropdown.tsx
  src/renderer/index.tsx
  src/types/config.ts
  src/types/utils.ts
Labels: 4: Reviews Complete, release-note

#1666 [MM-36747] Allow users to specify spellchecker url for downloading dictionaries
  src/common/config/index.js
  src/main/Validator.js
  src/main/main.js
  src/main/views/MattermostView.js
  src/renderer/components/SettingsPage.jsx
Labels: 4: Reviews Complete, release-note

#1665 [MM-36753] Revert to Electron v12.0.1
  package-lock.json
  package.json
Labels: 2: Dev Review, release-note-none

#1667 [Mm 37198] enable global sandboxing to increase security
  src/common/config/index.ts
  src/main/main.ts
  src/main/preload/mainWindow.js
  src/main/views/webContentEvents.ts
  src/renderer/components/MainPage.tsx
  src/renderer/index.tsx
  src/types/config.ts
  src/types/window.ts
Labels: 4: Reviews Complete, release-note

#1652 [MM-35946] Remove memoization to prevent errors on detecting unread/mention state
  src/main/views/MattermostView.js
Labels: 3: QA Review, CherryPick/Approved, release-note

#1669 [MM-36747] Spellchecker custom urls (cherrypick to TS)
  src/common/config/index.ts
  src/main/Validator.ts
  src/main/main.ts
  src/renderer/components/SettingsPage.tsx
  src/types/config.ts
Labels: release-note

#1672 allow webpack to resolve .json
  webpack.config.base.js
Labels: 4: Reviews Complete, release-note-none

#1671 [MM-37198] enable global sandboxing to increase security (cherry-pick #1667)
  src/common/config/index.js
  src/main/main.js
  src/main/preload/mainWindow.js
  src/main/views/webContentEvents.js
  src/renderer/components/MainPage.jsx
  src/renderer/index.jsx
Labels: 4: Reviews Complete, release-note

#1674 Remove electron-log from preload (cherry pick for #1673)
  src/main/preload/mattermost.js
Labels: 2: Dev Review, release-note

#1673 remove electron-log from preload
  src/main/preload/mattermost.js
Labels: 2: Dev Review, release-note

#1676 [MM-37480]Fix no handler
  src/common/config/index.js
Labels: 4: Reviews Complete, release-note
