Repository mattermost/desktop, pull requests merged in 2021-02, with the labels that each got.

#1461 [MM-31215][MM-31387] Fixes for bad tab navigation and dragging
  src/common/communication.js
  src/main/viewManager.js
  src/main/windows/windowManager.js
  src/renderer/components/MainPage.jsx
  src/renderer/components/SettingsPage.jsx
Labels: 4: Reviews Complete

#1455 [MM-31650] Restore focus to active server on modal and settings window closure + other fixes
  src/common/communication.js
  src/main/modalManager.js
  src/main/windows/windowManager.js
  src/renderer/components/MainPage.jsx
  src/renderer/components/TabBar.jsx
  src/renderer/css/components/TabBar.css
  src/renderer/modals/newServer/addServer.jsx
  src/renderer/modals/newServer/newServer.jsx
Labels: 4: Reviews Complete

#1462 [MM-32442] Fix event as content bound
  src/main/windows/windowManager.js
Labels: 2: Dev Review

#1459 [MM-32424] fix server devtools being hidden by browserview
  src/main/menus/app.js
Labels: 4: Reviews Complete

#1463 [MM-20227][MM-31388] move to roles and fix focus
  src/main/MattermostView.js
  src/main/menus/app.js
  src/main/windows/mainWindow.js
  src/main/windows/windowManager.js
Labels: 4: Reviews Complete

#1460 [MM-31570] update mentions/unreads/session on jewel, tray and dock
  src/common/communication.js
  src/main/AppVersionManager.js
  src/main/MattermostView.js
  src/main/appState.js
  src/main/badge.js
  src/main/main.js
  src/main/modalView.js
  src/main/preload/mattermost.js
  src/main/tray/tray.js
  src/main/viewManager.js
  src/main/windows/windowManager.js
  src/renderer/components/MainPage.jsx
Labels: 2: Dev Review, Do Not Merge

#1468 [MM-32333] Open public links in the user's default browser
  src/main/main.js
Labels: 4: Reviews Complete

#1467 [MM-31232] fix urlview present with no content
  src/main/viewManager.js
Labels: 2: Dev Review

#1466 [MM-31343] Migrate Finder to BrowserView
  package-lock.json
  package.json
  src/common/communication.js
  src/main/MattermostView.js
  src/main/menus/app.js
  src/main/preload/finderPreload.js
  src/main/viewManager.js
  src/main/windows/windowManager.js
  src/renderer/css/components/Finder.css
  src/renderer/modals/finder/finder.jsx
  src/renderer/modals/finder/index.jsx
  webpack.config.main.js
  webpack.config.renderer.js
Labels: 4: Reviews Complete

#1470 [MM-32382] Use resize event instead of will-resize for monitoring size of BV
  src/main/windows/windowManager.js
Labels: 4: Reviews Complete

#1471 [MM-32570] Use OpenSans as the font for the URL preview modal
  src/renderer/css/components/HoveringURL.css
  src/renderer/modals/urlView/urlView.jsx
Labels: 4: Reviews Complete

#1473 [MM-31554] Add listener for config synchronization on the settings window
  src/main/windows/windowManager.js
  src/renderer/components/SettingsPage.jsx
Labels: 4: Reviews Complete

#1475 [MM-28541] restore deeplinking
  src/common/utils/url.js
  src/main/MattermostView.js
  src/main/main.js
  src/main/viewManager.js
  src/main/windows/mainWindow.js
  src/main/windows/windowManager.js
  src/renderer/components/externalLink.jsx
Labels: 4: Reviews Complete

#1479 MM-32765_prevent crash on checking unread state
  src/main/MattermostView.js
Labels: 4: Reviews Complete

#1481 [MM-31383] Make no the default when asking to add a protocol
  src/main/allowProtocolDialog.js
Labels: 4: Reviews Complete

#1472 [MM-31340] Resize browser view and show back button when on non-team URL
  src/common/communication.js
  src/main/MattermostView.js
  src/main/utils.js
  src/main/windows/windowManager.js
  src/renderer/components/MainPage.jsx
Labels: 2: Dev Review

#1488 [MM-25122] Use modded version of winreg that supports UTF-8
  package-lock.json
  package.json
  src/common/config/RegistryConfig.js
Labels: 2: Dev Review

#1484 [MM-21716] fix appicon path resolution
  src/main/notifications/Download.js
  src/main/notifications/Mention.js
Labels: 4: Reviews Complete

#1487 [MM-33141] Fixed use of bad context in TeamList
  src/renderer/components/TeamList.jsx
Labels: 2: Dev Review

#1483 Add Swedish sv-SE (already in simple-spellchecker)
  src/browser/js/contextMenu.js
  src/main/SpellChecker.js
  test/specs/spellchecker_test.js
Labels: 4: Reviews Complete

#1489 [MM-33050] move webcontent events out of main
  src/common/utils/util.js
  src/main/authManager.js
  src/main/certificateManager.js
  src/main/main.js
  src/main/views/MattermostView.js
  src/main/views/modalManager.js
  src/main/views/modalView.js
  src/main/views/viewManager.js
  src/main/views/webContentEvents.js
  src/main/windows/windowManager.js
Labels: 4: Reviews Complete
