Repository mattermost/desktop, pull requests merged in 2021-01, with the labels that each got.

#1434 [MM-31224] fix reloading servers and other tab issues
  src/main/MattermostView.js
  src/main/viewManager.js
  src/renderer/components/MainPage.jsx
Labels: 2: Dev Review

#1437 Change dev server port
  src/main/main.js
  src/main/utils.js
  webpack.config.renderer.js
Labels: 2: Dev Review

#1438 remove dev_web_server
  package.json
  src/common/utils/constants.js
  src/common/utils/util.js
  src/main/main.js
  src/main/utils.js
Labels: 2: Dev Review

#1433 [MM-31225][MM-31217][MM-31219][Browserview] fix linux compilation + other fixes
  electron-builder.json
  package-lock.json
  package.json
  scripts/setup_env_vars.js
  scripts/setup_env_vars.ps1
  src/common/config/RegistryConfig.js
  src/main/MattermostView.js
  src/main/main.js
  src/main/menus/app.js
  src/main/tray/tray.js
  src/main/viewManager.js
  src/main/windows/settingsWindow.js
  src/renderer/components/MainPage.jsx
  src/renderer/components/SettingsPage.jsx
  webpack.config.main.js
  webpack.config.renderer.js
Labels: 2: Dev Review

#1440 [MM-31923] Fix missing key on apt-get
  .circleci/config.yml
Labels: 4: Reviews Complete

#1400 [MM-31221][BrowserView] first modal: adding a server while in a server view
  docs/development.md
  package-lock.json
  src/common/communication.js
  src/main/MattermostView.js
  src/main/main.js
  src/main/modalManager.js
  src/main/modalView.js
  src/main/preload/mattermost.js
  src/main/preload/modalPreload.js
  src/main/utils.js
  src/main/viewManager.js
  src/main/windows/windowManager.js
  src/renderer/components/MainPage.jsx
  src/renderer/css/components/AddServerModal.css
  src/renderer/index.html
  src/renderer/modals/newServer/addServer.jsx
  src/renderer/modals/newServer/newServer.jsx
  webpack.config.main.js
  webpack.config.renderer.js
Labels: 4: Reviews Complete

#1443 [MM-31987] Allow camera use for jitsi
  .gitignore
  build/entitlements.mac.plist
  electron-builder.json
  resources/osx/entitlements.mac.inherit.plist
Labels: 4: Reviews Complete, CherryPick/Approved

#1441 MM-31882 - Add CodeQL check
  .github/workflows/codeql-analysis.yml
Labels: 2: Dev Review

#1439 [MM-31626] bypass gitlab browser-check for oauth login
  src/browser/components/MattermostView.jsx
  src/main.js
Labels: 4: Reviews Complete, CherryPick/Approved

#1448 add own branch for testing
  .circleci/config.yml
Labels: 4: Reviews Complete

#1445 [MM-30144][MM-30145][MM-30146][MM-30147] Migrate auth and certificate modals to BrowserView
  src/common/communication.js
  src/common/utils/url.js
  src/main/authManager.js
  src/main/certificateManager.js
  src/main/main.js
  src/main/modalView.js
  src/main/preload/modalPreload.js
  src/renderer/components/MainPage.jsx
  src/renderer/css/modals.css
  src/renderer/modals/certificate/certificate.jsx
  src/renderer/modals/certificate/certificateModal.jsx
  src/renderer/modals/login/login.jsx
  src/renderer/modals/login/loginModal.jsx
  src/renderer/modals/permission/permission.jsx
  src/renderer/modals/permission/permissionModal.jsx
  webpack.config.renderer.js
Labels: 4: Reviews Complete

#1456 [browser view] MM-32277 bump version, exe, cache errrors
  .circleci/config.yml
  docs/release-process.md
  package-lock.json
  package.json
  scripts/cp_artifacts.sh
  scripts/manipulate_windows_zip.js
  scripts/release.sh
  src/main/CriticalErrorHandler.js
  src/main/menus/app.js
  src/renderer/index.jsx
  webpack.config.base.js
Labels: 2: Dev Review

#1453 [MM-31467] Move protocol handling over from original MattermostView into web contents handler
  src/main/MattermostView.js
  src/main/allowProtocolDialog.js
  src/main/main.js
Labels: 2: Dev Review

#1457 [MM-32392] prevent crash when checking a URL
  src/main/main.js
Labels: 2: Dev Review
