Repository mattermost/desktop, pull requests merged in 2022-11, with the labels that each got.

#2350 Add readme file for GPO
  resources/windows/gpo/README.md
Labels: 4: Reviews Complete, release-note-none, kind/chore

#2349 [MM-48142] Fix remaining call state issues in main window
  src/common/communication.ts
  src/common/utils/constants.ts
  src/main/preload/callsWidget.js
  src/main/preload/mattermost.js
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
  src/types/calls.ts
Labels: 4: Reviews Complete, release-note-none

#2357 [MM-48167] Only grab the last extension from a filename during Save As
  src/main/downloadsManager.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2360 Automated cherry pick of #2357
  src/main/downloadsManager.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2356 [MM-47710] Override CSP header including allowances for the Web App and Desktop App
  src/common/utils/constants.ts
  src/main/downloadsManager.test.js
  src/main/downloadsManager.ts
  src/main/server/serverAPI.test.js
  src/main/server/serverAPI.ts
  src/main/server/serverInfo.ts
  src/main/utils.test.js
  src/main/utils.ts
  src/main/views/MattermostView.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/webRequest/webRequestManager.ts
  src/renderer/index.html
  src/types/server.ts
  src/types/webRequest.ts
  webpack.config.renderer.js
Labels: 4: Reviews Complete, release-note-none

#2343 [MM-47709] Implement cookie handling
  src/common/communication.ts
  src/main/preload/mainWindow.js
  src/main/utils.ts
  src/main/views/MattermostView.ts
  src/renderer/index.tsx
  src/types/window.ts
Labels: 4: Reviews Complete, release-note-none

#2363 Fixed URL rewrite for Boards
  src/main/views/MattermostView.ts
Labels: 4: Reviews Complete, release-note-none

#2362 [MM-48083] Add websocket overrides
  src/main/views/MattermostView.ts
  src/renderer/index.tsx
  src/types/window.ts
Labels: 4: Reviews Complete, release-note-none

#2380 [MM-48404] Exclude unnecessary binaries for native modules
  electron-builder.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2381 Automated cherry pick of #2380
  electron-builder.json
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2365 [MM-47707] Update styles to allow for general functionality
  src/renderer/components/TabBar.tsx
  src/renderer/css/components/TabBar.css
  src/renderer/css/components/TabBar.scss
  src/renderer/css/index.css
  src/renderer/css/index.scss
  src/renderer/index.html
  src/renderer/index.tsx
  src/renderer/settings.tsx
Labels: 4: Reviews Complete, release-note-none

#2386 [MM-48289] Disable caching on the remote_entry script once it's loaded
  src/main/views/MattermostView.ts
Labels: 4: Reviews Complete, release-note-none

#2387 [MM-47706] Remove direct exposure of the ipcRenderer methods in the Desktop App and only expose specific endpoints
  src/main/preload/mainWindow.js
  src/renderer/components/MainPage.tsx
  src/renderer/components/SettingsPage.tsx
  src/renderer/components/TabBar.tsx
  src/renderer/components/TeamDropdownButton.tsx
  src/renderer/index.tsx
  src/renderer/settings.tsx
  src/types/settings.ts
  src/types/window.ts
Labels: 4: Reviews Complete, release-note-none

#2389 Translations update from Mattermost Weblate
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2393 Bump version to v5.3.0
  package-lock.json
  package.json
Labels: release-note-none

#2407 Automated cherry pick of #2406
  .circleci/config.yml
  package.json
  scripts/cp_artifacts.sh
  scripts/generate_release_markdown.sh
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2412 Automated cherry pick of #2408
  src/main/app/intercom.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2413 [MM-48557] Fix AppImage shortcut
  electron-builder.json
Labels: 2: Dev Review, CherryPick/Approved, release-note

#2414 Automated cherry pick of #2413
  electron-builder.json
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2421 [MM-48383] Upgrade compass-icons
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note, QA Deferred

#2428 [MM-48380] Reworked Linux build process to correctly support ARM64
  .circleci/config.yml
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#2433 Automated cherry pick of #2428
  .circleci/config.yml
  package.json
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2429 Translations update from Mattermost Weblate
  i18n/mk.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2430 [MM-48733] upgrade playwright
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note, QA Deferred

#2431 [MM-48685] Fix failing downloads dropdown items tests
  e2e/specs/downloads/downloads_dropdown_items.test.js
  src/renderer/css/downloadsDropdown.scss
Labels: 4: Reviews Complete, release-note, QA Deferred

#2434 [MM-48682] Stop user from opening the servers menu when no servers are configured
  src/main/app/intercom.test.js
  src/main/menus/app.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#2435 Automated cherry pick of #2434
  src/main/app/intercom.test.js
  src/main/menus/app.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2437 Extend npm run package:* context deadline to 60m
  .circleci/config.yml
Labels: CherryPick/Approved, release-note-none

#2438 Automated cherry pick of #2437
  .circleci/config.yml
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed
