Repository mattermost/desktop, pull requests merged in 2022-01, with the labels that each got.

#1939 Automated cherry pick of #1886
  src/main/views/MattermostView.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#1940 Automated cherry pick of #1932
  src/main/views/MattermostView.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#1933 [MM-36058][MM-40572] Tray fixes
  src/common/config/defaultPreferences.ts
  src/common/config/index.test.js
  src/common/config/index.ts
  src/common/config/migrationPreferences.test.js
  src/common/config/migrationPreferences.ts
  src/main/Validator.test.js
  src/main/Validator.ts
  src/main/constants.ts
  src/main/tray/tray.ts
  src/renderer/components/SettingsPage.tsx
  src/types/config.ts
Labels: 4: Reviews Complete, release-note

#1926 [MM-40009] Add servers dropdown shortcut to menu
  src/main/menus/app.ts
  src/main/preload/dropdown.js
  src/main/windows/mainWindow.ts
  src/renderer/css/dropdown.scss
  src/renderer/dropdown.tsx
Labels: 4: Reviews Complete, release-note

#1944 Menu > Help > version copied to clipboard on click
  src/main/menus/app.ts
Labels: 4: Reviews Complete, release-note, 2022 Contributor Event

#1941 [MM-32371] Communicate history information to webapp for disable/enabling Back/Forward buttons
  src/common/communication.ts
  src/main/menus/app.ts
  src/main/preload/mattermost.js
  src/main/views/MattermostView.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, release-note-none

#1948 change "tab" to "server" in developer tools menu
  src/main/menus/app.ts
Labels: 4: Reviews Complete, release-note, 2022 Contributor Event

#1945 [MM-40822] Remove app.dock.show from restoreMain
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: release-note

#1950 Make WEBSERVER_PORT configurable with env variable
  webpack.config.renderer.js
  webpack.config.test.js
Labels: 4: Reviews Complete, release-note-none, Contributor, 2022 Contributor Event

#1946 [MM-39852] Setup docker image to run in CI for E2E
  .circleci/config.yml
  e2e/modules/environment.js
  e2e/specs/menu_bar/dropdown.test.js
  e2e/specs/menu_bar/view_menu.test.js
  e2e/specs/server_management/edit_server_modal.test.js
  e2e/specs/server_management/remove_server_modal.test.js
  e2e/specs/settings.test.js
  e2e/specs/startup/config.test.js
  package-lock.json
  package.json
  scripts/setup_e2e_docker.js
Labels: 4: Reviews Complete, release-note-none

#1947 [MM-39738] E2E test for Open Settings modal using keyboard shortcuts
  e2e/specs/menu_bar/file_menu.test.js
Labels: 4: Reviews Complete, release-note, Contributor, 2022 Contributor Event

#1656 add a reminder on how to proceed with releases
  scripts/release.sh
Labels: 2: Dev Review, release-note

#1957 Change zoom in shortcut to match expected behavior known from other apps
  src/main/menus/app.ts
Labels: 4: Reviews Complete, release-note, 2022 Contributor Event

#1951 [MM-39799] E2E Test: MM-T4050 Long server name
  e2e/specs/server_management/long_server_name.test.js
Labels: 2: Dev Review, release-note, Contributor, 2022 Contributor Event

#1956 MM-41042: Allow trusted plugin routes
  src/common/utils/url.ts
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEvents.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#1966 test:MM-T125 Copy Link can be used from channel LHS
  e2e/specs/mattermost/copy_link.test.js
Labels: 4: Reviews Complete, release-note, Contributor, 2022 Contributor Event

#1971 Add scorecards analysis
  .github/workflows/scorecards-analysis.yml
Labels: release-note-none, 2022 Contributor Event

#1965 test: Added test for back and forward in history menu
  e2e/specs/menu_bar/history_menu.test.js
Labels: 4: Reviews Complete, release-note, Contributor, 2022 Contributor Event

#1972 test:Signin to another server open using menu bar
  e2e/specs/menu_bar/file_menu.test.js
Labels: 4: Reviews Complete, release-note, Contributor, 2022 Contributor Event

#1969 test: Undo in the menu bar
  e2e/specs/menu_bar/edit_menu.test.js
Labels: 4: Reviews Complete, release-note, Contributor, 2022 Contributor Event

#1959 test:Preferences in the Menu Bar opens the Settings page
  e2e/specs/menu_bar/file_menu.test.js
Labels: 4: Reviews Complete, release-note, Contributor, 2022 Contributor Event

#1981 test : MM-T2465 Linux Dark Mode Toggle
  e2e/specs/linux_dark_mode.test.js
Labels: 4: Reviews Complete, release-note, 2022 Contributor Event

#1980 test: MM-T806 Exit in the Menu Bar
  e2e/specs/menu_bar/file_menu.test.js
Labels: 4: Reviews Complete, release-note, 2022 Contributor Event

#1973 test:MM-T812 Select All in the Menu Bar
  e2e/specs/menu_bar/edit_menu.test.js
Labels: 4: Reviews Complete, release-note, Contributor, 2022 Contributor Event

#1962 [MM-40051] MM-T4385 select tab from menu
  e2e/specs/menu_bar/window_menu.test.js
Labels: 4: Reviews Complete, release-note, Contributor, 2022 Contributor Event

#1975 test:MM-T824/MM-T825 Minimize/Close in the Menu Bar
  e2e/specs/menu_bar/window_menu.test.js
Labels: 4: Reviews Complete, release-note-none, 2022 Contributor Event
