Repository mattermost/desktop, pull requests merged in 2022-07, with the labels that each got.

#2189 [MM-45519] Fix auto updater file patch script
  scripts/patch_updater_yml.sh
Labels: release-note-none

#2180 [MM-40233] Swap names for dark/light tray icons on Linux and Windows
  src/assets/linux/top_bar_dark_16.png
  src/assets/linux/top_bar_dark_16@2x.png
  src/assets/linux/top_bar_dark_mention_16.png
  src/assets/linux/top_bar_dark_mention_16@2x.png
  src/assets/linux/top_bar_dark_unread_16.png
  src/assets/linux/top_bar_dark_unread_16@2x.png
  src/assets/linux/top_bar_light_16.png
  src/assets/linux/top_bar_light_16@2x.png
  src/assets/linux/top_bar_light_mention_16.png
  src/assets/linux/top_bar_light_mention_16@2x.png
  src/assets/linux/top_bar_light_unread_16.png
  src/assets/linux/top_bar_light_unread_16@2x.png
  src/assets/windows/tray_dark.ico
  src/assets/windows/tray_dark_mention.ico
  src/assets/windows/tray_dark_unread.ico
  src/assets/windows/tray_light.ico
  src/assets/windows/tray_light_mention.ico
  src/assets/windows/tray_light_unread.ico
  src/main/tray/tray.ts
Labels: 4: Reviews Complete, release-note, Contributor

#2197 Fixed an issue with a permission modal translation
  i18n/en.json
  src/renderer/modals/permission/permissionModal.tsx
Labels: 2: Dev Review, release-note-none

#2198 Fix mac nightly build
  .circleci/config.yml
  package-lock.json
  package.json
Labels: release-note-none

#2200 Update Licences at Notice.txt to reflect dependency changes.
  NOTICE.txt
Labels: release-note-none, kind/chore

#2202 Translations update from Mattermost Weblate
  i18n/nl.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2203 [MM-45646] Change download notification text to display saved filename instead of original
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
Labels: 4: Reviews Complete, release-note

#2207 [MM-45448] Force electron processes to close after every test on Windows
  e2e/modules/environment.js
  e2e/specs/deep_linking/deeplink.test.js
  e2e/specs/focus.test.js
  e2e/specs/linux_dark_mode.test.js
  e2e/specs/mattermost/back_button.test.js
  e2e/specs/mattermost/copy_link.test.js
  e2e/specs/menu_bar/dropdown.test.js
  e2e/specs/menu_bar/edit_menu.test.js
  e2e/specs/menu_bar/file_menu.test.js
  e2e/specs/menu_bar/history_menu.test.js
  e2e/specs/menu_bar/menu.test.js
  e2e/specs/menu_bar/view_menu.test.js
  e2e/specs/menu_bar/window_menu.test.js
  e2e/specs/popup.test.js
  e2e/specs/relative_url/relative_url.test.js
  e2e/specs/server_management/add_server_modal.test.js
  e2e/specs/server_management/drag_and_drop.test.js
  e2e/specs/server_management/edit_server_modal.test.js
  e2e/specs/server_management/header.test.js
  e2e/specs/server_management/long_server_name.test.js
  e2e/specs/server_management/remove_server_modal.test.js
  e2e/specs/settings.test.js
  e2e/specs/settings/keyboard_shortcuts.test.js
  e2e/specs/startup/app.test.js
  e2e/specs/startup/config.test.js
  e2e/specs/startup/window.test.js
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#2209 Fix some issues caused by i18n addition
  e2e/modules/environment.js
  src/common/utils/util.ts
  src/main/app/utils.test.js
  src/main/app/utils.ts
  src/renderer/modals/login/login.tsx
  src/renderer/modals/login/loginModal.tsx
  src/renderer/modals/permission/permission.tsx
  src/renderer/modals/permission/permissionModal.tsx
Labels: 4: Reviews Complete, release-note-none

#2204 [MM-43941] Optimize app resizing on Windows/Linux by waiting for the viewport to resize
  src/common/communication.ts
  src/main/preload/mattermost.js
  src/main/views/viewManager.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, release-note, QA Deferred

#2213 [MM-45980] Add entitlements for read/write to a few key user directories
  entitlements.mas.plist
Labels: 4: Reviews Complete, release-note

#2214 Fix windows resize
  src/main/windows/windowManager.ts
Labels: release-note-none
