Repository mattermost/desktop, pull requests merged in 2022-12, with the labels that each got.

#2436 Reduced package size by moving most depedencies to devDependencies
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#2451 Automated cherry pick of #2431
  e2e/specs/downloads/downloads_dropdown_items.test.js
  src/renderer/css/downloadsDropdown.scss
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2459 Update feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 4: Reviews Complete, release-note-none

#2467 Translations update from Mattermost Weblate
  i18n/hi.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2469 Translations update from Mattermost Weblate
  i18n/hi.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2472 [MM-49049] Fix main window disappering on call join
  src/main/windows/callsWidgetWindow.ts
Labels: 4: Reviews Complete, release-note-none

#2466 Fixed some unit tests and add test step to run on Windows/Mac builds
  .circleci/config.yml
  e2e/specs/downloads/downloads_manager.test.js
  e2e/specs/startup/app.test.js
  src/main/diagnostics/steps/internal/loggerHooks.test.js
  src/main/diagnostics/steps/internal/obfuscators.ts
  src/main/windows/windowManager.test.js
Labels: 4: Reviews Complete, release-note-none, E2E/Playwright

#2476 Restore original MattermostView functionality
  src/main/views/MattermostView.test.js
  src/main/views/MattermostView.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: 2: Dev Review, release-note-none

#2477 Re-enable multiple tabs and allow for browser history push between them
  src/common/utils/constants.ts
  src/main/preload/mattermost.js
  src/main/utils.test.js
  src/main/utils.ts
  src/main/views/MattermostView.ts
  src/main/views/viewManager.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
  src/renderer/browserHistory.ts
  src/renderer/mattermost.tsx
  src/types/window.ts
Labels: 2: Dev Review, release-note-none

#2478 Remove check job and perform check on each build
  .circleci/config.yml
Labels: 2: Dev Review, release-note-none

#2479 Fix flaky unit test
  src/main/diagnostics/steps/internal/utils.test.js
Labels: 2: Dev Review, release-note-none

#2480 Fix MSI
  .circleci/config.yml
Labels: release-note-none

#2481 Proper MSI fix
  .circleci/config.yml
  scripts/Makefile.ps1
Labels: release-note-none
