Repository mattermost/desktop, pull requests merged in 2022-03, with the labels that each got.

#1988 [MM-30713] Stop Linux and Windows app from minimizing/hiding without user warning
  src/common/config/defaultPreferences.ts
  src/common/config/index.ts
  src/main/Validator.ts
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
  src/renderer/components/SettingsPage.tsx
  src/types/config.ts
Labels: 4: Reviews Complete, release-note

#2009 [MM-42010] Remove CircleCI check for E2E tests
  .circleci/config.yml
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#2010 [MM-42072] Fix issues with loading screen animations
  src/main/views/MattermostView.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/renderer/components/LoadingAnimation/LoadingAnimation.tsx
Labels: 4: Reviews Complete, release-note

#2015 Update nightly job
  .circleci/config.yml
Labels: release-note-none

#2016 Changes for MSI build for autoupdater
  .circleci/config.yml
  scripts/Makefile.ps1
  scripts/cp_artifacts.sh
Labels: release-note-none

#2017 CircleCI fix
  .circleci/config.yml
Labels: do-not-merge/release-note-label-needed

#2003 MM-41988 Updated links to legacy domain about.mm.com
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/troubleshooting-question.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  PULL_REQUEST_TEMPLATE.md
  SECURITY.md
  package.json
  scripts/generate_release_markdown.sh
  src/assets/linux/README.md
  src/common/config/buildConfig.ts
Labels: 4: Reviews Complete, QA Review Done, release-note

#2013 [MM-42086] Upgrade to Electron v17
  package-lock.json
  package.json
  src/common/communication.ts
  src/main/preload/mattermost.js
  src/main/views/MattermostView.ts
  src/main/views/modalView.ts
  src/main/views/teamDropdownView.ts
  src/main/views/viewManager.ts
  src/main/views/webContentEvents.ts
  src/main/windows/mainWindow.ts
  src/main/windows/settingsWindow.ts
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, release-note

#2018 [MM-42024] Enable React Developer Tools for nightly builds
  package.json
  src/main/app/initialize.ts
  src/main/preload/mattermost.js
  webpack.config.base.js
Labels: 4: Reviews Complete, release-note-none

#2020 [MM-42587] Fix typo in unread checking code
  src/main/preload/mattermost.js
Labels: 4: Reviews Complete, release-note

#2023 [MM-42538] Submit nightly builds to TestFlight for macOS
  .circleci/config.yml
  .gitignore
  electron-builder.json
  entitlements.mas.inherit.plist
  entitlements.mas.plist
  fastlane/Fastfile
  package.json
  scripts/afterpack.js
  scripts/notarize.js
  scripts/patch_mas_version.sh
  src/assets/icon.icns
  src/main/app/initialize.ts
  src/main/app/utils.test.js
  src/main/app/utils.ts
  src/types/config.ts
  webpack.config.base.js
Labels: release-note-none

#2026 Attempt to fix linux build
  electron-builder.json
  src/assets/icon.icns
  src/assets/osx/osx_icon.icns
Labels: do-not-merge/release-note-label-needed

#1968 Fullscreen mode
  src/common/config/defaultPreferences.ts
  src/common/config/index.ts
  src/common/config/upgradePreferences.test.js
  src/common/config/upgradePreferences.ts
  src/main/ParseArgs.ts
  src/main/Validator.test.js
  src/main/Validator.ts
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
  src/renderer/components/SettingsPage.tsx
  src/types/config.ts
  src/types/global.d.ts
Labels: 4: Reviews Complete, release-note, 2022 Contributor Event

#2030 Update ISSUE_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: 2: Dev Review, release-note-none

#2027 Add `skip_waiting_for_build_processing` to CI build
  fastlane/Fastfile
Labels: 2: Dev Review, release-note-none

#2033 Add separate deb and rpm builds for CI
  package.json
Labels: 4: Reviews Complete, release-note-none

#2031 [MM-41999] Add additional logging for debugging, allow users to change log level
  src/common/config/RegistryConfig.test.js
  src/common/config/index.test.js
  src/common/config/index.ts
  src/jestSetup.js
  src/main/AutoLauncher.test.js
  src/main/CriticalErrorHandler.test.js
  src/main/Validator.test.js
  src/main/Validator.ts
  src/main/allowProtocolDialog.test.js
  src/main/app/app.test.js
  src/main/app/app.ts
  src/main/app/config.test.js
  src/main/app/config.ts
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/app/intercom.ts
  src/main/app/utils.test.js
  src/main/app/utils.ts
  src/main/appState.ts
  src/main/authManager.test.js
  src/main/authManager.ts
  src/main/autoUpdater.test.js
  src/main/badge.ts
  src/main/certificateManager.test.js
  src/main/certificateManager.ts
  src/main/certificateStore.ts
  src/main/notifications/index.test.js
  src/main/notifications/index.ts
  src/main/server/serverAPI.test.js
  src/main/server/serverAPI.ts
  src/main/server/serverInfo.ts
  src/main/trustedOrigins.test.js
  src/main/trustedOrigins.ts
  src/main/views/MattermostView.test.js
  src/main/views/MattermostView.ts
  src/main/views/modalManager.test.js
  src/main/views/modalManager.ts
  src/main/views/modalView.test.js
  src/main/views/teamDropdownView.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEvents.ts
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
  src/renderer/components/SettingsPage.tsx
  src/types/config.ts
Labels: 4: Reviews Complete, release-note
