Repository mattermost/desktop, pull requests merged in 2022-02, with the labels that each got.

#1977 test:MM-T808 Redo in the Menu Bar
  e2e/specs/menu_bar/edit_menu.test.js
Labels: 4: Reviews Complete, release-note, Contributor, 2022 Contributor Event

#1982 test:MM-T1308 Check that external links dont open in the app
  e2e/specs/relative_url/relative_url.test.js
Labels: 2: Dev Review, release-note, Contributor, 2022 Contributor Event

#1976 test:MM-T816 Toggle Full Screen in the Menu Bar
  e2e/specs/menu_bar/view_menu.test.js
Labels: 2: Dev Review, release-note, Contributor, 2022 Contributor Event

#1979 test:MM-T817/MM-T818/MM-T819 Zooming in the Menu Bar
  e2e/specs/menu_bar/view_menu.test.js
Labels: 4: Reviews Complete, release-note, Contributor, 2022 Contributor Event

#1991 [MM-41559] Dynamically size URL view to avoid overlapping bottom links
  src/common/communication.ts
  src/main/preload/urlView.js
  src/main/views/viewManager.ts
  src/renderer/components/urlDescription.tsx
  webpack.config.main.js
Labels: 4: Reviews Complete, release-note

#1993 [MM-41392] Clean path name on browser pushes for subpaths
  src/main/windows/windowManager.ts
Labels: 2: Dev Review, release-note-none

#2000 [MM-41392] Ensure pathname starts with `/`
  src/main/windows/windowManager.ts
Labels: 2: Dev Review, release-note-none

#2001 Deb repo test
  .circleci/config.yml
  electron-builder.json
  scripts/cp_artifacts.sh
  scripts/generate_deb_repo.sh
  scripts/generate_release_markdown.sh
Labels: Do Not Merge, do-not-merge/release-note-label-needed

#2005 Nightly deployment changes
  .circleci/config.yml
  scripts/generate_deb_repo.sh
Labels: do-not-merge/release-note-label-needed

#1983 [MM-T2637] Double-Clicking on the header should minimize/maximize the app
  e2e/specs/server_management/header.test.js
Labels: 4: Reviews Complete, release-note, Contributor, 2022 Contributor Event

#1990 [MM-T820][MM-T821] Toggle developer Tools in the Menu Bar
  e2e/specs/menu_bar/view_menu.test.js
Labels: 4: Reviews Complete, release-note-none, Contributor, 2022 Contributor Event
