Repository mattermost/desktop, pull requests merged in 2022-08, with the labels that each got.

#2216 [MM-46114] More fixes for Windows resizing
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, release-note-none

#2219 Fix MAS build
  electron-builder.json
Labels: do-not-merge/release-note-label-needed

#2221 Update Licences at Notice.txt to reflect dependency changes.
  NOTICE.txt
Labels: 2: Dev Review, do-not-merge/release-note-label-needed, kind/chore

#2222 [MM-46305] Add reporting code for E2E tests
  .gitignore
  e2e/save_report.js
  e2e/utils/artifacts.js
  e2e/utils/constants.js
  e2e/utils/report.js
  e2e/utils/test_cases.js
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#2224 Translations update from Mattermost Weblate
  i18n/ca.json
  i18n/es.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/sv.json
  i18n/zh-CN.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2225 Revert "Translations update from Mattermost Weblate"
  i18n/ca.json
  i18n/es.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/sv.json
  i18n/zh-CN.json
Labels: do-not-merge/release-note-label-needed

#2220 MM-25003_Improve Onboarding screens for the desktop app - Intro Screen
  e2e/specs/startup/app.test.js
  e2e/specs/startup/welcome_screen_modal.test.js
  e2e/utils/artifacts.js
  e2e/utils/test_cases.js
  i18n/en.json
  src/assets/fonts/Metropolis-Light.woff
  src/assets/fonts/Metropolis-LightItalic.woff
  src/assets/fonts/Metropolis-Regular.woff
  src/assets/fonts/Metropolis-RegularItalic.woff
  src/assets/fonts/Metropolis-SemiBold.woff
  src/assets/fonts/Metropolis-SemiBoldItalic.woff
  src/common/communication.ts
  src/main/ParseArgs.ts
  src/main/app/config.test.js
  src/main/app/config.ts
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/app/intercom.test.js
  src/main/app/intercom.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
  src/renderer/assets/svg/bullseye.svg
  src/renderer/assets/svg/channels.svg
  src/renderer/assets/svg/chat2.svg
  src/renderer/assets/svg/clipboard.svg
  src/renderer/components/Carousel/Carousel.tsx
  src/renderer/components/Carousel/CarouselButton.tsx
  src/renderer/components/Carousel/CarouselPaginationIndicator.tsx
  src/renderer/components/Carousel/index.ts
  src/renderer/components/Header/Header.tsx
  src/renderer/components/Header/index.ts
  src/renderer/components/Logo.tsx
  src/renderer/components/MainPage.tsx
  src/renderer/components/WelcomeScreen/WelcomeScreen.tsx
  src/renderer/components/WelcomeScreen/WelcomeScreenSlide.tsx
  src/renderer/components/WelcomeScreen/index.ts
  src/renderer/css/_css_variables.scss
  src/renderer/css/components/Button.scss
  src/renderer/css/components/Carousel.scss
  src/renderer/css/components/CarouselButton.scss
  src/renderer/css/components/CarouselPaginationIndicator.scss
  src/renderer/css/components/Header.scss
  src/renderer/css/components/WelcomeScreen.scss
  src/renderer/css/components/WelcomeScreenSlide.scss
  src/renderer/css/fonts.css
  src/renderer/css/index.css
  src/renderer/modals/welcomeScreen/welcomeScreen.tsx
  webpack.config.renderer.js
Labels: 4: Reviews Complete, release-note

#2228 Fix for some flaky E2E tests
  e2e/modules/environment.js
Labels: release-note-none

#2231 Fix for mac unit tests
  src/main/notifications/index.test.js
Labels: 4: Reviews Complete, release-note-none

#2229 Remove cypress related dependency and reporting unsupported diagnostic, and ignore e2e/webpack from unit jest
  e2e/utils/report.js
  e2e/utils/test_cases.js
  package.json
Labels: 2: Dev Review, release-note-none

#2233 Fix node-gyp build on Windows
  .circleci/config.yml
  package-lock.json
  package.json
  scripts/Makefile.ps1
Labels: 2: Dev Review, release-note-none

#2232 MM-46445_Add a way to bypass Desktop App onboarding to `buildConfig`
  .circleci/config.yml
  src/common/config/buildConfig.ts
  src/common/config/defaultPreferences.ts
  src/common/config/index.ts
  src/main/Validator.test.js
  src/main/Validator.ts
  src/main/app/intercom.ts
  src/types/config.ts
Labels: 4: Reviews Complete, release-note-none

#2238 Remove buildConfig patch
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note-none

#2236 [MM-46535] Fix E2E tests for reporting purposes
  e2e/specs/mattermost/back_button.test.js
  e2e/specs/menu_bar/dropdown.test.js
  e2e/specs/menu_bar/view_menu.test.js
  e2e/specs/menu_bar/window_menu.test.js
  e2e/specs/server_management/add_server_modal.test.js
  e2e/specs/server_management/drag_and_drop.test.js
  e2e/specs/server_management/header.test.js
  e2e/specs/server_management/long_server_name.test.js
  e2e/specs/settings.test.js
Labels: 2: Dev Review, release-note-none

#2241 [MM-46533] Remove buildConfig item and add webpack flags for onboarding screens and GPU acceleration
  .circleci/config.yml
  package.json
  src/common/config/buildConfig.ts
  src/common/config/defaultPreferences.ts
  src/common/config/index.ts
  src/main/Validator.test.js
  src/main/Validator.ts
  src/main/app/initialize.ts
  src/main/app/intercom.ts
  src/types/config.ts
  webpack.config.base.js
Labels: 4: Reviews Complete, release-note-none

#2237 [MM-45003] Fix the infinite redirect caused by MFA sending the login signal repeatedly
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, release-note

#2239 [MM-46405] Drop support for asterisk-based unreads
  src/main/views/MattermostView.test.js
  src/main/views/MattermostView.ts
Labels: 4: Reviews Complete, release-note

#2245 Remove notification logging from info
  src/main/notifications/index.ts
Labels: 2: Dev Review, release-note-none

#2244 Add recommended VSCode extensions
  .editorconfig
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  src/renderer/index.html
Labels: 4: Reviews Complete, release-note-none, kind/chore
