Repository mattermost/desktop, pull requests merged in 2022-06, with the labels that each got.

#2149 Create configuration folder for notice.txt generation
  .config/notice-file/Readme.md
  .config/notice-file/config.yaml
Labels: release-note-none, kind/chore

#2152 [MM-44644] Update configured server URL from SiteURL if available
  src/main/app/intercom.ts
  src/main/app/utils.test.js
  src/main/app/utils.ts
  src/main/server/serverInfo.ts
  src/types/server.ts
Labels: 4: Reviews Complete, release-note

#2157 Automated cherry pick of #2153
  src/main/app/app.test.js
  src/main/app/app.ts
  src/main/views/MattermostView.test.js
  src/main/views/MattermostView.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2151 Fix MAS/TestFlight nightly build
  package.json
Labels: 4: Reviews Complete, release-note-none

#2161 Update Licences at Notice.txt to reflect dependency changes.
  NOTICE.txt
Labels: 4: Reviews Complete, release-note-none, kind/chore

#2162 [MM-44071] Fixed an issue where the first client certificate could not be selected
  src/renderer/modals/certificate/certificateModal.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#2166 Automated cherry pick of #2162
  src/renderer/modals/certificate/certificateModal.tsx
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2167 Update to Electron 18.3.0
  package-lock.json
  package.json
Labels: release-note

#2168 Update to Electron 18.3.0 (#2167)
  package-lock.json
  package.json
Labels: release-note-none

#2170 Automated cherry pick of #2169
  e2e/modules/environment.js
  e2e/specs/focus.test.js
  e2e/specs/mattermost/back_button.test.js
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2174 [MM-44932] Fixed issue where deleting a server doesn't switch to another server (or show the new server modal)
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
Labels: release-note-none

#2176 [MM-40711] Upgrade to Electron v19.0.6
  package-lock.json
  package.json
Labels: 4: Reviews Complete, Docs/Needed, release-note

#2178 [MM-44931] Allow zoom in/out when Shift is pressed
  e2e/specs/menu_bar/view_menu.test.js
  src/main/menus/app.ts
Labels: 4: Reviews Complete, release-note, Contributor
