Repository mattermost/desktop, pull requests merged in 2022-04, with the labels that each got.

#2035 Fix daily upload for Rainforest builds
  .circleci/config.yml
Labels: 2: Dev Review, release-note-none

#2040 Fix a typo in the nightly build
  .circleci/config.yml
Labels: release-note-none

#2038 [MM-43039] Upgrade and clean up dependencies
  .eslintrc-webapp.json
  NOTICE.txt
  package-lock.json
  package.json
  src/main/Validator.ts
  src/main/app/utils.test.js
  src/main/notifications/Download.ts
  src/main/notifications/Upgrade.ts
  src/main/tray/tray.ts
  src/main/utils.ts
  src/main/windows/windowManager.ts
  src/renderer/components/ExtraBar.tsx
  src/renderer/components/MainPage.tsx
  src/renderer/components/SettingsPage.tsx
  src/renderer/css/index.css
  src/renderer/notificationSounds.ts
  webpack.config.base.js
  webpack.config.main.js
  webpack.config.renderer.js
  webpack.config.test.js
Labels: 4: Reviews Complete, release-note

#1964 [MM-39661] MM-T827 Select Next/Previous Tab
  e2e/specs/menu_bar/window_menu.test.js
Labels: 4: Reviews Complete, release-note, Contributor, 2022 Contributor Event

#2041 [MM-39673][MM-T1288] E2E Test: Keyboard Shortcuts in Settings Page
  e2e/specs/settings/keyboard_shortcuts.test.js
  src/renderer/components/SettingsPage.tsx
Labels: release-note-none

#2043 [MM-39793][MM-T2633] E2E Test: Use back button to return to the desktop app login - and fixes
  e2e/specs/mattermost/back_button.test.js
  package-lock.json
  package.json
  src/common/utils/url.ts
  src/main/utils.test.js
  src/main/utils.ts
  src/main/views/MattermostView.test.js
  src/main/views/MattermostView.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, release-note-none

#2044 [MM-39794] E2E Test: Drag and Drop
  e2e/specs/server_management/drag_and_drop.test.js
Labels: 4: Reviews Complete, release-note-none

#2048 [MM-39747][MM-T1315][MM-T1316][MM-T1317] E2E Test: Ensure focus is returned to Mattermost view
  e2e/specs/focus.test.js
Labels: 4: Reviews Complete, release-note-none

#2047 [MM-39796][MM-39872][MM-T1659][MM-T2827] E2E Tests for Popups
  e2e/specs/popup.test.js
  e2e/specs/settings/keyboard_shortcuts.test.js
Labels: 4: Reviews Complete, release-note-none

#2051 [MM-26016] Hide tray icon theme colour when tray icon not enabled
  src/renderer/components/SettingsPage.tsx
Labels: 4: Reviews Complete, release-note

#2052 Upgrade to Electron v18.0.3 to fix MAS rejection
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#2050 [MM-43185] Fix size of BrowserView for URLView
  src/main/views/viewManager.ts
  src/renderer/css/components/HoveringURL.css
Labels: 4: Reviews Complete, release-note

#2049 [MM-31547] Stop users from being able to enter the same server name or URL twice
  e2e/specs/server_management/add_server_modal.test.js
  e2e/specs/server_management/edit_server_modal.test.js
  src/main/app/intercom.ts
  src/renderer/components/NewTeamModal.tsx
  src/renderer/modals/editServer/editServer.tsx
  src/renderer/modals/newServer/newServer.tsx
Labels: 4: Reviews Complete, release-note

#2053 Fix issue where opening a new view causes the original view still to push
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: 2: Dev Review, release-note

#2058 Add MAS to release pipeline
  .circleci/config.yml
Labels: release-note-none

#2059 Fixes to the release script
  .circleci/config.yml
  scripts/generate_release_markdown.sh
Labels: release-note-none

#2060 Update NOTICE.txt
  NOTICE.txt
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#2062 Automated cherry pick of #2060
  NOTICE.txt
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2063 Fix download folder for MAS
  src/common/config/defaultPreferences.ts
Labels: CherryPick/Approved, release-note-none

#2064 Fix version numbers
  package.json
Labels: CherryPick/Approved, release-note-none

#2065 Automated cherry pick of #2064
  package.json
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2066 Automated cherry pick of #2063
  src/common/config/defaultPreferences.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2067 Automated cherry pick of #2059
  .circleci/config.yml
  scripts/generate_release_markdown.sh
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2068 Create makefile and pipeline to generate signed debian packages.
  .gitlab-ci.yml
  Makefile
Labels: 2: Dev Review, release-note-none, Changelog/Not Needed, kind/chore

#2070 MAS: remove default download location
  src/common/config/defaultPreferences.ts
  src/main/app/initialize.ts
  src/types/config.ts
Labels: 2: Dev Review, release-note-none

#2071 Automated cherry pick of #2068
  .gitlab-ci.yml
  Makefile
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2072 Automated cherry pick of #2070
  src/common/config/defaultPreferences.ts
  src/main/app/initialize.ts
  src/types/config.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2074 [MM-43632] Ensure handleURLView is called when removing the target URL
  src/main/views/MattermostView.test.js
  src/main/views/MattermostView.ts
Labels: 2: Dev Review, CherryPick/Approved, release-note

#2073 [MM-30272] Update to electron builder v23.0.8
  package-lock.json
  package.json
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#2077 Automated cherry pick of #2074
  src/main/views/MattermostView.test.js
  src/main/views/MattermostView.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2078 Automated cherry pick of #2073
  package-lock.json
  package.json
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2075 Fix release markdown
  .circleci/config.yml
  scripts/generate_release_markdown.sh
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#2079 Automated cherry pick of #2075
  .circleci/config.yml
  scripts/generate_release_markdown.sh
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2081 Automated cherry pick of #2080
  src/renderer/components/MainPage.tsx
  src/renderer/css/components/UpgradeButton.scss
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed
