Repository mattermost/desktop, pull requests merged in 2023-01, with the labels that each got.

#2496 Allow for changing of status lint, fix lint issues
  src/main/server/serverAPI.ts
  src/main/views/MattermostView.ts
  src/main/webRequest/webRequestHandler.ts
  src/main/webRequest/webRequestManager.ts
  src/main/windows/windowManager.ts
Labels: 2: Dev Review, release-note-none

#2501 [MM-48363] Default to opening a file when it is clicked from the download list
  src/common/communication.ts
  src/main/preload/downloadsDropdown.js
  src/main/views/downloadsDropdownView.ts
  src/renderer/components/DownloadsDropdown/DownloadsDropdownItemFile.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#2503 Translations update from Mattermost Weblate
  i18n/hr.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2128 [MM-44004] Optionally turn off UTF-8 encoding for winreg if the system doesn't support it
  src/common/config/RegistryConfig.test.js
  src/common/config/RegistryConfig.ts
Labels: 4: Reviews Complete, release-note

#2111 Update Display Name for MSI
  scripts/msi_installer.wxs
Labels: 2: Dev Review, release-note-none, Contributor

#2508 Left-clicking on system tray hides the app to tray when it is already visible.
  src/main/tray/tray.ts
Labels: 4: Reviews Complete, release-note, Contributor

#2511 Translations update from Mattermost Weblate
  i18n/pt.json
Labels: 4: Reviews Complete, do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2513 Translations update from Mattermost Weblate
  i18n/uk.json
Labels: 4: Reviews Complete, do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2514 Fixed an issue where opening the app with a deeplink may cause the app not to redirect to the correct URL
  src/main/views/MattermostView.ts
Labels: 4: Reviews Complete, release-note

#2518 Add await to the dark mode toggle test for Linux
  e2e/specs/linux_dark_mode.test.js
Labels: 4: Reviews Complete, release-note-none

#2519 [MM-50011] Disable popping the dialog box for uncaught exceptions on E2E tests
  e2e/specs/linux_dark_mode.test.js
  package.json
  src/main/CriticalErrorHandler.ts
Labels: 4: Reviews Complete, release-note-none

#2475 [MM-49082] Hide menu bar in calls popout window
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
Labels: 4: Reviews Complete, release-note-none

#2522 [MM-49690] Set currentView to `undefined` instead of using `delete`
  src/main/views/viewManager.ts
Labels: 2: Dev Review, release-note-none

#2521 [MM-49692][MM-49183] Switch webContents URL checks over to the mm-desktop URLs
  src/common/utils/constants.ts
  src/common/utils/url.ts
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/utils.ts
  src/main/views/MattermostView.test.js
  src/main/views/MattermostView.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEvents.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, release-note-none

#2529 Run npm i to save exact version of jest
  package-lock.json
Labels: release-note-none, kind/chore

#2530 [MM-49689] Force `/api/v4/files` links to not open a new window and download correctly
  src/main/downloadsManager.ts
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEvents.ts
Labels: 4: Reviews Complete, release-note-none
