Repository mattermost/desktop, pull requests merged in 2023-06, with the labels that each got.

#2745 [MM-52984] Fix minimized window not showing when clicking the notification
  src/main/notifications/index.test.js
  src/main/notifications/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2746 Automated cherry pick of #2745
  src/main/notifications/index.test.js
  src/main/notifications/index.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2748 [MM-53056] Force a pathname when checking for deep links
  src/common/servers/serverManager.test.js
  src/common/servers/serverManager.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2749 Automated cherry pick of #2748
  src/common/servers/serverManager.test.js
  src/common/servers/serverManager.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2739 [MM-52333] Create Server View State module, move into new `app` module
  src/app/serverViewState.test.js
  src/app/serverViewState.ts
  src/common/servers/serverManager.ts
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/app/intercom.test.js
  src/main/app/intercom.ts
  src/main/app/servers.ts
  src/main/app/views.test.js
  src/main/app/views.ts
  src/main/menus/app.test.js
  src/main/menus/app.ts
  src/main/menus/tray.test.js
  src/main/menus/tray.ts
  src/main/views/serverDropdownView.test.js
  src/main/views/serverDropdownView.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  webpack.config.base.js
Labels: 2: Dev Review, release-note-none

#2752 [MM-53201] Fix piping concurrency issues with release post generation script
  scripts/generate_release_post.sh
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2753 Automated cherry pick of #2752
  scripts/generate_release_post.sh
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2755 Translations update from Mattermost Weblate
  i18n/vi.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2759 Force install of ARM64 Electron headers
  .github/workflows/build-for-pr.yml
  .github/workflows/ci.yaml
  .github/workflows/nightly-main.yml
  .github/workflows/nightly-rainforest.yml
  .github/workflows/release.yaml
  scripts/Makefile.ps1
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2764 [MM-53199] Update to use `notarytool`
  package-lock.json
  package.json
  scripts/notarize.js
Labels: 4: Reviews Complete, release-note-none

#2772 [MM-53294] Fix bad user feedback on server URL validation when plugins are disabled
  src/app/serverViewState.test.js
  src/app/serverViewState.ts
  src/main/server/serverInfo.ts
Labels: 4: Reviews Complete, release-note

#2771 [MM-53295] Fix crash in diagnostics when server is unreachable
  src/main/diagnostics/steps/internal/utils.ts
  src/main/diagnostics/steps/step3.serverConnectivity.ts
  src/main/server/serverInfo.ts
Labels: 2: Dev Review, release-note

#2774 Translations update from Mattermost Weblate
  i18n/th.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2751 MM-52857 - Add call-join-request to calls widget
  src/common/communication.ts
  src/main/preload/callsWidget.js
  src/main/preload/mattermost.js
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/types/calls.ts
Labels: 4: Reviews Complete, release-note-none

#2776 Fix E2E test report upload URL
  e2e/utils/artifacts.js
Labels: release-note-none

#2777 [MM-50536] Add workaround for Dev Tools not opening correctly on Mac
  src/main/views/MattermostBrowserView.ts
Labels: 4: Reviews Complete, release-note-none
