Repository mattermost/desktop, pull requests merged in 2023-09, with the labels that each got.

#2812 [MM-54279] Fix issues around working with saved downloads
  src/common/JsonFileManager.ts
  src/main/downloadsManager.ts
Labels: 4: Reviews Complete, release-note-none

#2814 [MM-54276] Stop URL from being populated on validation regardless of change/timeout
  src/renderer/components/ConfigureServer.tsx
Labels: 4: Reviews Complete, release-note-none

#2811 [MM-54170] Automatically set the logging level to info if not specified
  src/common/config/defaultPreferences.ts
  src/common/log.test.js
  src/common/log.ts
Labels: 4: Reviews Complete, release-note

#2816 Bump to version 5.6
  package-lock.json
  package.json
Labels: release-note-none

#2820 Cherry-pick of https://github.com/mattermost/desktop/pull/2819
  i18n/de.json
  i18n/ja.json
  i18n/ko.json
  i18n/pl.json
  i18n/ru.json
  i18n/sv.json
  i18n/zh-CN.json
Labels: release-note-none

#2823 Automated cherry pick of #2822
  e2e/specs/mattermost/back_button.test.js
  package-lock.json
  package.json
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2821 Fix top bar theme when changing the system settings
  src/renderer/components/MainPage.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#2825 Automated cherry pick of #2821
  src/renderer/components/MainPage.tsx
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2827 Translations update from Mattermost Weblate
  i18n/fr.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2831 [MM-54465] Remove lowercase call when checking path names
  src/common/Validator.ts
  src/common/utils/url.test.js
  src/common/utils/url.ts
  src/main/windows/callsWidgetWindow.test.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#2834 Automated cherry pick of #2831
  src/common/Validator.ts
  src/common/utils/url.test.js
  src/common/utils/url.ts
  src/main/windows/callsWidgetWindow.test.js
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2830 Fix issue where logging will be stuck on `info` level
  src/common/log.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#2835 Automated cherry pick of #2830
  src/common/log.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2829 [MM-54463] Enforce secure keyboard entry on macOS when a password box is focused
  src/common/communication.ts
  src/main/app/initialize.ts
  src/main/app/intercom.ts
  src/main/preload/mattermost.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2836 Automated cherry pick of #2829
  src/common/communication.ts
  src/main/app/initialize.ts
  src/main/app/intercom.ts
  src/main/preload/mattermost.js
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2837 [MM-54509] Upgrade to Electron v26.2.1
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#2838 [MM-54509] Upgrade to Electron v26.2.1 (#2837)
  package-lock.json
  package.json
Labels: release-note-none

#2832 [MM-54465] Add Permissions Manager, require manual interaction to approve use of microphone and camera, to send notifications, and to use location per server
  i18n/en.json
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/constants.ts
  src/main/notifications/index.test.js
  src/main/notifications/index.ts
  src/main/permissionsManager.test.js
  src/main/permissionsManager.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#2839 Automated cherry pick of #2832
  i18n/en.json
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/constants.ts
  src/main/notifications/index.test.js
  src/main/notifications/index.ts
  src/main/permissionsManager.test.js
  src/main/permissionsManager.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2840 Add debugging for notification script
  .github/workflows/release.yaml
  scripts/generate_release_post.sh
Labels: CherryPick/Approved, release-note-none

#2841 Automated cherry pick of #2840
  .github/workflows/release.yaml
  scripts/generate_release_post.sh
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2842 Revert "Add debugging for notification script (#2840)"
  .github/workflows/release.yaml
  scripts/generate_release_post.sh
Labels: CherryPick/Approved, release-note-none

#2843 Automated cherry pick of #2842
  .github/workflows/release.yaml
  scripts/generate_release_post.sh
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2846 Force end notification to pull all commits
  .github/workflows/release.yaml
Labels: CherryPick/Approved, release-note-none

#2847 Automated cherry pick of #2846
  .github/workflows/release.yaml
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2848 Cherrypick translations (#2844)
  i18n/de.json
  i18n/pl.json
  i18n/ru.json
  i18n/tr.json
Labels: release-note-none

#2849 Fix multiple permission dialogs displaying for the same permission check
  src/main/permissionsManager.test.js
  src/main/permissionsManager.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2850 Automated cherry pick of #2849
  src/main/permissionsManager.test.js
  src/main/permissionsManager.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2851 [MM-54617] Remove regex matching for URL lookups
  src/common/servers/serverManager.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2854 Automated cherry pick of #2851
  src/common/servers/serverManager.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2856 Remove gconf dependencies for debian as no longer needed by Electron.
  electron-builder.json
Labels: 4: Reviews Complete, release-note

#2860 [GH-2857] Allow only macOS to call setSecureKeyboardEntryEnabled
  src/main/app/intercom.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2862 [MM-54591] Use getVersion endpoint to report app name
  src/main/preload/desktopAPI.js
  src/renderer/components/DownloadsDropdown/DownloadsDropdownItem.tsx
  src/renderer/components/DownloadsDropdown/DownloadsDropdownItemFile.tsx
  src/renderer/components/DownloadsDropdown/Update/UpdateAvailable.tsx
  src/renderer/components/DownloadsDropdown/Update/UpdateDownloaded.tsx
  src/renderer/components/DownloadsDropdown/Update/UpdateWrapper.tsx
  src/renderer/downloadsDropdown.tsx
  src/types/window.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note
