Repository mattermost/desktop, pull requests merged in 2023-11, with the labels that each got.

#2893 [MM-55054] Consider a matching origin for a media request as a trusted URL when checking permissions
  src/main/permissionsManager.test.js
  src/main/permissionsManager.ts
Labels: 4: Reviews Complete, release-note

#2890 Removing empy zh_Han* files that are raising an alert in Weblate
  i18n/zh_Hans.json
  i18n/zh_Hant.json
Labels: Hacktoberfest, Lifecycle/1:stale, release-note-none, Contributor

#2905 [MM-55261] Allow embedded video links to go fullscreen after a permission check
  src/main/permissionsManager.ts
Labels: 2: Dev Review, 3: Security Review, release-note

#2907 [MM-55317] Force deep linking to use formatted path names when rewriting the URL
  src/main/views/viewManager.ts
Labels: 4: Reviews Complete, release-note

#2909 [MM-55466] Update to node-gyp v10 to fix Python script error
  package-lock.json
  package.json
Labels: CherryPick/Approved, release-note-none

#2910 Automated cherry pick of #2909
  package-lock.json
  package.json
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2911 Bump to version v5.7
  package-lock.json
  package.json
Labels: release-note-none

#2912 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Done, release-note

#2913 Automated cherry pick of #2912
  NOTICE.txt
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2904 chore: migrate AWS SDK for JavaScript v2 APIs to v3
  e2e/utils/artifacts.js
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none, Contributor
