Repository mattermost/desktop, pull requests merged in 2023-08, with the labels that each got.

#2807 Replaced hardcoded app name with parameter in localizable strings
  i18n/en.json
  src/renderer/components/DownloadsDropdown/DownloadsDropdownItemFile.tsx
  src/renderer/components/DownloadsDropdown/Update/UpdateAvailable.tsx
  src/renderer/components/DownloadsDropdown/Update/UpdateDownloaded.tsx
  src/renderer/components/MainPage.tsx
  src/renderer/components/SettingsPage.tsx
Labels: 2: Dev Review, release-note-none, Contributor

#2808 Upgrade to Electron v26.1.0
  package-lock.json
  package.json
  src/main/authManager.ts
  src/main/certificateManager.ts
  src/main/views/viewManager.ts
  src/main/views/webContentEvents.ts
  src/main/windows/callsWidgetWindow.ts
Labels: 2: Dev Review, release-note, Contributor

#2800 [MM-53847] Expose isDev API to allow webapp to check if the app is in dev mode
  src/common/communication.ts
  src/main/app/initialize.ts
  src/main/app/utils.test.js
  src/main/app/utils.ts
  src/main/preload/mattermost.js
  src/main/views/viewManager.ts
Labels: 4: Reviews Complete, release-note-none
