Repository mattermost/desktop, pull requests merged in 2023-03, with the labels that each got.

#2572 Fix wording in error message
  src/main/views/MattermostView.ts
Labels: 2: Dev Review, release-note, Contributor

#2571 [MM-50995] Harden Calls events handling
  src/main/preload/callsWidget.js
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
  src/types/calls.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2565 [MM-50527] Explicitly allow the Mattermost views access to write to the clipboard using Copy Link
  src/main/app/initialize.ts
  src/main/windows/callsWidgetWindow.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2574 Translations update from Mattermost Weblate
  i18n/ar.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2577 Translations update from Mattermost Weblate
  i18n/bg.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2578 Translations update from Mattermost Weblate
  i18n/bg.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2573 [MM-50973] Harden Calls windows URL navigation checks
  src/common/utils/url.test.js
  src/common/utils/url.ts
  src/main/views/viewManager.ts
  src/main/views/webContentEvents.ts
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2579 [MM-50537] Upgrade to Electron v23.1.2
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2516 feat(ci): CircleCI migration to Github Actions
  .circleci/config.yml
  .github/actions/patch-nightly-version/action.yaml
  .github/actions/patch-nightly-version/patch-version.go
  .github/actions/test/action.yaml
  .github/workflows/build-for-pr.yml
  .github/workflows/ci.yaml
  .github/workflows/nightly-browser-view.yml
  .github/workflows/nightly-rainforest.yml
  .github/workflows/release.yaml
  package-lock.json
  package.json
  src/main/app/initialize.test.js
  src/main/autoUpdater.test.js
  src/main/views/MattermostView.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/windowManager.test.js
Labels: 2: Dev Review, release-note

#2580 [MM-50948] Prevent popup windows from redirecting to internal URLs outside of the plugin/managed resource URLs
  src/main/views/webContentEvents.ts
Labels: 2: Dev Review, CherryPick/Approved, release-note

#2582 Translations update from Mattermost Weblate
  i18n/be.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2584 Translations update from Mattermost Weblate
  i18n/ar.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2586 Translations update from Mattermost Weblate
  i18n/ar.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2581 [GH-2534] Refocus the popup window if already exists
  src/main/views/webContentEvents.ts
Labels: 4: Reviews Complete, release-note

#2589 Update release script
  scripts/release.sh
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2590 fix nightly builds
  .github/workflows/nightly-browser-view.yml
  .github/workflows/nightly-rainforest.yml
Labels: release-note

#2591 [MM-51222] Fix race condition on switching calls
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, release-note

#2592 Nightly builds fix
  .github/actions/patch-nightly-version/action.yaml
  .github/workflows/nightly-browser-view.yml
  .github/workflows/nightly-rainforest.yml
Labels: release-note

#2570 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2594 Add missing yq for windows builds on nightly
  .github/workflows/nightly-browser-view.yml
  .github/workflows/nightly-rainforest.yml
Labels: release-note

#2595 Allow MAS build to be repeated more easily
  scripts/patch_mas_version.sh
Labels: release-note-none

#2600 Cherry-pick GitHub Actions to 5.3
  .circleci/config.yml
  .github/actions/patch-nightly-version/action.yaml
  .github/actions/patch-nightly-version/patch-version.go
  .github/actions/test/action.yaml
  .github/workflows/build-for-pr.yml
  .github/workflows/ci.yaml
  .github/workflows/nightly-browser-view.yml
  .github/workflows/nightly-rainforest.yml
  .github/workflows/release.yaml
  package-lock.json
  package.json
  scripts/patch_mas_version.sh
  src/main/app/initialize.test.js
  src/main/autoUpdater.test.js
  src/main/views/MattermostView.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/windowManager.test.js
Labels: 4: Reviews Complete, release-note-none

#2603 Run pipeline on tags only
  .github/workflows/release.yaml
Labels: release-note

#2605 Bump version to v5.4.0
  package-lock.json
  package.json
Labels: release-note-none

#2607 Add missing checkout/patch . Fixed folder name
  .github/workflows/nightly-rainforest.yml
Labels: release-note, kind/bug

#2610 Disable creation of blank issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: 4: Reviews Complete, release-note-none

#2608 Replace release creation with gh CLI
  .github/workflows/nightly-browser-view.yml
  .github/workflows/nightly-rainforest.yml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
Labels: 4: Reviews Complete, CherryPick/Approved, release-note, kind/bug

#2612 fix secret inheritance and naming convention for consistency
  .github/workflows/nightly-builds.yaml
Labels: release-note, kind/bug

#2613 Add MM_WIN_INSTALLERS to release pipeline
  .github/workflows/release.yaml
Labels: CherryPick/Approved, release-note-none

#2616 [MM-51406] Check for other server URLs when trying to navigate
  src/main/views/webContentEvents.ts
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#2619 Automated cherry pick of #2616
  src/main/views/webContentEvents.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2615 fix: use XDG_DOWNLOAD_DIR as default download dir
  src/common/config/defaultPreferences.ts
Labels: 4: Reviews Complete, release-note, Contributor

#2617 [MM-51406] Update node-abi, fix some server modal bugs
  package-lock.json
  package.json
  src/renderer/components/ConfigureServer.tsx
  src/renderer/components/NewTeamModal.tsx
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#2620 Automated cherry pick of #2617
  package-lock.json
  package.json
  src/renderer/components/ConfigureServer.tsx
  src/renderer/components/NewTeamModal.tsx
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2618 Separate artifact names since we merged the nightly builds for consistency
  .github/workflows/nightly-main.yml
  .github/workflows/nightly-rainforest.yml
Labels: 4: Reviews Complete, release-note

#2623 HOTFIX nightly workflow name
  .github/workflows/nightly-builds.yaml
Labels: release-note

#2625 Automated cherry pick of #2624
  scripts/release.sh
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2627 Translations update from Mattermost Weblate
  i18n/tr.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2621 Fix the issue where we sometimes need to wait for GPO teams properly
  src/common/config/index.ts
  src/main/app/config.ts
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/app/intercom.ts
Labels: 4: Reviews Complete, release-note

#2631 Translations update from Mattermost Weblate
  i18n/hr.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2632 Automated cherry pick of #2630
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/windowManager.ts
  src/types/calls.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2633 [MM-51527] Cherrypick to `release-5.3`
  src/common/utils/url.test.js
  src/common/utils/url.ts
Labels: release-note-none

#2634 Translations update from Mattermost Weblate
  i18n/lt.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2641 MM-51535 - Calls: Fix unrestricted redirect from calls widget (#2635)
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
Labels: 4: Reviews Complete, release-note

#2642 Add a checkbox asking users to reproduce on the latest version of the Desktop App
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: 4: Reviews Complete, release-note-none

#2647 MM-51850 - Calls: Fix for crash after closing popout
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#2649 cherry-pick: MM-51850 - Calls: Fix for crash after closing popout (#2647)
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
Labels: 4: Reviews Complete, release-note
