Repository mattermost/desktop, pull requests merged in 2023-04, with the labels that each got.

#2660 For MAS pre-release, only release to MAS (and not actual production)
  .github/workflows/release-mas-only.yaml
  .github/workflows/release.yaml
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2659 Remove unneeded entitlements for MAS
  entitlements.mas.plist
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2662 Fixed a typo in MAS workflow
  .github/workflows/release-mas-only.yaml
Labels: release-note-none

#2663 Fix final release pipeline
  .github/workflows/release-mas-only.yaml
  .github/workflows/release-mas.yaml
  .github/workflows/release.yaml
Labels: release-note-none

#2650 [MM-51871] Migrate mainWindow and settingsWindow to singletons
  src/main/CriticalErrorHandler.test.js
  src/main/CriticalErrorHandler.ts
  src/main/allowProtocolDialog.test.js
  src/main/allowProtocolDialog.ts
  src/main/app/app.test.js
  src/main/app/app.ts
  src/main/app/config.ts
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/app/intercom.test.js
  src/main/app/intercom.ts
  src/main/app/utils.test.js
  src/main/app/utils.ts
  src/main/authManager.test.js
  src/main/authManager.ts
  src/main/badge.test.js
  src/main/badge.ts
  src/main/certificateManager.test.js
  src/main/certificateManager.ts
  src/main/diagnostics/index.test.js
  src/main/diagnostics/steps/step5.browserWindows.ts
  src/main/downloadsManager.test.js
  src/main/menus/app.test.js
  src/main/menus/app.ts
  src/main/menus/tray.test.js
  src/main/menus/tray.ts
  src/main/notifications/index.test.js
  src/main/notifications/index.ts
  src/main/tray/tray.test.js
  src/main/tray/tray.ts
  src/main/utils.ts
  src/main/views/MattermostView.test.js
  src/main/views/MattermostView.ts
  src/main/views/downloadsDropdownMenuView.test.js
  src/main/views/downloadsDropdownMenuView.ts
  src/main/views/downloadsDropdownView.test.js
  src/main/views/downloadsDropdownView.ts
  src/main/views/teamDropdownView.test.js
  src/main/views/teamDropdownView.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
  src/main/windows/settingsWindow.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, Docs/Done, release-note-none

#2655 [MM-51874] Migrate loading screen to singleton
  src/main/app/config.test.js
  src/main/app/config.ts
  src/main/views/loadingScreen.test.js
  src/main/views/loadingScreen.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/mainWindow.test.js
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, Docs/Done, release-note-none

#2652 [MM-51873] Create central logging module for adding prefixes to differentiate logs between modules
  src/common/Validator.ts
  src/common/config/RegistryConfig.ts
  src/common/config/index.ts
  src/common/log.test.js
  src/common/log.ts
  src/jest/jestSetup.js
  src/main/AutoLauncher.ts
  src/main/CriticalErrorHandler.ts
  src/main/UserActivityMonitor.ts
  src/main/allowProtocolDialog.ts
  src/main/app/app.ts
  src/main/app/config.test.js
  src/main/app/config.ts
  src/main/app/initialize.ts
  src/main/app/intercom.ts
  src/main/app/utils.ts
  src/main/appState.ts
  src/main/authManager.ts
  src/main/autoUpdater.ts
  src/main/badge.ts
  src/main/certificateManager.ts
  src/main/certificateStore.ts
  src/main/downloadsManager.ts
  src/main/i18nManager.ts
  src/main/notifications/dnd-linux.ts
  src/main/notifications/index.ts
  src/main/server/serverAPI.ts
  src/main/server/serverInfo.ts
  src/main/trustedOrigins.ts
  src/main/views/MattermostView.ts
  src/main/views/downloadsDropdownMenuView.ts
  src/main/views/downloadsDropdownView.ts
  src/main/views/loadingScreen.ts
  src/main/views/modalManager.ts
  src/main/views/modalView.ts
  src/main/views/teamDropdownView.ts
  src/main/views/viewManager.ts
  src/main/views/webContentEvents.ts
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/mainWindow.ts
  src/main/windows/settingsWindow.ts
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, Docs/Done, release-note-none

#2654 [MM-50485] Implement ServerManager, introduce id concept for identifying servers/views
  package-lock.json
  package.json
  src/common/communication.ts
  src/common/config/RegistryConfig.ts
  src/common/config/index.ts
  src/common/log.ts
  src/common/servers/MattermostServer.ts
  src/common/servers/serverManager.test.js
  src/common/servers/serverManager.ts
  src/common/tabs/BaseTabView.ts
  src/common/tabs/TabView.ts
  src/jest/jestSetup.js
  src/main/app/utils.ts
  src/main/views/MattermostView.test.js
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/renderer/components/TabBar.tsx
  src/renderer/dropdown.tsx
  src/types/config.ts
Labels: 4: Reviews Complete, Docs/Needed, release-note-none

#2668 [MM-51964] Clean up MattermostView, remove tuple in preparation for id
  package-lock.json
  package.json
  src/common/tabs/BaseTabView.ts
  src/common/tabs/TabView.ts
  src/main/views/MattermostView.test.js
  src/main/views/MattermostView.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/views/webContentEvents.ts
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
  src/types/external/tuple-record-polyfill.d.ts
Labels: 4: Reviews Complete, Docs/Needed, release-note-none

#2667 [MM-51961] Migrate calls widget to singleton
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEvents.ts
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: 2: Dev Review, Docs/Needed, release-note-none

#2674 Translations update from Mattermost Weblate
  i18n/pt-BR.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2675 Update Licences at Notice.txt to reflect dependency changes.
  NOTICE.txt
Labels: 4: Reviews Complete, do-not-merge/release-note-label-needed, kind/chore

#2676 Clean up appState module, move to common, simplify events
  src/common/appState.ts
  src/common/communication.ts
  src/main/app/initialize.test.js
  src/main/appState.ts
  src/main/badge.test.js
  src/main/badge.ts
  src/main/tray/tray.ts
  src/main/views/MattermostView.test.js
  src/main/views/MattermostView.ts
  src/main/views/teamDropdownView.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/windows/mainWindow.ts
Labels: 4: Reviews Complete, release-note-none

#2677 Migrate teamDropdownView to singleton
  src/common/communication.ts
  src/main/app/initialize.ts
  src/main/app/intercom.ts
  src/main/views/teamDropdownView.test.js
  src/main/views/teamDropdownView.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, release-note-none

#2680 Migrate downloads dropdown menus to singletons
  src/main/views/downloadsDropdownMenuView.test.js
  src/main/views/downloadsDropdownMenuView.ts
  src/main/views/downloadsDropdownView.test.js
  src/main/views/downloadsDropdownView.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: 2: Dev Review, release-note-none

#2687 Fixed bad mention counts in the dropdown menu
  src/main/views/teamDropdownView.ts
Labels: 4: Reviews Complete, release-note-none

#2686 Fixed Snap issue with resizing on Windows 11
  src/main/preload/desktopAPI.js
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
Labels: 4: Reviews Complete, release-note-none
