Repository mattermost/desktop, pull requests merged in 2023-07, with the labels that each got.

#2779 Re-add React Developer Tools to nightly builds
  webpack.config.base.js
Labels: release-note-none

#2780 Have all nightly branches include React Developer Tools
  webpack.config.base.js
Labels: release-note-none

#2781 Translations update from Mattermost Weblate
  i18n/zh_Hant.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2784 Translations update from Mattermost Weblate
  i18n/vi.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2783 Fix React Developer Tools for some users
  package-lock.json
  package.json
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
Labels: 2: Dev Review, release-note-none

#2788 Translations update from Mattermost Weblate
  i18n/zh_Hans.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2792 Translations update from Mattermost Weblate
  i18n/zh_Hans.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2793 [GH-2694] Upgrade to Electron v24.6.3
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note

#2787 [MM-53490] Reduce min window width to 600px
  e2e/specs/menu_bar/full_screen.test.js
  src/common/utils/constants.ts
Labels: 4: Reviews Complete, release-note

#2794 Translations update from Mattermost Weblate
  i18n/vi.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2801 [MM-53841] Remove upgrade notification if auto updates were switched off
  src/main/downloadsManager.test.js
  src/main/downloadsManager.ts
Labels: 4: Reviews Complete, release-note
