Repository mattermost/desktop, pull requests merged in 2023-02, with the labels that each got.

#2531 [MM-50220] Fix issue with rpm build conflicting with other electron applications
  electron-builder.json
Labels: 4: Reviews Complete, release-note

#2076 [MM-43656] Flush cookies to disk on finishing custom login
  src/main/app/utils.ts
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEvents.ts
Labels: 4: Reviews Complete, release-note

#2535 [MM-50042] Detect Boards using the BuildBoards flag in the client config
  src/main/server/serverAPI.test.js
  src/main/server/serverAPI.ts
  src/main/server/serverInfo.ts
  src/types/server.ts
Labels: 4: Reviews Complete, release-note

#2538 Update feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: release-note-none

#2539 [MM-49739] Set parent window on calls expanded popout view
  src/common/communication.ts
  src/main/preload/callsWidget.js
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
Labels: 4: Reviews Complete, release-note-none

#2546 [MM-50250] Revised Issue Templates with Issue Forms
  .github/ISSUE_TEMPLATE/beta_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/crash_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/troubleshooting-question.md
  .github/ISSUE_TEMPLATE/upgrade-dependencies.md
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: 4: Reviews Complete, release-note-none

#2544 Remove use of `getView()` and replace with `getViewByURL()` where necessary.
  src/common/tabs/TabView.test.js
  src/common/tabs/TabView.ts
  src/common/utils/url.test.js
  src/common/utils/url.ts
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/authManager.test.js
  src/main/authManager.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEvents.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, release-note

#2548 [MM-50410] Allow any unhandled target=_blank links to open in the browser
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEvents.ts
Labels: 2: Dev Review, release-note-none

#2550 [MM-50411] Fix media permissions failure on Calls window
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
Labels: 4: Reviews Complete, release-note-none

#2552 [MM-50433] Upgrade to Electron v23.0.0
  package-lock.json
  package.json
Labels: 4: Reviews Complete, Docs/Needed, release-note

#2520 [MM-49172] Stop cookies from being appended if they don't match the host of the server
  src/main/views/MattermostView.ts
Labels: 3: Security Review, release-note-none

#2553 Merge and migrate locally-trusted preload scripts to `contextBridge` API
  src/common/communication.ts
  src/main/app/intercom.ts
  src/main/authManager.ts
  src/main/certificateManager.ts
  src/main/preload/desktopAPI.js
  src/main/preload/downloadsDropdown.js
  src/main/preload/downloadsDropdownMenu.js
  src/main/preload/dropdown.js
  src/main/preload/loadingScreenPreload.js
  src/main/preload/modalPreload.js
  src/main/preload/urlView.js
  src/main/views/downloadsDropdownMenuView.ts
  src/main/views/downloadsDropdownView.ts
  src/main/views/teamDropdownView.ts
  src/main/views/viewManager.ts
  src/main/windows/mainWindow.ts
  src/main/windows/settingsWindow.ts
  src/main/windows/windowManager.ts
  src/renderer/components/ConfigureServer.tsx
  src/renderer/components/DownloadsDropdown/DownloadsDropdownItemFile.tsx
  src/renderer/components/DownloadsDropdown/ThreeDotButton.tsx
  src/renderer/components/DownloadsDropdown/Update/UpdateAvailable.tsx
  src/renderer/components/DownloadsDropdown/Update/UpdateDownloaded.tsx
  src/renderer/components/NewTeamModal.tsx
  src/renderer/components/urlDescription.tsx
  src/renderer/downloadsDropdown.tsx
  src/renderer/downloadsDropdownMenu.tsx
  src/renderer/dropdown.tsx
  src/renderer/intl_provider.tsx
  src/renderer/modals/certificate/certificate.tsx
  src/renderer/modals/certificate/certificateModal.tsx
  src/renderer/modals/darkMode.ts
  src/renderer/modals/editServer/editServer.tsx
  src/renderer/modals/loadingScreen/index.tsx
  src/renderer/modals/login/login.tsx
  src/renderer/modals/login/loginModal.tsx
  src/renderer/modals/newServer/newServer.tsx
  src/renderer/modals/permission/permission.tsx
  src/renderer/modals/permission/permissionModal.tsx
  src/renderer/modals/removeServer/removeServer.tsx
  src/renderer/modals/welcomeScreen/welcomeScreen.tsx
  src/types/modals.ts
  src/types/window.ts
  webpack.config.main.js
Labels: 4: Reviews Complete, release-note-none

#2557 [MM-49089] Propagate calls client errors
  src/main/preload/callsWidget.js
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
  src/types/calls.ts
Labels: CherryPick/Approved, release-note-none

#2558 MM-49079 - Calls: process link clicks from Calls popout
  src/common/communication.ts
  src/main/preload/callsWidget.js
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
  src/types/calls.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#2560 Automated cherry pick of #2558
  src/common/communication.ts
  src/main/preload/callsWidget.js
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
  src/types/calls.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2556 [MM-46980] Improve screensharing permissions flow
  src/main/preload/callsWidget.js
  src/main/preload/mattermost.js
  src/main/utils.ts
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
  src/types/calls.ts
Labels: CherryPick/Approved, release-note-none

#2561 Automated cherry pick of #2556
  src/main/preload/callsWidget.js
  src/main/preload/mattermost.js
  src/main/utils.ts
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/windowManager.test.js
  src/main/windows/windowManager.ts
  src/types/calls.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#2567 [MM-50712] Fix local prototype pollution flaw
  src/main/diagnostics/steps/internal/loggerHooks.test.js
  src/main/diagnostics/steps/internal/obfuscators.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2566 [MM-50569] Fix insecure win32 path regex
  src/common/constants.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#2569 Translations update from Mattermost Weblate
  i18n/da.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod
