Repository mattermost/desktop, pull requests merged in 2023-10, with the labels that each got.

#2864 integrating WIP languages
  i18n/am.json
  i18n/be.json
  i18n/bn.json
  i18n/br.json
  i18n/ca.json
  i18n/cs.json
  i18n/da.json
  i18n/el.json
  i18n/et.json
  i18n/eu.json
  i18n/fi.json
  i18n/fil.json
  i18n/fy.json
  i18n/gl.json
  i18n/gu.json
  i18n/he.json
  i18n/hi.json
  i18n/hr.json
  i18n/id.json
  i18n/is.json
  i18n/ka.json
  i18n/kk.json
  i18n/kk_Latn.json
  i18n/km.json
  i18n/la.json
  i18n/lo.json
  i18n/lt.json
  i18n/lv.json
  i18n/mk.json
  i18n/ml.json
  i18n/mn.json
  i18n/nb_NO.json
  i18n/ne.json
  i18n/pr.json
  i18n/pt.json
  i18n/si.json
  i18n/sl.json
  i18n/sq.json
  i18n/sr.json
  i18n/th.json
  i18n/zh_Hans.json
  i18n/zh_Hant.json
Labels: Hacktoberfest, 4: Reviews Complete, release-note-none, Contributor

#2868 [MM-54584] Fixed an issue where clicking on a link to an unregistered protocol on macOS would cause the app to crash
  src/main/allowProtocolDialog.test.js
  src/main/allowProtocolDialog.ts
Labels: 2: Dev Review, release-note

#2867 [MM-54701] Fix development deep linking for login for Windows/Linux
  package.json
  scripts/patch_macos_notification_state.js
  scripts/postinstall.js
  src/main/app/initialize.ts
Labels: 4: Reviews Complete, release-note-none

#2865 Fix notifications not working
  package.json
  src/main/app/intercom.ts
  src/main/autoUpdater.test.ts
  src/main/autoUpdater.ts
  src/main/downloadsManager.ts
  src/main/notifications/Download.ts
  src/main/notifications/Mention.ts
  src/main/notifications/index.test.ts
  src/main/notifications/index.ts
Labels: 4: Reviews Complete, release-note

#2883 Include more obvious prompt to reproduce issues in the Web App first
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: release-note-none

#2872 adding Vietnamese language as beta
  i18n/i18n.ts
Labels: Hacktoberfest, 4: Reviews Complete, release-note, Contributor

#2796 feat(e2e): add a job to run e2e on linux os
  .github/workflows/e2e-functional.yml
  e2e/modules/environment.js
  e2e/save_report.js
  e2e/specs/deep_linking/deeplink.test.js
  e2e/specs/mattermost/copy_link.test.js
  e2e/specs/menu_bar/edit_menu.test.js
  e2e/specs/relative_url/relative_url.test.js
Labels: release-note-none

#2886 [MM-54979] Stop auto opening Boards/Playbooks tabs, close existing open tabs once for users that might have them open
  src/common/config/migrationPreferences.test.js
  src/common/config/migrationPreferences.ts
  src/common/servers/serverManager.test.js
  src/common/servers/serverManager.ts
  src/types/config.ts
Labels: 4: Reviews Complete, release-note

#2894 [MM-55132] Upgrade to Electron v27.0.2
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note

#2896 Add argument passing to the desktop file script
  src/assets/linux/create_desktop_file.sh
Labels: 2: Dev Review, release-note-none

#2892 adding Hebrew as a new beta language
  i18n/i18n.ts
Labels: Hacktoberfest, 2: Dev Review, release-note, Contributor
