Repository mattermost/desktop, pull requests merged in 2024-06, with the labels that each got.

#3049 Translations update from Mattermost Weblate
  i18n/ru.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#3051 [MM-46634] Force window to be focused after navigation on notification click
  src/main/notifications/index.test.ts
  src/main/notifications/index.ts
Labels: 2: Dev Review, release-note, Build Apps for PR

#3053 [MM-58455] Add error handling when FocusStatus is not authorized on macOS
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/notifications/index.test.ts
  src/main/notifications/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#3054 Automated cherry pick of #3053
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/notifications/index.test.ts
  src/main/notifications/index.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3056 Automated cherry pick of #3051
  src/main/notifications/index.test.ts
  src/main/notifications/index.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3057 Automated cherry pick of #3045
  src/common/Validator.ts
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3058 Automated cherry pick of #3040
  src/main/notifications/index.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3060 [MM-58693] Fix some issues with Windows notifications
  src/main/notifications/dnd-windows.test.js
  src/main/notifications/dnd-windows.ts
  src/main/notifications/index.ts
Labels: 2: Dev Review, CherryPick/Approved, release-note

#3062 Automated cherry pick of #3060
  src/main/notifications/dnd-windows.test.js
  src/main/notifications/dnd-windows.ts
  src/main/notifications/index.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3063 [MM-58357] Disable window scaling for OSes that aren't Windows
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#3064 Automated cherry pick of #3063
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3065 Assorted Desktop App repo fixes
  .eslintignore
  .eslintrc.json
  .github/actions/test/action.yaml
  package-lock.json
  scripts/beforepack.js
  scripts/cp_msi_app_update.js
Labels: 2: Dev Review, release-note-none

#3068 Move all E2E dependencies into its own folder, run from there
  .eslintignore
  .eslintrc.json
  .github/workflows/e2e-functional-template.yml
  .github/workflows/e2e-performance.yml
  e2e/babel.config.js
  e2e/modules/environment.js
  e2e/package-lock.json
  e2e/package.json
  e2e/specs/focus.test.js
  e2e/specs/mattermost/copy_link.test.js
  e2e/specs/settings.test.js
  e2e/specs/settings/keyboard_shortcuts.test.js
  e2e/specs/startup/config.test.js
  e2e/utils/constants.js
  e2e/webpack.config.js
  e2e/webpack.config.performance.js
  package-lock.json
  package.json
  webpack.config.base.js
  webpack.config.renderer.js
Labels: 2: Dev Review, release-note-none

#3059 [MM-54863] Add permissions manager UI in Edit Server modal, improve permission checks to be less missable
  i18n/en.json
  package-lock.json
  package.json
  src/app/serverViewState.test.js
  src/app/serverViewState.ts
  src/common/communication.ts
  src/main/notifications/index.ts
  src/main/permissionsManager.test.js
  src/main/permissionsManager.ts
  src/main/preload/internalAPI.js
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/renderer/components/NewServerModal.tsx
  src/renderer/components/Toggle.tsx
  src/renderer/css/_css_variables.scss
  src/renderer/css/components/Toggle.scss
  src/renderer/css/lazy/modals-dark.lazy.css
  src/renderer/modals/editServer/editServer.tsx
  src/types/permissions.ts
  src/types/window.ts
Labels: 4: Reviews Complete, QA Review Done, release-note, Build Apps for PR

#3072 [MM-58780] Don't account for scaleFactor on Windows when resizing if the matching screen is the primary monitor
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
Labels: 4: Reviews Complete, release-note

#3073 [MM-57964] Implement `openThread` and `openStopRecordingModal`
  api-types/index.ts
  api-types/lib/index.d.ts
  src/common/communication.ts
  src/main/preload/externalAPI.ts
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/types/externalAPI.ts
Labels: 4: Reviews Complete, release-note-none

#3075 Bump api-types and publish
  api-types/package-lock.json
  api-types/package.json
Labels: release-note-none
