Repository mattermost/desktop, pull requests merged in 2024-05, with the labels that each got.

#3024 [MM-58089] Disallow redirects to untrusted URLs without a permission prompt
  i18n/en.json
  src/main/notifications/index.ts
  src/main/permissionsManager.test.js
  src/main/permissionsManager.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#3030 Automated cherry pick of #3024
  i18n/en.json
  src/main/notifications/index.ts
  src/main/permissionsManager.test.js
  src/main/permissionsManager.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3027 Fix script to make directories recursively
  scripts/beforepack.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none, Build Apps for PR

#3031 Automated cherry pick of #3027
  scripts/beforepack.js
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3033 Automated cherry pick of #3032
  src/main/permissionsManager.test.js
  src/main/permissionsManager.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3028 [MM-55341][MM-56894] Use `electron-builder` to create the MSI installer, drop support for 32-bit Windows and the NSIS installer
  .github/workflows/build-for-pr.yml
  .github/workflows/ci.yaml
  .github/workflows/e2e-functional-template.yml
  .github/workflows/nightly-main.yml
  .github/workflows/nightly-rainforest.yml
  .github/workflows/release.yaml
  electron-builder.json
  package.json
  patches/app-builder-lib+24.13.3.patch
  resources/windows/license.rtf
  resources/windows/msi_create_folder.ico
  resources/windows/msi_dialog_banner.png
  resources/windows/msi_dialog_banner_small.png
  resources/windows/msi_i18n/en_US.wxl
  resources/windows/msi_modify.ico
  resources/windows/msi_question.ico
  resources/windows/msi_remove.ico
  resources/windows/msi_repair.ico
  resources/windows/msi_up.ico
  resources/windows/msi_warning.ico
  scripts/Makefile.ps1
  scripts/cp_artifacts.sh
  scripts/cp_msi_app_update.js
  scripts/generate_release_markdown.sh
  scripts/installer.nsh
  scripts/msi_installer.wxs
  scripts/msi_installer_files_replace_id.xslt
  scripts/msi_installer_files_set_win64.xslt
  scripts/wix311.sha
Labels: 4: Reviews Complete, release-note, Build Apps for PR

#3037 [MM-58286] Fix cp_artifacts to avoid weird naming changes
  scripts/cp_artifacts.sh
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#3040 Improve notification logging
  src/main/notifications/index.ts
Labels: 4: Reviews Complete, release-note-none

#3043 Fixes for the MSI installer
  electron-builder.json
  patches/app-builder-lib+24.13.3.patch
Labels: 4: Reviews Complete, release-note

#3045 [MM-58357] Account for monitor scale factor when creating the window from saved bounds
  src/common/Validator.ts
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
Labels: 4: Reviews Complete, release-note

#3046 Support new notice-file-generator version
  .config/notice-file/config.yaml
Labels: release-note-none
