Repository mattermost/desktop, pull requests merged in 2024-12, with the labels that each got.

#3236 Automated cherry pick of #3232
  package-lock.json
  package.json
  patches/electron+33.2.0.patch
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3231 [MM-61821] Automatically allow permission checks for supported permission types through for GPO configured servers
  src/main/permissionsManager.test.js
  src/main/permissionsManager.ts
Labels: 4: Reviews Complete, release-note

#3237 [MM-61994] Fix UpgradeCode to use the old one, allow MSI to uninstall both
  electron-builder.json
  patches/app-builder-lib+24.13.3.patch
Labels: 4: Reviews Complete, release-note

#3238 [MM-60416] Check for the presence of the EXE uninstaller before trying to run it
  patches/app-builder-lib+24.13.3.patch
Labels: 4: Reviews Complete, release-note

#3242 Automated cherry pick of #3157
  src/main/utils.ts
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3243 Automated cherry pick of #3157
  src/main/utils.ts
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3244 Cherry-pick of #3237, #3238, #3239 to `release-5.10`
  electron-builder.json
  patches/app-builder-lib+24.13.3.patch
Labels: release-note-none

#3246 Automated cherry pick of #3226
  .github/workflows/build-for-pr.yml
  .github/workflows/ci.yaml
  .github/workflows/nightly-builds.yaml
  .github/workflows/nightly-main.yml
  .github/workflows/nightly-rainforest.yml
  .github/workflows/release-mas.yaml
  .github/workflows/release.yaml
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3247 Cherry-pick of #3237, #3238, #3239 to `release-5.9`
  electron-builder.json
  patches/app-builder-lib+24.13.3.patch
Labels: release-note-none

#3249 [MM-62196] Add support for downgrades using the MSI
  patches/app-builder-lib+24.13.3.patch
Labels: CherryPick/Approved, release-note, QA Deferred

#3250 Automated cherry pick of #3249
  patches/app-builder-lib+24.13.3.patch
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3251 Automated cherry pick of #3249
  patches/app-builder-lib+24.13.3.patch
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3233 [MM-61744] Import GenericModal, convert Remove Server to new design
  i18n/en.json
  src/app/serverViewState.ts
  src/renderer/components/DestructiveConfirmModal.tsx
  src/renderer/components/GenericModal/_buttons.scss
  src/renderer/components/GenericModal/_css_variables.scss
  src/renderer/components/GenericModal/_modal.scss
  src/renderer/components/GenericModal/_sys_css_variables.scss
  src/renderer/components/GenericModal/_typography.scss
  src/renderer/components/GenericModal/generic_modal.scss
  src/renderer/components/GenericModal/generic_modal.tsx
  src/renderer/components/GenericModal/utils/_functions.scss
  src/renderer/components/GenericModal/utils/_mixins.scss
  src/renderer/components/GenericModal/utils/_variables.scss
  src/renderer/components/RemoveServerModal.tsx
  src/renderer/css/modals-dark.scss
  src/renderer/modals/removeServer/removeServer.tsx
Labels: 4: Reviews Complete, release-note, Build Apps for PR

#3235 [MM-62001] Calls: switch tab on actions requiring focus
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
Labels: 4: Reviews Complete, release-note

#3254 Translations update from Mattermost Weblate
  i18n/de.json
  i18n/tr.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#3255 Revert "Translations update from Mattermost Weblate"
  i18n/de.json
  i18n/tr.json
Labels: do-not-merge/release-note-label-needed

#3256 Revert "Revert "Translations update from Mattermost Weblate""
  i18n/de.json
  i18n/tr.json
Labels: do-not-merge/release-note-label-needed

#3257 Bump SBOM version so the file output is sbom-desktop-vX.Y.Z.json
  .github/workflows/snyk-sbom.yml
Labels: release-note-none

#3260 Automated cherry pick of #3257
  .github/workflows/snyk-sbom.yml
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3259 Automated cherry pick of #3257
  .github/workflows/snyk-sbom.yml
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3253 [MM-62205] Dynamically toggle widget window visibility when popout opens/closes
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
Labels: 4: Reviews Complete, release-note, Build Apps for PR
