Repository mattermost/desktop, pull requests merged in 2024-09, with the labels that each got.

#3144 [MM-60308] Add a set of "Developer Mode" settings that allow the user to turn off systems or force the app to behave a certain way
  i18n/en.json
  src/common/communication.ts
  src/main/UserActivityMonitor.ts
  src/main/app/initialize.ts
  src/main/constants.ts
  src/main/developerMode.test.js
  src/main/developerMode.ts
  src/main/menus/app.ts
  src/main/notifications/index.test.ts
  src/main/notifications/index.ts
  src/main/preload/externalAPI.ts
  src/main/preload/internalAPI.js
  src/main/utils.ts
  src/main/views/MattermostBrowserView.test.js
  src/main/views/MattermostBrowserView.ts
  src/main/views/viewManager.ts
  src/renderer/components/DeveloperModeIndicator.tsx
  src/renderer/components/MainPage.tsx
  src/renderer/css/components/DeveloperModeIndicator.scss
  src/types/settings.ts
  src/types/window.ts
Labels: 4: Reviews Complete, release-note, Build Apps for PR

#3135 [MM-60227] Allow plugins to ask for desktop sources for screen sharing
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
Labels: 4: Reviews Complete, release-note

#3136 [MM-60226] Allow plugins to open blank popup windows
  src/main/views/pluginsPopUps.test.js
  src/main/views/pluginsPopUps.ts
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEvents.ts
  src/main/views/webContentEventsCommon.ts
Labels: 4: Reviews Complete, release-note

#3147 [MM-60232] Fix a crash in Linux when trying to create a thumbnail from an image
  src/main/downloadsManager.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#3149 Automated cherry pick of #3147
  src/main/downloadsManager.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3152 [MM-60201] Fixed a potential crash on removing server
  src/app/serverViewState.ts
Labels: 4: Reviews Complete, release-note

#3154 [MM-60605] Cherrypick of (#3148) to `release-5.9`
  src/renderer/components/MainPage.tsx
  src/types/window.ts
Labels: AutoMerge, release-note-none

#3151 Disable full screen mode on Linux
  src/main/menus/app.ts
  src/main/windows/mainWindow.ts
  src/renderer/components/SettingsPage.tsx
Labels: 4: Reviews Complete, release-note
