Repository mattermost/desktop, pull requests merged in 2024-10, with the labels that each got.

#3156 SBOM generation on release
  .github/workflows/snyk-sbom.yml
Labels: release-note-none

#3160 Automated cherry pick of #3156
  .github/workflows/snyk-sbom.yml
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3166 [MM-61040] Handle custom protocols in plugins popouts
  src/main/views/pluginsPopUps.test.js
  src/main/views/pluginsPopUps.ts
  src/main/views/webContentEvents.ts
  src/main/views/webContentEventsCommon.ts
Labels: 4: Reviews Complete, release-note-none

#3167 Translations update from Mattermost Weblate
  i18n/zh-TW.json
Labels: Hacktoberfest, do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#3161 MM-60782 - use default download directory on windows
  src/app/serverViewState.test.js
  src/common/config/defaultPreferences.ts
  src/common/config/index.test.js
  src/common/config/upgradePreferences.test.js
  src/main/app/config.test.js
  src/main/downloadsManager.test.js
  src/main/tray/tray.test.js
  src/main/views/MattermostBrowserView.test.js
  src/main/views/downloadsDropdownMenuView.test.js
  src/main/views/downloadsDropdownView.test.js
  src/main/views/serverDropdownView.test.js
  src/main/views/viewManager.test.js
Labels: 4: Reviews Complete, release-note, Build Apps for PR

#3170 Bump to version 5.11
  package-lock.json
  package.json
Labels: release-note-none

#3165 [MM-60086][MM-60610] Implement performanceMonitor, collect CPU/memory usage data and send via API
  api-types/index.ts
  api-types/lib/index.d.ts
  api-types/package-lock.json
  api-types/package.json
  i18n/en.json
  src/common/Validator.ts
  src/common/communication.ts
  src/common/config/defaultPreferences.ts
  src/common/config/index.ts
  src/common/config/migrationPreferences.ts
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/performanceMonitor.test.js
  src/main/performanceMonitor.ts
  src/main/preload/externalAPI.ts
  src/main/preload/internalAPI.js
  src/main/tray/tray.test.js
  src/main/views/MattermostBrowserView.test.js
  src/main/views/MattermostBrowserView.ts
  src/main/views/downloadsDropdownMenuView.test.js
  src/main/views/downloadsDropdownMenuView.ts
  src/main/views/downloadsDropdownView.test.js
  src/main/views/downloadsDropdownView.ts
  src/main/views/loadingScreen.test.js
  src/main/views/loadingScreen.ts
  src/main/views/modalView.test.js
  src/main/views/modalView.ts
  src/main/views/serverDropdownView.test.js
  src/main/views/serverDropdownView.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
  src/renderer/components/SettingsPage.tsx
  src/types/config.ts
  src/types/externalAPI.ts
Labels: 1: UX Review, release-note, Build Apps for PR, QA Deferred

#3171 Automated cherry pick of #3165
  api-types/index.ts
  api-types/lib/index.d.ts
  api-types/package-lock.json
  api-types/package.json
  i18n/en.json
  src/common/Validator.ts
  src/common/communication.ts
  src/common/config/defaultPreferences.ts
  src/common/config/index.ts
  src/common/config/migrationPreferences.ts
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/performanceMonitor.test.js
  src/main/performanceMonitor.ts
  src/main/preload/externalAPI.ts
  src/main/preload/internalAPI.js
  src/main/tray/tray.test.js
  src/main/views/MattermostBrowserView.test.js
  src/main/views/MattermostBrowserView.ts
  src/main/views/downloadsDropdownMenuView.test.js
  src/main/views/downloadsDropdownMenuView.ts
  src/main/views/downloadsDropdownView.test.js
  src/main/views/downloadsDropdownView.ts
  src/main/views/loadingScreen.test.js
  src/main/views/loadingScreen.ts
  src/main/views/modalView.test.js
  src/main/views/modalView.ts
  src/main/views/serverDropdownView.test.js
  src/main/views/serverDropdownView.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
  src/renderer/components/SettingsPage.tsx
  src/types/config.ts
  src/types/externalAPI.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3173 [MM-61058] Upgrade `electron-log`, turn on async logging
  package-lock.json
  package.json
  src/common/log.ts
Labels: 2: Dev Review, release-note

#3178 Automated cherry pick of #3173
  package-lock.json
  package.json
  src/common/log.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3175 [MM-61144][MM-60704] Show badges and allow Edit Server modal for permissions for pre-defined servers
  src/app/serverViewState.ts
  src/renderer/components/NewServerModal.tsx
  src/renderer/dropdown.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#3179 Automated cherry pick of #3175
  src/app/serverViewState.ts
  src/renderer/components/NewServerModal.tsx
  src/renderer/dropdown.tsx
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3181 [MM-61271] Upgrade to Electron v33.0.2
  e2e/package-lock.json
  e2e/package.json
  e2e/patches/nan+2.22.0.patch
  package-lock.json
  package.json
  patches/electron+33.0.2.patch
  src/main/menus/app.ts
  src/main/views/MattermostBrowserView.test.js
  src/main/views/MattermostBrowserView.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#3182 Automated cherry pick of #3181
  e2e/package-lock.json
  e2e/package.json
  e2e/patches/nan+2.22.0.patch
  package-lock.json
  package.json
  patches/electron+33.0.2.patch
  src/main/menus/app.ts
  src/main/views/MattermostBrowserView.test.js
  src/main/views/MattermostBrowserView.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3174 [MM-59483] Remove legacy preload and custom login code
  i18n/en.json
  src/common/communication.ts
  src/common/utils/constants.ts
  src/common/utils/url.test.js
  src/common/utils/url.ts
  src/main/authManager.test.js
  src/main/authManager.ts
  src/main/developerMode.ts
  src/main/menus/app.ts
  src/main/preload/externalAPI.ts
  src/main/preload/internalAPI.js
  src/main/utils.test.js
  src/main/utils.ts
  src/main/views/MattermostBrowserView.test.js
  src/main/views/MattermostBrowserView.ts
  src/main/views/viewManager.ts
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEvents.ts
  src/main/windows/callsWidgetWindow.test.js
  src/main/windows/callsWidgetWindow.ts
  src/renderer/components/ExtraBar.tsx
  src/renderer/components/MainPage.tsx
  src/renderer/css/components/ExtraBar.css
  src/renderer/css/components/index.css
  src/types/settings.ts
  src/types/window.ts
Labels: 4: Reviews Complete, release-note

#3183 Upgrade`windows-focus-assist` to 1.4.0
  package-lock.json
  package.json
Labels: CherryPick/Approved, release-note-none

#3184 Automated cherry pick of #3183
  package-lock.json
  package.json
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3157 MM-60233 - fix issue in kde of focus after minimize
  src/main/utils.ts
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
Labels: 4: Reviews Complete, release-note, Build Apps for PR

#3177 [MM-59823] Migrate `BrowserView` to `WebContentsView`
  e2e/specs/deep_linking/deeplink.test.js
  e2e/specs/menu_bar/dropdown.test.js
  e2e/specs/menu_bar/view_menu.test.js
  i18n/en.json
  package-lock.json
  package.json
  src/common/communication.ts
  src/common/utils/constants.ts
  src/main/app/app.test.js
  src/main/contextMenu.test.js
  src/main/contextMenu.ts
  src/main/diagnostics/steps/internal/utils.test.js
  src/main/diagnostics/steps/internal/utils.ts
  src/main/downloadsManager.test.js
  src/main/preload/externalAPI.ts
  src/main/preload/internalAPI.js
  src/main/views/MattermostWebContentsView.test.js
  src/main/views/MattermostWebContentsView.ts
  src/main/views/downloadsDropdownMenuView.test.js
  src/main/views/downloadsDropdownMenuView.ts
  src/main/views/downloadsDropdownView.test.js
  src/main/views/downloadsDropdownView.ts
  src/main/views/loadingScreen.test.js
  src/main/views/loadingScreen.ts
  src/main/views/modalView.test.js
  src/main/views/modalView.ts
  src/main/views/serverDropdownView.test.js
  src/main/views/serverDropdownView.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/windows/callsWidgetWindow.ts
  src/main/windows/mainWindow.test.js
  src/main/windows/mainWindow.ts
  src/renderer/components/ErrorView.tsx
  src/renderer/components/WelcomeScreen/WelcomeScreen.tsx
  src/types/window.ts
Labels: 4: Reviews Complete, release-note-none
