Repository mattermost/desktop, pull requests merged in 2024-04, with the labels that each got.

#2994 Minor fixes for the Compatibility Matrix Test
  .github/workflows/compatibility-matrix-testing.yml
Labels: release-note

#2995 Small package update
  package-lock.json
Labels: 4: Reviews Complete, release-note-none

#2998 [MM-57348] Support notification metrics from the Desktop App client
  .eslintignore
  api-types/index.ts
  api-types/lib/index.d.ts
  api-types/lib/index.js
  api-types/package.json
  api-types/tsconfig.json
  src/main/app/initialize.ts
  src/main/app/intercom.ts
  src/main/notifications/index.ts
  src/main/preload/externalAPI.ts
Labels: 4: Reviews Complete, release-note-none

#3001 Translations update from Mattermost Weblate
  i18n/sr.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#2999 Various QoL fixes for Desktop App
  .eslintrc.json
  api-types/index.ts
  api-types/lib/index.d.ts
  api-types/package.json
  e2e/specs/menu_bar/view_menu.test.js
  e2e/utils/analyze-flaky-test.js
  package-lock.json
  package.json
  src/app/serverViewState.test.js
  src/app/serverViewState.ts
  src/common/appState.ts
  src/main/app/initialize.ts
  src/main/app/utils.ts
  src/main/preload/externalAPI.ts
  src/main/views/viewManager.test.js
  src/main/views/viewManager.ts
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEvents.ts
  src/renderer/components/MainPage.tsx
  src/renderer/index.tsx
  webpack.config.base.js
Labels: 2: Dev Review, release-note

#3002 [MM-57736] Force maximize state when restoring the window
  src/main/windows/mainWindow.ts
Labels: 2: Dev Review, release-note

#3003 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, release-note-none

#3005 [MM-57348] Change `result` to `status` as a better descriptor of the notification status
  api-types/index.ts
  api-types/lib/index.d.ts
  api-types/package-lock.json
  api-types/package.json
  package-lock.json
  src/main/notifications/index.ts
  src/main/windows/mainWindow.ts
Labels: 4: Reviews Complete, release-note-none

#3006 Fix settings window disappearing on macOS when dragged to another monitor
  src/main/app/app.ts
  src/main/app/utils.test.js
  src/main/app/utils.ts
  src/main/windows/settingsWindow.ts
Labels: 4: Reviews Complete, release-note

#3007 Move Settings Window into Modal
  src/main/app/config.ts
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/app/intercom.ts
  src/main/menus/app.test.js
  src/main/menus/app.ts
  src/main/menus/tray.test.js
  src/main/menus/tray.ts
  src/main/tray/tray.ts
  src/main/views/modalManager.ts
  src/main/windows/settingsWindow.ts
  src/renderer/components/SettingsPage.tsx
  src/renderer/css/lazy/modals-dark.lazy.css
  src/renderer/css/lazy/settings-dark.lazy.css
  src/renderer/css/settings.css
  src/renderer/modals/settings/settings.tsx
  webpack.config.renderer.js
Labels: 4: Reviews Complete, release-note, Run Desktop E2E Tests

#3010 [MM-57912] Disable `--inspect` on built application
  scripts/afterpack.js
Labels: release-note, Build Apps for PR

#3009 Fix shouldNotify notification reason
  src/main/notifications/index.ts
Labels: 4: Reviews Complete, release-note-none

#3011 Revert upload-artifact where homonymous jobs are used
  .github/workflows/nightly-main.yml
  .github/workflows/nightly-rainforest.yml
  .github/workflows/release.yaml
Labels: release-note-none

#3012 Revert download-artifact for problematic jobs
  .github/workflows/nightly-main.yml
  .github/workflows/nightly-rainforest.yml
  .github/workflows/release.yaml
Labels: release-note-none

#3013 Translations update from Mattermost Weblate
  i18n/hr.json
Labels: do-not-merge/release-note-label-needed

#3014 Fix focus test cases
  e2e/specs/focus.test.js
Labels: 4: Reviews Complete, do-not-merge/release-note-label-needed

#3015 fix: Upgrade upload/download actions
  .github/workflows/nightly-main.yml
  .github/workflows/nightly-rainforest.yml
  .github/workflows/release.yaml
Labels: release-note, kind/bug

#3018 Automated cherry pick of #3017
  src/main/app/utils.test.js
  src/main/app/utils.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3019 Bump version to v5.9
  package-lock.json
  package.json
Labels: release-note-none

#3022 [MM-58065] Force the packager to create the version directory before packing
  electron-builder.json
  scripts/beforepack.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#3023 Automated cherry pick of #3022
  electron-builder.json
  scripts/beforepack.js
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed
