Repository mattermost/desktop, pull requests merged in 2024-08, with the labels that each got.

#3116 [MM-59252] Fix loading screen CSS
  src/renderer/css/components/LoadingScreen.css
  src/renderer/css/components/WelcomeScreen.scss
Labels: 4: Reviews Complete, release-note-none

#3120 [MM-59552] Remove `unsafe-inline` from internal CSP, replace with nonce and rework some dynamic styling
  package-lock.json
  package.json
  src/common/communication.ts
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/nonceManager.ts
  src/main/preload/internalAPI.js
  src/main/views/downloadsDropdownView.ts
  src/renderer/components/SettingsPage.tsx
  src/renderer/components/TabBar.tsx
  src/renderer/css/lazy/modals-dark.lazy.css
  src/renderer/css/modals-dark.scss
  src/renderer/dropdown.tsx
  src/renderer/index.html
  src/renderer/modals/darkMode.ts
  src/types/window.ts
  webpack.config.renderer.js
Labels: 4: Reviews Complete, release-note-none

#3121 Translations update from Mattermost Weblate
  i18n/it.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#3126 Fixed #2977 - Fixed the dark-mode style for the download location box in settings
  src/renderer/components/SettingsPage.tsx
Labels: release-note, Build Apps for PR, Contributor

#3134 Translations update from Mattermost Weblate
  i18n/sv.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod
