Repository mattermost/desktop, pull requests merged in 2025-03, with the labels that each got.

#3360 [MM-63265] Use constants for modal keys
  src/app/serverViewState.ts
  src/common/constants.ts
  src/main/app/intercom.ts
  src/main/authManager.test.js
  src/main/authManager.ts
  src/main/certificateManager.ts
  src/main/menus/app.ts
  src/main/menus/tray.ts
Labels: 4: Reviews Complete, release-note-none

#3365 Fix an issue where the incompatible server check defaults to show the screen when the server info is not present
  src/main/views/MattermostWebContentsView.ts
Labels: 2: Dev Review, CherryPick/Approved, release-note

#3366 Automated cherry pick of #3365
  src/main/views/MattermostWebContentsView.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3370 Combine changes from other PR
  .github/workflows/e2e-functional-template.yml
  .github/workflows/e2e-functional.yml
  e2e/package-lock.json
  e2e/package.json
  e2e/patches/nan+2.22.0.patch
  e2e/specs/linux_dark_mode.test.js
Labels: release-note-none

#3371 [MM-63399] Add a changelog link for when the app auto updates
  i18n/en.json
  src/common/communication.ts
  src/common/constants.ts
  src/main/preload/internalAPI.js
  src/main/views/viewManager.ts
  src/renderer/components/DownloadsDropdown/Update/UpdateAvailable.tsx
  src/renderer/css/downloadsDropdown.scss
  src/types/window.ts
Labels: 4: Reviews Complete, release-note

#3355 Fix issue with media permissions on Linux
  src/main/permissionsManager.test.js
  src/main/permissionsManager.ts
Labels: 4: Reviews Complete, release-note, Contributor
