Repository mattermost/desktop, pull requests merged in 2025-04, with the labels that each got.

#3392 Translations update from Mattermost Weblate
  i18n/fi.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#3394 Fix: Build Mac no dmg job failing due to MACOS_NOTIFICATION_STATE_NO_SDK_CHECK
  .github/workflows/ci.yaml
Labels: release-note-none

#3398 [MM-63842] Upgrade to Electron v35.2.0
  package-lock.json
  package.json
  patches/electron+34.0.1.patch
  src/main/badge.ts
  src/main/notifications/index.test.ts
  src/main/notifications/index.ts
  src/main/performanceMonitor.ts
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEventsCommon.ts
Labels: 4: Reviews Complete, release-note

#3399 Bump to version 5.13
  package-lock.json
  package.json
Labels: release-note-none

#3400 Fix mac build again
  .github/workflows/build-for-pr.yml
  .github/workflows/nightly-main.yml
  .github/workflows/nightly-rainforest.yml
  .github/workflows/release-mas.yaml
  .github/workflows/release.yaml
Labels: CherryPick/Approved, release-note-none

#3401 Manual SBOM trigger
  .github/workflows/snyk-sbom.yml
Labels: release-note-none

#3407 Bump sbom version
  .github/workflows/snyk-sbom.yml
Labels: release-note-none

#3408 Fix SBOM file name
  .github/workflows/snyk-sbom.yml
Labels: 4: Reviews Complete, release-note-none

#3413 Translations update from Mattermost Weblate
  i18n/zh-CN.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#3415 Automated cherry pick of #3409
  src/main/views/viewManager.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3416 Automated cherry pick of #3409
  src/main/views/viewManager.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3411 [MM-63849] Account for minor versions >= 10
  scripts/generate_release_post.sh
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#3417 Automated cherry pick of #3411
  scripts/generate_release_post.sh
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3418 Automated cherry pick of #3411
  scripts/generate_release_post.sh
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed
