Repository mattermost/desktop, pull requests merged in 2025-07, with the labels that each got.

#3453 MM-62005 Change UrlView to always stay mounted
  src/common/communication.ts
  src/main/preload/internalAPI.js
  src/main/views/viewManager.ts
  src/renderer/components/urlDescription.tsx
  src/renderer/modals/urlView/urlView.tsx
  src/types/window.ts
Labels: 4: Reviews Complete, release-note, Build Apps for PR, QA Deferred

#3454 In-App Links in Channel's Bookmarks
  src/main/views/webContentEvents.ts
  src/main/views/webContentEventsCommon.ts
Labels: release-note, Contributor

#3452 E2E: Run E2E tests with Server Init
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/e2e-functional-template.yml
  .github/workflows/e2e-functional.yml
  e2e/modules/environment.js
Labels: release-note-none

#3462 [MM-64867] Upgrade to Electron v37.2.2, some other package changes
  e2e/modules/environment.js
  package-lock.json
  package.json
  scripts/watch.js
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/menus/app.test.js
Labels: 2: Dev Review, release-note

#3470 Automated cherry pick of #3464
  NOTICE.txt
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3471 Bump to version v6.0
  package-lock.json
  package.json
Labels: release-note-none
