Repository mattermost/desktop, pull requests merged in 2025-05, with the labels that each got.

#3419 Translations update from Mattermost Weblate
  i18n/pt-BR.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#3431 Automated cherry pick of #3430
  src/renderer/components/SettingsModal/components/ServerSetting.tsx
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3429 [MM-62005] Use `ready-to-show` event for focus workaround for URL view
  src/main/views/viewManager.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#3433 Automated cherry pick of #3429
  src/main/views/viewManager.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3435 Automated cherry pick of #3394
  .github/workflows/ci.yaml
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3434 Automated cherry pick of #3400
  .github/workflows/build-for-pr.yml
  .github/workflows/nightly-main.yml
  .github/workflows/nightly-rainforest.yml
  .github/workflows/release-mas.yaml
  .github/workflows/release.yaml
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3436 Don't require the update file to exist
  scripts/patch_updater_yml.sh
Labels: release-note-none

#3437 Automated cherry pick of #3436
  scripts/patch_updater_yml.sh
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3432 Automated cherry pick of #3429
  src/main/views/viewManager.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3441 [MM-64399] Fix crash in electron-context-menu
  patches/electron-context-menu+4.0.4.patch
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#3443 Automated cherry pick of #3441
  patches/electron-context-menu+4.0.4.patch
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed
