Repository mattermost/desktop, pull requests merged in 2025-09, with the labels that each got.

#3483 Automated cherry pick of #3477
  src/main/tray/tray.test.js
  src/main/views/loadingScreen.test.js
  src/main/views/loadingScreen.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed, Do Not Merge/Awaiting Release

#3485 Automated cherry pick of #3476
  i18n/en.json
  src/main/views/webContentEvents.test.js
  src/main/views/webContentEvents.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed, Do Not Merge/Awaiting Release

#3489 [MM-65085] Pre auth headers
  e2e/specs/server_management/add_server_modal.test.js
  e2e/specs/server_management/configure_server_modal.test.js
  e2e/specs/server_management/edit_server_modal.test.js
  e2e/specs/startup/welcome_screen_modal.test.js
  i18n/en.json
  src/app/serverViewState.test.js
  src/app/serverViewState.ts
  src/common/communication.ts
  src/common/constants/secureStorage.ts
  src/common/servers/MattermostServer.ts
  src/common/servers/serverManager.ts
  src/common/utils/constants.ts
  src/jest/jestSetup.js
  src/main/app/initialize.test.js
  src/main/app/initialize.ts
  src/main/app/intercom.test.js
  src/main/app/intercom.ts
  src/main/app/utils.test.js
  src/main/constants.ts
  src/main/preAuthSecret.ts
  src/main/preload/internalAPI.js
  src/main/secureStorage.ts
  src/main/server/serverAPI.ts
  src/main/server/serverInfo.ts
  src/main/views/MattermostWebContentsView.ts
  src/renderer/components/ConfigureServer.tsx
  src/renderer/components/NewServerModal.tsx
  src/renderer/css/components/ConfigureServer.scss
  src/renderer/css/components/Input.scss
  src/renderer/css/components/NewServerModal.scss
  src/types/config.ts
  src/types/server.ts
  src/types/window.ts
Labels: 2: Dev Review, QA Review Done, release-note, Build Apps for PR, E2E/Run

#3501 [MM-65617] Allow scrolling in modals, fix other modal issues
  src/renderer/components/Modal.tsx
  src/renderer/css/components/Modal.scss
Labels: 4: Reviews Complete, release-note, Build Apps for PR

#3513 Translations update from Mattermost Weblate
  i18n/de.json
  i18n/ko.json
  i18n/pl.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: do-not-merge/release-note-label-needed, Do Not Merge/Mattermod

#3509 [MM-65011][MM-65664] Remove extraneous logging of potentially sensitive info, clear server data on removal
  src/app/callsWidgetWindow.ts
  src/app/mainWindow/downloadsDropdownMenuView.ts
  src/app/mainWindow/downloadsDropdownView.ts
  src/app/mainWindow/mainWindow.ts
  src/app/mainWindow/modals/modalManager.ts
  src/app/navigationManager.ts
  src/app/serverHub.ts
  src/app/system/badge.ts
  src/app/tabs/tabManager.ts
  src/app/views/MattermostWebContentsView.ts
  src/app/views/pluginsPopUps.ts
  src/app/views/urlView.ts
  src/app/views/webContentEventsCommon.test.ts
  src/app/views/webContentEventsCommon.ts
  src/app/views/webContentsManager.ts
  src/app/windows/baseWindow.ts
  src/app/windows/popoutManager.ts
  src/common/appState.ts
  src/common/config/RegistryConfig.ts
  src/common/config/index.ts
  src/common/log.ts
  src/common/servers/serverManager.ts
  src/common/views/viewManager.ts
  src/main/UserActivityMonitor.ts
  src/main/app/app.ts
  src/main/app/config.ts
  src/main/app/initialize.ts
  src/main/app/intercom.ts
  src/main/app/utils.ts
  src/main/autoUpdater.ts
  src/main/downloadsManager.ts
  src/main/i18nManager.ts
  src/main/notifications/index.ts
  src/main/performanceMonitor.ts
  src/main/secureStorage.ts
  src/main/security/allowProtocolDialog.ts
  src/main/security/permissionsManager.ts
  src/main/server/serverAPI.ts
Labels: 4: Reviews Complete, release-note

#3514 Fix server removal bug
  src/app/mainWindow/mainWindow.ts
  src/app/serverHub.ts
  src/common/servers/serverManager.ts
  src/common/views/viewManager.test.js
  src/common/views/viewManager.ts
Labels: release-note-none

#3516 [MM-64732] Enable hardened runtime on MAS build
  electron-builder.json
  resources/mac/entitlements.mas.inherit.plist
Labels: 2: Dev Review, release-note

#3517 [MM-65620] Add clear cache and reload link to the error screen
  i18n/en.json
  src/app/menus/app.test.js
  src/app/menus/app.ts
  src/app/preload/internalAPI.js
  src/app/tabs/tabManager.test.js
  src/app/tabs/tabManager.ts
  src/app/views/MattermostWebContentsView.ts
  src/app/views/webContentsManager.test.js
  src/app/views/webContentsManager.ts
  src/app/windows/popoutManager.test.js
  src/app/windows/popoutManager.ts
  src/common/communication.ts
  src/renderer/components/ConnectionErrorView.tsx
  src/types/window.ts
Labels: release-note, Build Apps for PR
