Repository mattermost/desktop, pull requests merged in 2025-02, with the labels that each got.

#3299 Reminding myself to upgrade Electron and bump the release version for future releases
  scripts/release.sh
Labels: 2: Dev Review, release-note-none

#3319 [MM-62589] Push cross-spawn to v7.0.6
  e2e/package-lock.json
  package-lock.json
Labels: 2: Dev Review, Do Not Merge, CherryPick/Approved, release-note-none

#3320 [MM-62781] Wait for nonce before requesting info that will update the server dropdown component
  src/renderer/dropdown.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note, Build Apps for PR

#3305 Fix(e2e): E2E report should be available in the community channel.
  e2e/utils/artifacts.js
  src/main/contextMenu.ts
  src/main/views/MattermostWebContentsView.ts
  src/main/views/modalView.ts
Labels: release-note-none

#3342 feat: Add dependabot for gha
  .github/dependabot.yaml
Labels: release-note, kind/feature

#3345 Allow for env variable to set the username for E2E tests
  e2e/modules/environment.js
Labels: 4: Reviews Complete, release-note-none

#3347 Cherry-pick of #3300 to `release-5.11`
  i18n/en.json
  src/common/communication.ts
  src/main/preload/internalAPI.js
  src/main/views/viewManager.ts
  src/renderer/components/ErrorView.tsx
  src/renderer/components/Images/alert.tsx
  src/renderer/components/MainPage.tsx
  src/renderer/css/_css_variables.scss
  src/renderer/css/components/ErrorView.css
  src/renderer/css/components/ErrorView.scss
  src/renderer/css/components/MainPage.css
  src/renderer/css/components/index.css
  src/renderer/css/index.css
  src/types/window.ts
Labels: 2: Dev Review, release-note-none

#3348 [MM-63224] Add incompatible server screen
  i18n/en.json
  src/app/serverViewState.ts
  src/common/communication.ts
  src/common/config/buildConfig.ts
  src/common/config/index.ts
  src/common/constants.ts
  src/main/app/initialize.ts
  src/main/preload/internalAPI.js
  src/main/views/MattermostWebContentsView.test.js
  src/main/views/MattermostWebContentsView.ts
  src/main/views/viewManager.ts
  src/renderer/components/ConnectionErrorView.tsx
  src/renderer/components/ErrorView.tsx
  src/renderer/components/IncompatibleErrorView.tsx
  src/renderer/components/MainPage.tsx
  src/types/config.ts
  src/types/window.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note, QA Deferred

#3350 Add aider to gitignore
  .gitignore
Labels: release-note-none

#3323 Automated cherry pick of #3320
  src/renderer/dropdown.tsx
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed, Do Not Merge/Awaiting Release

#3322 Automated cherry pick of #3314
  scripts/patch_updater_yml.sh
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed, Do Not Merge/Awaiting Release

#3321 Automated cherry pick of #3319
  e2e/package-lock.json
  package-lock.json
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed, Do Not Merge/Awaiting Release

#3356 Reload server info on retry
  src/main/views/MattermostWebContentsView.test.js
  src/main/views/MattermostWebContentsView.ts
Labels: 4: Reviews Complete, CherryPick/Candidate, release-note-none

#3357 Automated cherry pick of #3356
  src/main/views/MattermostWebContentsView.test.js
  src/main/views/MattermostWebContentsView.ts
Labels: release-note-none, Docs/Not Needed, AutomatedCherryPick, Changelog/Not Needed

#3337 [MM-61717] Refresh Settings Modal without Bootstrap
  e2e/specs/focus.test.js
  e2e/specs/settings.test.js
  e2e/specs/settings/keyboard_shortcuts.test.js
  i18n/en.json
  src/app/serverViewState.ts
  src/common/communication.ts
  src/main/app/intercom.ts
  src/main/notifications/index.ts
  src/main/preload/internalAPI.js
  src/renderer/components/AutoSaveIndicator.tsx
  src/renderer/components/Images/server-small.tsx
  src/renderer/components/Modal.tsx
  src/renderer/components/SettingsModal/SettingsModal.scss
  src/renderer/components/SettingsModal/components/CheckSetting.scss
  src/renderer/components/SettingsModal/components/CheckSetting.tsx
  src/renderer/components/SettingsModal/components/DownloadSetting.scss
  src/renderer/components/SettingsModal/components/DownloadSetting.tsx
  src/renderer/components/SettingsModal/components/NotificationSetting.tsx
  src/renderer/components/SettingsModal/components/RadioSetting.scss
  src/renderer/components/SettingsModal/components/RadioSetting.tsx
  src/renderer/components/SettingsModal/components/SelectSetting.scss
  src/renderer/components/SettingsModal/components/SelectSetting.tsx
  src/renderer/components/SettingsModal/components/ServerSetting.scss
  src/renderer/components/SettingsModal/components/ServerSetting.tsx
  src/renderer/components/SettingsModal/components/SpellCheckerSetting.scss
  src/renderer/components/SettingsModal/components/SpellCheckerSetting.tsx
  src/renderer/components/SettingsModal/components/UpdatesSetting.scss
  src/renderer/components/SettingsModal/components/UpdatesSetting.tsx
  src/renderer/components/SettingsModal/definition.tsx
  src/renderer/components/SettingsModal/index.tsx
  src/renderer/components/SettingsPage.tsx
  src/renderer/css/_css_variables.scss
  src/renderer/css/components/NewServerModal.scss
  src/renderer/css/modals-dark.scss
  src/renderer/css/modals.css
  src/renderer/css/settings.css
  src/renderer/modals/settings/settings.tsx
  src/types/config.ts
  src/types/settings.ts
  src/types/window.ts
Labels: 4: Reviews Complete, release-note, Build Apps for PR

#3358 [MM-62448] Remove react-bootstrap, bootstrap and dependencies
  NOTICE.txt
  package-lock.json
  package.json
  src/renderer/components/RemoveServerModal.tsx
Labels: 2: Dev Review, release-note
